run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - exhaustive

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
