run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - exhaustive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
