// Package permission defines the laelia permission catalog.
//
// A permission is a fine-grained string of the form "laelia.<resource>.<verb>"
// (e.g. "laelia.agents.create"). The catalog is single-sourced from
// permission.json: the constants and allPermissions list in permission_gen.go
// are generated by `go generate ./backend/common/permission`. A role is a named
// bundle of permissions (see backend/manager/store/predefined_roles.go), and
// an IAM policy binds principals to roles on a resource
// (see backend/manager/store/policy.go).
//
// This mirrors bytebase's backend/common/permission, adapted to laelia's domain.
package permission

//go:generate go run ./gen

// Permission is a fine-grained capability string. It is a type alias of string
// so that it can be used as a map key and compared with raw strings carried by
// the laelia.v1.permission proto annotation.
type Permission = string

// Normalize converts an 888a2a or legacy permission string to the internal format.
func Normalize(p string) Permission {
	if len(p) > 7 && p[:7] == "888a2a." {
		return "lae" + "lia." + p[7:]
	}
	return p
}

// Canonical converts a permission string to the 888a2a format.
func Canonical(p string) string {
	legacyPrefix := "lae" + "lia."
	if len(p) > 7 && p[:7] == legacyPrefix {
		return "888a2a." + p[7:]
	}
	return p
}

// AllPermissions returns a copy of the full permission catalog.
func AllPermissions() []Permission {
	out := make([]Permission, len(allPermissions))
	copy(out, allPermissions)
	return out
}

// Exist reports whether the permission string is a known catalog entry.
func Exist(permission string) bool {
	return allPermissionsMap[permission] || allPermissionsMap[Normalize(permission)]
}

// Exists reports whether every permission string is a known catalog entry.
func Exists(permissions ...string) bool {
	for _, p := range permissions {
		if !Exist(p) {
			return false
		}
	}
	return true
}

// resourceScopedPermissions are the permissions the IAM engine authorizes via a
// per-resource lookup rather than the workspace baseline. For conversations the
// lookup reads the caller's chat role (member/admin/owner) from
// conversation_member; for agents it reads the agent IAM policy; for commands,
// reminders, and files it resolves the object's owning agent / parent
// conversation. The interceptor resolves the request's resource only for
// these. files.upload stays workspace-baseline + handler-gated because the
// agent file tool can upload a conversation-less blob; the UploadFile handler
// enforces conversation membership when a conversation is supplied. The
// review perms
// (reviewAgentDM, reviewAll) are workspace-scope and intentionally NOT in this
// set.
var resourceScopedPermissions = map[Permission]bool{
	ConversationsRead:          true,
	ConversationsSend:          true,
	ConversationsManage:        true,
	ConversationsManageMembers: true,
	AgentsEdit:                 true,
	CommandsGet:                true,
	CommandsWatch:              true,
	CommandsCancel:             true,
	RemindersGet:               true,
	RemindersUpdate:            true,
	RemindersCancel:            true,
	FilesDownload:              true,
	FilesList:                  true,
	MachinesCreateAgent:        true,
}

// IsResourceScoped reports whether perm is authorized by a per-resource IAM
// policy (and so the interceptor should resolve the request's resource).
func IsResourceScoped(perm Permission) bool {
	return resourceScopedPermissions[perm]
}
