// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/agent.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tbdavid2019/888a2a/backend/generated-go/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "laelia.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceCreateAgentProcedure is the fully-qualified name of the AgentService's CreateAgent
	// RPC.
	AgentServiceCreateAgentProcedure = "/laelia.v1.AgentService/CreateAgent"
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/laelia.v1.AgentService/ListAgents"
	// AgentServiceGetAgentProcedure is the fully-qualified name of the AgentService's GetAgent RPC.
	AgentServiceGetAgentProcedure = "/laelia.v1.AgentService/GetAgent"
	// AgentServiceUpdateAgentProcedure is the fully-qualified name of the AgentService's UpdateAgent
	// RPC.
	AgentServiceUpdateAgentProcedure = "/laelia.v1.AgentService/UpdateAgent"
	// AgentServiceTransferAgentOwnershipProcedure is the fully-qualified name of the AgentService's
	// TransferAgentOwnership RPC.
	AgentServiceTransferAgentOwnershipProcedure = "/laelia.v1.AgentService/TransferAgentOwnership"
	// AgentServiceDeleteAgentProcedure is the fully-qualified name of the AgentService's DeleteAgent
	// RPC.
	AgentServiceDeleteAgentProcedure = "/laelia.v1.AgentService/DeleteAgent"
	// AgentServiceStopAgentProcedure is the fully-qualified name of the AgentService's StopAgent RPC.
	AgentServiceStopAgentProcedure = "/laelia.v1.AgentService/StopAgent"
	// AgentServiceStartAgentProcedure is the fully-qualified name of the AgentService's StartAgent RPC.
	AgentServiceStartAgentProcedure = "/laelia.v1.AgentService/StartAgent"
	// AgentServiceRotateAgentTokenProcedure is the fully-qualified name of the AgentService's
	// RotateAgentToken RPC.
	AgentServiceRotateAgentTokenProcedure = "/laelia.v1.AgentService/RotateAgentToken"
	// AgentServiceRevokeAgentTokenProcedure is the fully-qualified name of the AgentService's
	// RevokeAgentToken RPC.
	AgentServiceRevokeAgentTokenProcedure = "/laelia.v1.AgentService/RevokeAgentToken"
	// AgentServiceForceDisconnectAgentProcedure is the fully-qualified name of the AgentService's
	// ForceDisconnectAgent RPC.
	AgentServiceForceDisconnectAgentProcedure = "/laelia.v1.AgentService/ForceDisconnectAgent"
	// AgentServiceListAgentSessionsProcedure is the fully-qualified name of the AgentService's
	// ListAgentSessions RPC.
	AgentServiceListAgentSessionsProcedure = "/laelia.v1.AgentService/ListAgentSessions"
	// AgentServiceUpdateAgentACPConfigProcedure is the fully-qualified name of the AgentService's
	// UpdateAgentACPConfig RPC.
	AgentServiceUpdateAgentACPConfigProcedure = "/laelia.v1.AgentService/UpdateAgentACPConfig"
	// AgentServiceUpdateAgentMcpConfigProcedure is the fully-qualified name of the AgentService's
	// UpdateAgentMcpConfig RPC.
	AgentServiceUpdateAgentMcpConfigProcedure = "/laelia.v1.AgentService/UpdateAgentMcpConfig"
	// AgentServiceRefreshAgentProvidersProcedure is the fully-qualified name of the AgentService's
	// RefreshAgentProviders RPC.
	AgentServiceRefreshAgentProvidersProcedure = "/laelia.v1.AgentService/RefreshAgentProviders"
	// AgentServiceListAgentWorkspaceProcedure is the fully-qualified name of the AgentService's
	// ListAgentWorkspace RPC.
	AgentServiceListAgentWorkspaceProcedure = "/laelia.v1.AgentService/ListAgentWorkspace"
	// AgentServiceReadAgentWorkspaceFileProcedure is the fully-qualified name of the AgentService's
	// ReadAgentWorkspaceFile RPC.
	AgentServiceReadAgentWorkspaceFileProcedure = "/laelia.v1.AgentService/ReadAgentWorkspaceFile"
	// AgentServiceListPiModelsProcedure is the fully-qualified name of the AgentService's ListPiModels
	// RPC.
	AgentServiceListPiModelsProcedure = "/laelia.v1.AgentService/ListPiModels"
	// AgentServiceConnectAgentProcedure is the fully-qualified name of the AgentService's ConnectAgent
	// RPC.
	AgentServiceConnectAgentProcedure = "/laelia.v1.AgentService/ConnectAgent"
	// AgentServiceAgentHeartbeatProcedure is the fully-qualified name of the AgentService's
	// AgentHeartbeat RPC.
	AgentServiceAgentHeartbeatProcedure = "/laelia.v1.AgentService/AgentHeartbeat"
	// AgentServiceAgentDisconnectProcedure is the fully-qualified name of the AgentService's
	// AgentDisconnect RPC.
	AgentServiceAgentDisconnectProcedure = "/laelia.v1.AgentService/AgentDisconnect"
	// AgentServiceRefreshAgentTokenProcedure is the fully-qualified name of the AgentService's
	// RefreshAgentToken RPC.
	AgentServiceRefreshAgentTokenProcedure = "/laelia.v1.AgentService/RefreshAgentToken"
	// AgentServiceUploadAgentAvatarProcedure is the fully-qualified name of the AgentService's
	// UploadAgentAvatar RPC.
	AgentServiceUploadAgentAvatarProcedure = "/laelia.v1.AgentService/UploadAgentAvatar"
	// AgentServiceDownloadAgentAvatarProcedure is the fully-qualified name of the AgentService's
	// DownloadAgentAvatar RPC.
	AgentServiceDownloadAgentAvatarProcedure = "/laelia.v1.AgentService/DownloadAgentAvatar"
	// AgentServiceDeleteAgentAvatarProcedure is the fully-qualified name of the AgentService's
	// DeleteAgentAvatar RPC.
	AgentServiceDeleteAgentAvatarProcedure = "/laelia.v1.AgentService/DeleteAgentAvatar"
	// AgentServiceHelloProcedure is the fully-qualified name of the AgentService's Hello RPC.
	AgentServiceHelloProcedure = "/laelia.v1.AgentService/Hello"
)

// AgentServiceClient is a client for the laelia.v1.AgentService service.
type AgentServiceClient interface {
	// CreateAgent is handler-gated (no permission annotation): the machine's
	// creator, a workspace admin, or a principal bound to
	// roles/machineAgentCreator on the machine's IAM policy may create agents on
	// it. The machine-scoped check is enforced by the handler via
	// laelia.machines.createAgent against the machine's IAM policy.
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	// UpdateAgent patches a single mutable agent field. Only allow_add_to_channel
	// is supported initially (any other update_mask path is rejected). Authorized
	// in the handler for the agent's owner or a workspace admin; the IAM
	// interceptor's agents.edit is admin-only, so this RPC carries no permission
	// annotation and is handler-gated.
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error)
	// TransferAgentOwnership reassigns the agent's owner to another user. The new
	// owner takes effect immediately and unilaterally (no acceptance required);
	// the previous owner loses owner authority at once. Authorized in the handler
	// for the agent's current owner or a workspace admin; like UpdateAgent this
	// RPC carries no permission annotation (agents.edit is admin-only) and is
	// handler-gated via canEditAgent.
	TransferAgentOwnership(context.Context, *connect.Request[v1.TransferAgentOwnershipRequest]) (*connect.Response[v1.TransferAgentOwnershipResponse], error)
	// DeleteAgent soft-deletes an agent. Authorized in the handler for the
	// agent's owner or a holder of laelia.agents.edit on the agent; no
	// permission annotation so the owner short-circuit can run.
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// StopAgent stops an agent: its machine runner is torn down and it no
	// longer processes session messages or runs an LLM agent until StartAgent.
	// The agent row is preserved (not deleted) and remains visible. Authorized
	// in the handler for the agent's owner or a holder of laelia.agents.edit.
	StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// StartAgent resumes a stopped agent: its machine runner is re-spawned and
	// it resumes processing session messages. No-op (still succeeds) if the
	// agent is already enabled. Authorized in the handler for the agent's owner
	// or a holder of laelia.agents.edit.
	StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// Token rotation: generate a new bootstrap token, old token invalid after
	// grace period. Authorized in the handler for the agent's owner or a holder
	// of laelia.agents.edit on the agent; no permission annotation so the owner
	// short-circuit can run.
	RotateAgentToken(context.Context, *connect.Request[v1.RotateAgentTokenRequest]) (*connect.Response[v1.RotateAgentTokenResponse], error)
	// Token revocation: revoke all tokens for the agent. Authorized in the
	// handler for the agent's owner or a holder of laelia.agents.edit on the
	// agent; no permission annotation so the owner short-circuit can run.
	RevokeAgentToken(context.Context, *connect.Request[v1.RevokeAgentTokenRequest]) (*connect.Response[v1.RevokeAgentTokenResponse], error)
	// Force-disconnects an agent connection. Authorized in the handler for the
	// agent's owner or a holder of laelia.agents.edit on the agent; no
	// permission annotation so the owner short-circuit can run.
	ForceDisconnectAgent(context.Context, *connect.Request[v1.ForceDisconnectAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// List agent sessions
	ListAgentSessions(context.Context, *connect.Request[v1.ListAgentSessionsRequest]) (*connect.Response[v1.ListAgentSessionsResponse], error)
	// Update the agent's ACP config. Handler-gated (no permission annotation):
	// the agent's owner or a workspace admin may update it. Setting a legacy
	// inline api_provider/api_key additionally requires laelia.agents.edit (only
	// workspace admin today); owners without it must use a global provider.
	UpdateAgentACPConfig(context.Context, *connect.Request[v1.UpdateAgentACPConfigRequest]) (*connect.Response[emptypb.Empty], error)
	// UpdateAgentMcpConfig replaces the MCP servers enabled on an agent. Only
	// servers the caller may use (members of the server's user/group list, or
	// workspace admin) are accepted. Handler-gated like UpdateAgentACPConfig:
	// the agent's owner or a workspace admin may update it.
	UpdateAgentMcpConfig(context.Context, *connect.Request[v1.UpdateAgentMcpConfigRequest]) (*connect.Response[emptypb.Empty], error)
	// Ask the agent daemon to re-probe its host for installed LLM agent
	// providers and their models. Returns the freshly discovered provider list
	// (also persisted into agent.info.available_providers). Authorized in the
	// handler for the agent's owner or a holder of laelia.agents.edit on the
	// agent; no permission annotation so the owner short-circuit can run.
	RefreshAgentProviders(context.Context, *connect.Request[v1.RefreshAgentProvidersRequest]) (*connect.Response[v1.RefreshAgentProvidersResponse], error)
	// ListAgentWorkspace lists one directory level of an agent's workspace on its
	// machine (~/.laelia/<machineID>/<agentID>/), lazily loading the tree level by
	// level. Workspace content is sensitive: authorized in the handler for the
	// agent's owner or a workspace admin (canEditAgent); like UpdateAgent this
	// RPC carries no permission annotation (agents.edit is admin-only) and is
	// handler-gated.
	ListAgentWorkspace(context.Context, *connect.Request[v1.ListAgentWorkspaceRequest]) (*connect.Response[v1.ListAgentWorkspaceResponse], error)
	// ReadAgentWorkspaceFile reads a single workspace file for text/image preview.
	// Same handler-gated authorization as ListAgentWorkspace (owner or workspace
	// admin). Sensitive files (secret/credential/token patterns) are rejected by
	// the machine app and surface as a per-file error, not a transport error.
	ReadAgentWorkspaceFile(context.Context, *connect.Request[v1.ReadAgentWorkspaceFileRequest]) (*connect.Response[v1.ReadAgentWorkspaceFileResponse], error)
	// List the models a built-in pi agent's LLM API provider exposes. The manager
	// proxies the provider's model-listing HTTP API (DeepSeek `GET /models` with
	// the caller's api_key; OpenRouter `GET /models`, public) so the model list is
	// fetched dynamically rather than hardcoded. Not agent-scoped: the add-agent
	// form calls it before the agent exists. Admin (agents.edit) only.
	ListPiModels(context.Context, *connect.Request[v1.ListPiModelsRequest]) (*connect.Response[v1.ListPiModelsResponse], error)
	// Agent initial connection using bootstrap token
	ConnectAgent(context.Context, *connect.Request[v1.ConnectAgentRequest]) (*connect.Response[v1.ConnectAgentResponse], error)
	// Agent heartbeat
	AgentHeartbeat(context.Context, *connect.Request[v1.AgentHeartbeatRequest]) (*connect.Response[v1.AgentHeartbeatResponse], error)
	// Agent graceful disconnect
	AgentDisconnect(context.Context, *connect.Request[v1.AgentDisconnectRequest]) (*connect.Response[emptypb.Empty], error)
	// Agent refreshes access token
	RefreshAgentToken(context.Context, *connect.Request[v1.RefreshAgentTokenRequest]) (*connect.Response[v1.RefreshAgentTokenResponse], error)
	// UploadAgentAvatar replaces an agent's avatar image. Requires
	// laelia.agents.edit on the agent; the caller must be the agent's creator or a
	// workspace admin. Bytes travel over Connect-JSON.
	UploadAgentAvatar(context.Context, *connect.Request[v1.UploadAgentAvatarRequest]) (*connect.Response[v1.Agent], error)
	// DownloadAgentAvatar fetches an agent's avatar image bytes. Any authenticated
	// user may download any agent's avatar (workspace-internal profile image).
	DownloadAgentAvatar(context.Context, *connect.Request[v1.DownloadAgentAvatarRequest]) (*connect.Response[v1.DownloadAgentAvatarResponse], error)
	// DeleteAgentAvatar clears an agent's avatar, reverting to the pixel default.
	// Requires laelia.agents.edit on the agent.
	DeleteAgentAvatar(context.Context, *connect.Request[v1.DeleteAgentAvatarRequest]) (*connect.Response[v1.Agent], error)
	// Health check (no auth required)
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
}

// NewAgentServiceClient constructs a client for the laelia.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.CreateAgentResponse](
			httpClient,
			baseURL+AgentServiceCreateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceGetAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[v1.UpdateAgentRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceUpdateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		transferAgentOwnership: connect.NewClient[v1.TransferAgentOwnershipRequest, v1.TransferAgentOwnershipResponse](
			httpClient,
			baseURL+AgentServiceTransferAgentOwnershipProcedure,
			connect.WithSchema(agentServiceMethods.ByName("TransferAgentOwnership")),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v1.DeleteAgentRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceDeleteAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
			connect.WithClientOptions(opts...),
		),
		stopAgent: connect.NewClient[v1.StopAgentRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceStopAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StopAgent")),
			connect.WithClientOptions(opts...),
		),
		startAgent: connect.NewClient[v1.StartAgentRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceStartAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StartAgent")),
			connect.WithClientOptions(opts...),
		),
		rotateAgentToken: connect.NewClient[v1.RotateAgentTokenRequest, v1.RotateAgentTokenResponse](
			httpClient,
			baseURL+AgentServiceRotateAgentTokenProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RotateAgentToken")),
			connect.WithClientOptions(opts...),
		),
		revokeAgentToken: connect.NewClient[v1.RevokeAgentTokenRequest, v1.RevokeAgentTokenResponse](
			httpClient,
			baseURL+AgentServiceRevokeAgentTokenProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RevokeAgentToken")),
			connect.WithClientOptions(opts...),
		),
		forceDisconnectAgent: connect.NewClient[v1.ForceDisconnectAgentRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceForceDisconnectAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ForceDisconnectAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgentSessions: connect.NewClient[v1.ListAgentSessionsRequest, v1.ListAgentSessionsResponse](
			httpClient,
			baseURL+AgentServiceListAgentSessionsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgentSessions")),
			connect.WithClientOptions(opts...),
		),
		updateAgentACPConfig: connect.NewClient[v1.UpdateAgentACPConfigRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceUpdateAgentACPConfigProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateAgentACPConfig")),
			connect.WithClientOptions(opts...),
		),
		updateAgentMcpConfig: connect.NewClient[v1.UpdateAgentMcpConfigRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceUpdateAgentMcpConfigProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateAgentMcpConfig")),
			connect.WithClientOptions(opts...),
		),
		refreshAgentProviders: connect.NewClient[v1.RefreshAgentProvidersRequest, v1.RefreshAgentProvidersResponse](
			httpClient,
			baseURL+AgentServiceRefreshAgentProvidersProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RefreshAgentProviders")),
			connect.WithClientOptions(opts...),
		),
		listAgentWorkspace: connect.NewClient[v1.ListAgentWorkspaceRequest, v1.ListAgentWorkspaceResponse](
			httpClient,
			baseURL+AgentServiceListAgentWorkspaceProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgentWorkspace")),
			connect.WithClientOptions(opts...),
		),
		readAgentWorkspaceFile: connect.NewClient[v1.ReadAgentWorkspaceFileRequest, v1.ReadAgentWorkspaceFileResponse](
			httpClient,
			baseURL+AgentServiceReadAgentWorkspaceFileProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ReadAgentWorkspaceFile")),
			connect.WithClientOptions(opts...),
		),
		listPiModels: connect.NewClient[v1.ListPiModelsRequest, v1.ListPiModelsResponse](
			httpClient,
			baseURL+AgentServiceListPiModelsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListPiModels")),
			connect.WithClientOptions(opts...),
		),
		connectAgent: connect.NewClient[v1.ConnectAgentRequest, v1.ConnectAgentResponse](
			httpClient,
			baseURL+AgentServiceConnectAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ConnectAgent")),
			connect.WithClientOptions(opts...),
		),
		agentHeartbeat: connect.NewClient[v1.AgentHeartbeatRequest, v1.AgentHeartbeatResponse](
			httpClient,
			baseURL+AgentServiceAgentHeartbeatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("AgentHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		agentDisconnect: connect.NewClient[v1.AgentDisconnectRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceAgentDisconnectProcedure,
			connect.WithSchema(agentServiceMethods.ByName("AgentDisconnect")),
			connect.WithClientOptions(opts...),
		),
		refreshAgentToken: connect.NewClient[v1.RefreshAgentTokenRequest, v1.RefreshAgentTokenResponse](
			httpClient,
			baseURL+AgentServiceRefreshAgentTokenProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RefreshAgentToken")),
			connect.WithClientOptions(opts...),
		),
		uploadAgentAvatar: connect.NewClient[v1.UploadAgentAvatarRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceUploadAgentAvatarProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UploadAgentAvatar")),
			connect.WithClientOptions(opts...),
		),
		downloadAgentAvatar: connect.NewClient[v1.DownloadAgentAvatarRequest, v1.DownloadAgentAvatarResponse](
			httpClient,
			baseURL+AgentServiceDownloadAgentAvatarProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DownloadAgentAvatar")),
			connect.WithClientOptions(opts...),
		),
		deleteAgentAvatar: connect.NewClient[v1.DeleteAgentAvatarRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceDeleteAgentAvatarProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteAgentAvatar")),
			connect.WithClientOptions(opts...),
		),
		hello: connect.NewClient[v1.HelloRequest, v1.HelloResponse](
			httpClient,
			baseURL+AgentServiceHelloProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	createAgent            *connect.Client[v1.CreateAgentRequest, v1.CreateAgentResponse]
	listAgents             *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	getAgent               *connect.Client[v1.GetAgentRequest, v1.Agent]
	updateAgent            *connect.Client[v1.UpdateAgentRequest, v1.Agent]
	transferAgentOwnership *connect.Client[v1.TransferAgentOwnershipRequest, v1.TransferAgentOwnershipResponse]
	deleteAgent            *connect.Client[v1.DeleteAgentRequest, emptypb.Empty]
	stopAgent              *connect.Client[v1.StopAgentRequest, emptypb.Empty]
	startAgent             *connect.Client[v1.StartAgentRequest, emptypb.Empty]
	rotateAgentToken       *connect.Client[v1.RotateAgentTokenRequest, v1.RotateAgentTokenResponse]
	revokeAgentToken       *connect.Client[v1.RevokeAgentTokenRequest, v1.RevokeAgentTokenResponse]
	forceDisconnectAgent   *connect.Client[v1.ForceDisconnectAgentRequest, emptypb.Empty]
	listAgentSessions      *connect.Client[v1.ListAgentSessionsRequest, v1.ListAgentSessionsResponse]
	updateAgentACPConfig   *connect.Client[v1.UpdateAgentACPConfigRequest, emptypb.Empty]
	updateAgentMcpConfig   *connect.Client[v1.UpdateAgentMcpConfigRequest, emptypb.Empty]
	refreshAgentProviders  *connect.Client[v1.RefreshAgentProvidersRequest, v1.RefreshAgentProvidersResponse]
	listAgentWorkspace     *connect.Client[v1.ListAgentWorkspaceRequest, v1.ListAgentWorkspaceResponse]
	readAgentWorkspaceFile *connect.Client[v1.ReadAgentWorkspaceFileRequest, v1.ReadAgentWorkspaceFileResponse]
	listPiModels           *connect.Client[v1.ListPiModelsRequest, v1.ListPiModelsResponse]
	connectAgent           *connect.Client[v1.ConnectAgentRequest, v1.ConnectAgentResponse]
	agentHeartbeat         *connect.Client[v1.AgentHeartbeatRequest, v1.AgentHeartbeatResponse]
	agentDisconnect        *connect.Client[v1.AgentDisconnectRequest, emptypb.Empty]
	refreshAgentToken      *connect.Client[v1.RefreshAgentTokenRequest, v1.RefreshAgentTokenResponse]
	uploadAgentAvatar      *connect.Client[v1.UploadAgentAvatarRequest, v1.Agent]
	downloadAgentAvatar    *connect.Client[v1.DownloadAgentAvatarRequest, v1.DownloadAgentAvatarResponse]
	deleteAgentAvatar      *connect.Client[v1.DeleteAgentAvatarRequest, v1.Agent]
	hello                  *connect.Client[v1.HelloRequest, v1.HelloResponse]
}

// CreateAgent calls laelia.v1.AgentService.CreateAgent.
func (c *agentServiceClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// ListAgents calls laelia.v1.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// GetAgent calls laelia.v1.AgentService.GetAgent.
func (c *agentServiceClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// UpdateAgent calls laelia.v1.AgentService.UpdateAgent.
func (c *agentServiceClient) UpdateAgent(ctx context.Context, req *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// TransferAgentOwnership calls laelia.v1.AgentService.TransferAgentOwnership.
func (c *agentServiceClient) TransferAgentOwnership(ctx context.Context, req *connect.Request[v1.TransferAgentOwnershipRequest]) (*connect.Response[v1.TransferAgentOwnershipResponse], error) {
	return c.transferAgentOwnership.CallUnary(ctx, req)
}

// DeleteAgent calls laelia.v1.AgentService.DeleteAgent.
func (c *agentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// StopAgent calls laelia.v1.AgentService.StopAgent.
func (c *agentServiceClient) StopAgent(ctx context.Context, req *connect.Request[v1.StopAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.stopAgent.CallUnary(ctx, req)
}

// StartAgent calls laelia.v1.AgentService.StartAgent.
func (c *agentServiceClient) StartAgent(ctx context.Context, req *connect.Request[v1.StartAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.startAgent.CallUnary(ctx, req)
}

// RotateAgentToken calls laelia.v1.AgentService.RotateAgentToken.
func (c *agentServiceClient) RotateAgentToken(ctx context.Context, req *connect.Request[v1.RotateAgentTokenRequest]) (*connect.Response[v1.RotateAgentTokenResponse], error) {
	return c.rotateAgentToken.CallUnary(ctx, req)
}

// RevokeAgentToken calls laelia.v1.AgentService.RevokeAgentToken.
func (c *agentServiceClient) RevokeAgentToken(ctx context.Context, req *connect.Request[v1.RevokeAgentTokenRequest]) (*connect.Response[v1.RevokeAgentTokenResponse], error) {
	return c.revokeAgentToken.CallUnary(ctx, req)
}

// ForceDisconnectAgent calls laelia.v1.AgentService.ForceDisconnectAgent.
func (c *agentServiceClient) ForceDisconnectAgent(ctx context.Context, req *connect.Request[v1.ForceDisconnectAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.forceDisconnectAgent.CallUnary(ctx, req)
}

// ListAgentSessions calls laelia.v1.AgentService.ListAgentSessions.
func (c *agentServiceClient) ListAgentSessions(ctx context.Context, req *connect.Request[v1.ListAgentSessionsRequest]) (*connect.Response[v1.ListAgentSessionsResponse], error) {
	return c.listAgentSessions.CallUnary(ctx, req)
}

// UpdateAgentACPConfig calls laelia.v1.AgentService.UpdateAgentACPConfig.
func (c *agentServiceClient) UpdateAgentACPConfig(ctx context.Context, req *connect.Request[v1.UpdateAgentACPConfigRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateAgentACPConfig.CallUnary(ctx, req)
}

// UpdateAgentMcpConfig calls laelia.v1.AgentService.UpdateAgentMcpConfig.
func (c *agentServiceClient) UpdateAgentMcpConfig(ctx context.Context, req *connect.Request[v1.UpdateAgentMcpConfigRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateAgentMcpConfig.CallUnary(ctx, req)
}

// RefreshAgentProviders calls laelia.v1.AgentService.RefreshAgentProviders.
func (c *agentServiceClient) RefreshAgentProviders(ctx context.Context, req *connect.Request[v1.RefreshAgentProvidersRequest]) (*connect.Response[v1.RefreshAgentProvidersResponse], error) {
	return c.refreshAgentProviders.CallUnary(ctx, req)
}

// ListAgentWorkspace calls laelia.v1.AgentService.ListAgentWorkspace.
func (c *agentServiceClient) ListAgentWorkspace(ctx context.Context, req *connect.Request[v1.ListAgentWorkspaceRequest]) (*connect.Response[v1.ListAgentWorkspaceResponse], error) {
	return c.listAgentWorkspace.CallUnary(ctx, req)
}

// ReadAgentWorkspaceFile calls laelia.v1.AgentService.ReadAgentWorkspaceFile.
func (c *agentServiceClient) ReadAgentWorkspaceFile(ctx context.Context, req *connect.Request[v1.ReadAgentWorkspaceFileRequest]) (*connect.Response[v1.ReadAgentWorkspaceFileResponse], error) {
	return c.readAgentWorkspaceFile.CallUnary(ctx, req)
}

// ListPiModels calls laelia.v1.AgentService.ListPiModels.
func (c *agentServiceClient) ListPiModels(ctx context.Context, req *connect.Request[v1.ListPiModelsRequest]) (*connect.Response[v1.ListPiModelsResponse], error) {
	return c.listPiModels.CallUnary(ctx, req)
}

// ConnectAgent calls laelia.v1.AgentService.ConnectAgent.
func (c *agentServiceClient) ConnectAgent(ctx context.Context, req *connect.Request[v1.ConnectAgentRequest]) (*connect.Response[v1.ConnectAgentResponse], error) {
	return c.connectAgent.CallUnary(ctx, req)
}

// AgentHeartbeat calls laelia.v1.AgentService.AgentHeartbeat.
func (c *agentServiceClient) AgentHeartbeat(ctx context.Context, req *connect.Request[v1.AgentHeartbeatRequest]) (*connect.Response[v1.AgentHeartbeatResponse], error) {
	return c.agentHeartbeat.CallUnary(ctx, req)
}

// AgentDisconnect calls laelia.v1.AgentService.AgentDisconnect.
func (c *agentServiceClient) AgentDisconnect(ctx context.Context, req *connect.Request[v1.AgentDisconnectRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.agentDisconnect.CallUnary(ctx, req)
}

// RefreshAgentToken calls laelia.v1.AgentService.RefreshAgentToken.
func (c *agentServiceClient) RefreshAgentToken(ctx context.Context, req *connect.Request[v1.RefreshAgentTokenRequest]) (*connect.Response[v1.RefreshAgentTokenResponse], error) {
	return c.refreshAgentToken.CallUnary(ctx, req)
}

// UploadAgentAvatar calls laelia.v1.AgentService.UploadAgentAvatar.
func (c *agentServiceClient) UploadAgentAvatar(ctx context.Context, req *connect.Request[v1.UploadAgentAvatarRequest]) (*connect.Response[v1.Agent], error) {
	return c.uploadAgentAvatar.CallUnary(ctx, req)
}

// DownloadAgentAvatar calls laelia.v1.AgentService.DownloadAgentAvatar.
func (c *agentServiceClient) DownloadAgentAvatar(ctx context.Context, req *connect.Request[v1.DownloadAgentAvatarRequest]) (*connect.Response[v1.DownloadAgentAvatarResponse], error) {
	return c.downloadAgentAvatar.CallUnary(ctx, req)
}

// DeleteAgentAvatar calls laelia.v1.AgentService.DeleteAgentAvatar.
func (c *agentServiceClient) DeleteAgentAvatar(ctx context.Context, req *connect.Request[v1.DeleteAgentAvatarRequest]) (*connect.Response[v1.Agent], error) {
	return c.deleteAgentAvatar.CallUnary(ctx, req)
}

// Hello calls laelia.v1.AgentService.Hello.
func (c *agentServiceClient) Hello(ctx context.Context, req *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the laelia.v1.AgentService service.
type AgentServiceHandler interface {
	// CreateAgent is handler-gated (no permission annotation): the machine's
	// creator, a workspace admin, or a principal bound to
	// roles/machineAgentCreator on the machine's IAM policy may create agents on
	// it. The machine-scoped check is enforced by the handler via
	// laelia.machines.createAgent against the machine's IAM policy.
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	// UpdateAgent patches a single mutable agent field. Only allow_add_to_channel
	// is supported initially (any other update_mask path is rejected). Authorized
	// in the handler for the agent's owner or a workspace admin; the IAM
	// interceptor's agents.edit is admin-only, so this RPC carries no permission
	// annotation and is handler-gated.
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error)
	// TransferAgentOwnership reassigns the agent's owner to another user. The new
	// owner takes effect immediately and unilaterally (no acceptance required);
	// the previous owner loses owner authority at once. Authorized in the handler
	// for the agent's current owner or a workspace admin; like UpdateAgent this
	// RPC carries no permission annotation (agents.edit is admin-only) and is
	// handler-gated via canEditAgent.
	TransferAgentOwnership(context.Context, *connect.Request[v1.TransferAgentOwnershipRequest]) (*connect.Response[v1.TransferAgentOwnershipResponse], error)
	// DeleteAgent soft-deletes an agent. Authorized in the handler for the
	// agent's owner or a holder of laelia.agents.edit on the agent; no
	// permission annotation so the owner short-circuit can run.
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// StopAgent stops an agent: its machine runner is torn down and it no
	// longer processes session messages or runs an LLM agent until StartAgent.
	// The agent row is preserved (not deleted) and remains visible. Authorized
	// in the handler for the agent's owner or a holder of laelia.agents.edit.
	StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// StartAgent resumes a stopped agent: its machine runner is re-spawned and
	// it resumes processing session messages. No-op (still succeeds) if the
	// agent is already enabled. Authorized in the handler for the agent's owner
	// or a holder of laelia.agents.edit.
	StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// Token rotation: generate a new bootstrap token, old token invalid after
	// grace period. Authorized in the handler for the agent's owner or a holder
	// of laelia.agents.edit on the agent; no permission annotation so the owner
	// short-circuit can run.
	RotateAgentToken(context.Context, *connect.Request[v1.RotateAgentTokenRequest]) (*connect.Response[v1.RotateAgentTokenResponse], error)
	// Token revocation: revoke all tokens for the agent. Authorized in the
	// handler for the agent's owner or a holder of laelia.agents.edit on the
	// agent; no permission annotation so the owner short-circuit can run.
	RevokeAgentToken(context.Context, *connect.Request[v1.RevokeAgentTokenRequest]) (*connect.Response[v1.RevokeAgentTokenResponse], error)
	// Force-disconnects an agent connection. Authorized in the handler for the
	// agent's owner or a holder of laelia.agents.edit on the agent; no
	// permission annotation so the owner short-circuit can run.
	ForceDisconnectAgent(context.Context, *connect.Request[v1.ForceDisconnectAgentRequest]) (*connect.Response[emptypb.Empty], error)
	// List agent sessions
	ListAgentSessions(context.Context, *connect.Request[v1.ListAgentSessionsRequest]) (*connect.Response[v1.ListAgentSessionsResponse], error)
	// Update the agent's ACP config. Handler-gated (no permission annotation):
	// the agent's owner or a workspace admin may update it. Setting a legacy
	// inline api_provider/api_key additionally requires laelia.agents.edit (only
	// workspace admin today); owners without it must use a global provider.
	UpdateAgentACPConfig(context.Context, *connect.Request[v1.UpdateAgentACPConfigRequest]) (*connect.Response[emptypb.Empty], error)
	// UpdateAgentMcpConfig replaces the MCP servers enabled on an agent. Only
	// servers the caller may use (members of the server's user/group list, or
	// workspace admin) are accepted. Handler-gated like UpdateAgentACPConfig:
	// the agent's owner or a workspace admin may update it.
	UpdateAgentMcpConfig(context.Context, *connect.Request[v1.UpdateAgentMcpConfigRequest]) (*connect.Response[emptypb.Empty], error)
	// Ask the agent daemon to re-probe its host for installed LLM agent
	// providers and their models. Returns the freshly discovered provider list
	// (also persisted into agent.info.available_providers). Authorized in the
	// handler for the agent's owner or a holder of laelia.agents.edit on the
	// agent; no permission annotation so the owner short-circuit can run.
	RefreshAgentProviders(context.Context, *connect.Request[v1.RefreshAgentProvidersRequest]) (*connect.Response[v1.RefreshAgentProvidersResponse], error)
	// ListAgentWorkspace lists one directory level of an agent's workspace on its
	// machine (~/.laelia/<machineID>/<agentID>/), lazily loading the tree level by
	// level. Workspace content is sensitive: authorized in the handler for the
	// agent's owner or a workspace admin (canEditAgent); like UpdateAgent this
	// RPC carries no permission annotation (agents.edit is admin-only) and is
	// handler-gated.
	ListAgentWorkspace(context.Context, *connect.Request[v1.ListAgentWorkspaceRequest]) (*connect.Response[v1.ListAgentWorkspaceResponse], error)
	// ReadAgentWorkspaceFile reads a single workspace file for text/image preview.
	// Same handler-gated authorization as ListAgentWorkspace (owner or workspace
	// admin). Sensitive files (secret/credential/token patterns) are rejected by
	// the machine app and surface as a per-file error, not a transport error.
	ReadAgentWorkspaceFile(context.Context, *connect.Request[v1.ReadAgentWorkspaceFileRequest]) (*connect.Response[v1.ReadAgentWorkspaceFileResponse], error)
	// List the models a built-in pi agent's LLM API provider exposes. The manager
	// proxies the provider's model-listing HTTP API (DeepSeek `GET /models` with
	// the caller's api_key; OpenRouter `GET /models`, public) so the model list is
	// fetched dynamically rather than hardcoded. Not agent-scoped: the add-agent
	// form calls it before the agent exists. Admin (agents.edit) only.
	ListPiModels(context.Context, *connect.Request[v1.ListPiModelsRequest]) (*connect.Response[v1.ListPiModelsResponse], error)
	// Agent initial connection using bootstrap token
	ConnectAgent(context.Context, *connect.Request[v1.ConnectAgentRequest]) (*connect.Response[v1.ConnectAgentResponse], error)
	// Agent heartbeat
	AgentHeartbeat(context.Context, *connect.Request[v1.AgentHeartbeatRequest]) (*connect.Response[v1.AgentHeartbeatResponse], error)
	// Agent graceful disconnect
	AgentDisconnect(context.Context, *connect.Request[v1.AgentDisconnectRequest]) (*connect.Response[emptypb.Empty], error)
	// Agent refreshes access token
	RefreshAgentToken(context.Context, *connect.Request[v1.RefreshAgentTokenRequest]) (*connect.Response[v1.RefreshAgentTokenResponse], error)
	// UploadAgentAvatar replaces an agent's avatar image. Requires
	// laelia.agents.edit on the agent; the caller must be the agent's creator or a
	// workspace admin. Bytes travel over Connect-JSON.
	UploadAgentAvatar(context.Context, *connect.Request[v1.UploadAgentAvatarRequest]) (*connect.Response[v1.Agent], error)
	// DownloadAgentAvatar fetches an agent's avatar image bytes. Any authenticated
	// user may download any agent's avatar (workspace-internal profile image).
	DownloadAgentAvatar(context.Context, *connect.Request[v1.DownloadAgentAvatarRequest]) (*connect.Response[v1.DownloadAgentAvatarResponse], error)
	// DeleteAgentAvatar clears an agent's avatar, reverting to the pixel default.
	// Requires laelia.agents.edit on the agent.
	DeleteAgentAvatar(context.Context, *connect.Request[v1.DeleteAgentAvatarRequest]) (*connect.Response[v1.Agent], error)
	// Health check (no auth required)
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceCreateAgentHandler := connect.NewUnaryHandler(
		AgentServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceTransferAgentOwnershipHandler := connect.NewUnaryHandler(
		AgentServiceTransferAgentOwnershipProcedure,
		svc.TransferAgentOwnership,
		connect.WithSchema(agentServiceMethods.ByName("TransferAgentOwnership")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStopAgentHandler := connect.NewUnaryHandler(
		AgentServiceStopAgentProcedure,
		svc.StopAgent,
		connect.WithSchema(agentServiceMethods.ByName("StopAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStartAgentHandler := connect.NewUnaryHandler(
		AgentServiceStartAgentProcedure,
		svc.StartAgent,
		connect.WithSchema(agentServiceMethods.ByName("StartAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRotateAgentTokenHandler := connect.NewUnaryHandler(
		AgentServiceRotateAgentTokenProcedure,
		svc.RotateAgentToken,
		connect.WithSchema(agentServiceMethods.ByName("RotateAgentToken")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRevokeAgentTokenHandler := connect.NewUnaryHandler(
		AgentServiceRevokeAgentTokenProcedure,
		svc.RevokeAgentToken,
		connect.WithSchema(agentServiceMethods.ByName("RevokeAgentToken")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceForceDisconnectAgentHandler := connect.NewUnaryHandler(
		AgentServiceForceDisconnectAgentProcedure,
		svc.ForceDisconnectAgent,
		connect.WithSchema(agentServiceMethods.ByName("ForceDisconnectAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentSessionsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentSessionsProcedure,
		svc.ListAgentSessions,
		connect.WithSchema(agentServiceMethods.ByName("ListAgentSessions")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentACPConfigHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentACPConfigProcedure,
		svc.UpdateAgentACPConfig,
		connect.WithSchema(agentServiceMethods.ByName("UpdateAgentACPConfig")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentMcpConfigHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentMcpConfigProcedure,
		svc.UpdateAgentMcpConfig,
		connect.WithSchema(agentServiceMethods.ByName("UpdateAgentMcpConfig")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRefreshAgentProvidersHandler := connect.NewUnaryHandler(
		AgentServiceRefreshAgentProvidersProcedure,
		svc.RefreshAgentProviders,
		connect.WithSchema(agentServiceMethods.ByName("RefreshAgentProviders")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentWorkspaceHandler := connect.NewUnaryHandler(
		AgentServiceListAgentWorkspaceProcedure,
		svc.ListAgentWorkspace,
		connect.WithSchema(agentServiceMethods.ByName("ListAgentWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceReadAgentWorkspaceFileHandler := connect.NewUnaryHandler(
		AgentServiceReadAgentWorkspaceFileProcedure,
		svc.ReadAgentWorkspaceFile,
		connect.WithSchema(agentServiceMethods.ByName("ReadAgentWorkspaceFile")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListPiModelsHandler := connect.NewUnaryHandler(
		AgentServiceListPiModelsProcedure,
		svc.ListPiModels,
		connect.WithSchema(agentServiceMethods.ByName("ListPiModels")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceConnectAgentHandler := connect.NewUnaryHandler(
		AgentServiceConnectAgentProcedure,
		svc.ConnectAgent,
		connect.WithSchema(agentServiceMethods.ByName("ConnectAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceAgentHeartbeatHandler := connect.NewUnaryHandler(
		AgentServiceAgentHeartbeatProcedure,
		svc.AgentHeartbeat,
		connect.WithSchema(agentServiceMethods.ByName("AgentHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceAgentDisconnectHandler := connect.NewUnaryHandler(
		AgentServiceAgentDisconnectProcedure,
		svc.AgentDisconnect,
		connect.WithSchema(agentServiceMethods.ByName("AgentDisconnect")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRefreshAgentTokenHandler := connect.NewUnaryHandler(
		AgentServiceRefreshAgentTokenProcedure,
		svc.RefreshAgentToken,
		connect.WithSchema(agentServiceMethods.ByName("RefreshAgentToken")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUploadAgentAvatarHandler := connect.NewUnaryHandler(
		AgentServiceUploadAgentAvatarProcedure,
		svc.UploadAgentAvatar,
		connect.WithSchema(agentServiceMethods.ByName("UploadAgentAvatar")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDownloadAgentAvatarHandler := connect.NewUnaryHandler(
		AgentServiceDownloadAgentAvatarProcedure,
		svc.DownloadAgentAvatar,
		connect.WithSchema(agentServiceMethods.ByName("DownloadAgentAvatar")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentAvatarHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentAvatarProcedure,
		svc.DeleteAgentAvatar,
		connect.WithSchema(agentServiceMethods.ByName("DeleteAgentAvatar")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceHelloHandler := connect.NewUnaryHandler(
		AgentServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(agentServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	return "/laelia.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceCreateAgentProcedure:
			agentServiceCreateAgentHandler.ServeHTTP(w, r)
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentProcedure:
			agentServiceGetAgentHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentProcedure:
			agentServiceUpdateAgentHandler.ServeHTTP(w, r)
		case AgentServiceTransferAgentOwnershipProcedure:
			agentServiceTransferAgentOwnershipHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentProcedure:
			agentServiceDeleteAgentHandler.ServeHTTP(w, r)
		case AgentServiceStopAgentProcedure:
			agentServiceStopAgentHandler.ServeHTTP(w, r)
		case AgentServiceStartAgentProcedure:
			agentServiceStartAgentHandler.ServeHTTP(w, r)
		case AgentServiceRotateAgentTokenProcedure:
			agentServiceRotateAgentTokenHandler.ServeHTTP(w, r)
		case AgentServiceRevokeAgentTokenProcedure:
			agentServiceRevokeAgentTokenHandler.ServeHTTP(w, r)
		case AgentServiceForceDisconnectAgentProcedure:
			agentServiceForceDisconnectAgentHandler.ServeHTTP(w, r)
		case AgentServiceListAgentSessionsProcedure:
			agentServiceListAgentSessionsHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentACPConfigProcedure:
			agentServiceUpdateAgentACPConfigHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentMcpConfigProcedure:
			agentServiceUpdateAgentMcpConfigHandler.ServeHTTP(w, r)
		case AgentServiceRefreshAgentProvidersProcedure:
			agentServiceRefreshAgentProvidersHandler.ServeHTTP(w, r)
		case AgentServiceListAgentWorkspaceProcedure:
			agentServiceListAgentWorkspaceHandler.ServeHTTP(w, r)
		case AgentServiceReadAgentWorkspaceFileProcedure:
			agentServiceReadAgentWorkspaceFileHandler.ServeHTTP(w, r)
		case AgentServiceListPiModelsProcedure:
			agentServiceListPiModelsHandler.ServeHTTP(w, r)
		case AgentServiceConnectAgentProcedure:
			agentServiceConnectAgentHandler.ServeHTTP(w, r)
		case AgentServiceAgentHeartbeatProcedure:
			agentServiceAgentHeartbeatHandler.ServeHTTP(w, r)
		case AgentServiceAgentDisconnectProcedure:
			agentServiceAgentDisconnectHandler.ServeHTTP(w, r)
		case AgentServiceRefreshAgentTokenProcedure:
			agentServiceRefreshAgentTokenHandler.ServeHTTP(w, r)
		case AgentServiceUploadAgentAvatarProcedure:
			agentServiceUploadAgentAvatarHandler.ServeHTTP(w, r)
		case AgentServiceDownloadAgentAvatarProcedure:
			agentServiceDownloadAgentAvatarHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentAvatarProcedure:
			agentServiceDeleteAgentAvatarHandler.ServeHTTP(w, r)
		case AgentServiceHelloProcedure:
			agentServiceHelloHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.CreateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.GetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.UpdateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) TransferAgentOwnership(context.Context, *connect.Request[v1.TransferAgentOwnershipRequest]) (*connect.Response[v1.TransferAgentOwnershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.TransferAgentOwnership is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.DeleteAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) StopAgent(context.Context, *connect.Request[v1.StopAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.StopAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) StartAgent(context.Context, *connect.Request[v1.StartAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.StartAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) RotateAgentToken(context.Context, *connect.Request[v1.RotateAgentTokenRequest]) (*connect.Response[v1.RotateAgentTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.RotateAgentToken is not implemented"))
}

func (UnimplementedAgentServiceHandler) RevokeAgentToken(context.Context, *connect.Request[v1.RevokeAgentTokenRequest]) (*connect.Response[v1.RevokeAgentTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.RevokeAgentToken is not implemented"))
}

func (UnimplementedAgentServiceHandler) ForceDisconnectAgent(context.Context, *connect.Request[v1.ForceDisconnectAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ForceDisconnectAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgentSessions(context.Context, *connect.Request[v1.ListAgentSessionsRequest]) (*connect.Response[v1.ListAgentSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ListAgentSessions is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgentACPConfig(context.Context, *connect.Request[v1.UpdateAgentACPConfigRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.UpdateAgentACPConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgentMcpConfig(context.Context, *connect.Request[v1.UpdateAgentMcpConfigRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.UpdateAgentMcpConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) RefreshAgentProviders(context.Context, *connect.Request[v1.RefreshAgentProvidersRequest]) (*connect.Response[v1.RefreshAgentProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.RefreshAgentProviders is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgentWorkspace(context.Context, *connect.Request[v1.ListAgentWorkspaceRequest]) (*connect.Response[v1.ListAgentWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ListAgentWorkspace is not implemented"))
}

func (UnimplementedAgentServiceHandler) ReadAgentWorkspaceFile(context.Context, *connect.Request[v1.ReadAgentWorkspaceFileRequest]) (*connect.Response[v1.ReadAgentWorkspaceFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ReadAgentWorkspaceFile is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListPiModels(context.Context, *connect.Request[v1.ListPiModelsRequest]) (*connect.Response[v1.ListPiModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ListPiModels is not implemented"))
}

func (UnimplementedAgentServiceHandler) ConnectAgent(context.Context, *connect.Request[v1.ConnectAgentRequest]) (*connect.Response[v1.ConnectAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.ConnectAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) AgentHeartbeat(context.Context, *connect.Request[v1.AgentHeartbeatRequest]) (*connect.Response[v1.AgentHeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.AgentHeartbeat is not implemented"))
}

func (UnimplementedAgentServiceHandler) AgentDisconnect(context.Context, *connect.Request[v1.AgentDisconnectRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.AgentDisconnect is not implemented"))
}

func (UnimplementedAgentServiceHandler) RefreshAgentToken(context.Context, *connect.Request[v1.RefreshAgentTokenRequest]) (*connect.Response[v1.RefreshAgentTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.RefreshAgentToken is not implemented"))
}

func (UnimplementedAgentServiceHandler) UploadAgentAvatar(context.Context, *connect.Request[v1.UploadAgentAvatarRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.UploadAgentAvatar is not implemented"))
}

func (UnimplementedAgentServiceHandler) DownloadAgentAvatar(context.Context, *connect.Request[v1.DownloadAgentAvatarRequest]) (*connect.Response[v1.DownloadAgentAvatarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.DownloadAgentAvatar is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgentAvatar(context.Context, *connect.Request[v1.DeleteAgentAvatarRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.DeleteAgentAvatar is not implemented"))
}

func (UnimplementedAgentServiceHandler) Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentService.Hello is not implemented"))
}
