// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/api_provider_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tbdavid2019/888a2a/backend/generated-go/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApiProviderServiceName is the fully-qualified name of the ApiProviderService service.
	ApiProviderServiceName = "laelia.v1.ApiProviderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApiProviderServiceGetAPIProviderProcedure is the fully-qualified name of the ApiProviderService's
	// GetAPIProvider RPC.
	ApiProviderServiceGetAPIProviderProcedure = "/laelia.v1.ApiProviderService/GetAPIProvider"
	// ApiProviderServiceListAPIProvidersProcedure is the fully-qualified name of the
	// ApiProviderService's ListAPIProviders RPC.
	ApiProviderServiceListAPIProvidersProcedure = "/laelia.v1.ApiProviderService/ListAPIProviders"
	// ApiProviderServiceCreateAPIProviderProcedure is the fully-qualified name of the
	// ApiProviderService's CreateAPIProvider RPC.
	ApiProviderServiceCreateAPIProviderProcedure = "/laelia.v1.ApiProviderService/CreateAPIProvider"
	// ApiProviderServiceUpdateAPIProviderProcedure is the fully-qualified name of the
	// ApiProviderService's UpdateAPIProvider RPC.
	ApiProviderServiceUpdateAPIProviderProcedure = "/laelia.v1.ApiProviderService/UpdateAPIProvider"
	// ApiProviderServiceDeleteAPIProviderProcedure is the fully-qualified name of the
	// ApiProviderService's DeleteAPIProvider RPC.
	ApiProviderServiceDeleteAPIProviderProcedure = "/laelia.v1.ApiProviderService/DeleteAPIProvider"
	// ApiProviderServiceListAPIProviderModelsProcedure is the fully-qualified name of the
	// ApiProviderService's ListAPIProviderModels RPC.
	ApiProviderServiceListAPIProviderModelsProcedure = "/laelia.v1.ApiProviderService/ListAPIProviderModels"
)

// ApiProviderServiceClient is a client for the laelia.v1.ApiProviderService service.
type ApiProviderServiceClient interface {
	GetAPIProvider(context.Context, *connect.Request[v1.GetApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	ListAPIProviders(context.Context, *connect.Request[v1.ListApiProvidersRequest]) (*connect.Response[v1.ListApiProvidersResponse], error)
	CreateAPIProvider(context.Context, *connect.Request[v1.CreateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	UpdateAPIProvider(context.Context, *connect.Request[v1.UpdateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	DeleteAPIProvider(context.Context, *connect.Request[v1.DeleteApiProviderRequest]) (*connect.Response[emptypb.Empty], error)
	// List the models a provider type exposes. The manager proxies the provider's
	// model-listing HTTP API (DeepSeek GET /models with the caller's api_key;
	// OpenRouter GET /models, public). Admin (laelia.apiProviders.update) only.
	ListAPIProviderModels(context.Context, *connect.Request[v1.ListApiProviderModelsRequest]) (*connect.Response[v1.ListApiProviderModelsResponse], error)
}

// NewApiProviderServiceClient constructs a client for the laelia.v1.ApiProviderService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApiProviderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApiProviderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	apiProviderServiceMethods := v1.File_v1_api_provider_service_proto.Services().ByName("ApiProviderService").Methods()
	return &apiProviderServiceClient{
		getAPIProvider: connect.NewClient[v1.GetApiProviderRequest, v1.ApiProvider](
			httpClient,
			baseURL+ApiProviderServiceGetAPIProviderProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("GetAPIProvider")),
			connect.WithClientOptions(opts...),
		),
		listAPIProviders: connect.NewClient[v1.ListApiProvidersRequest, v1.ListApiProvidersResponse](
			httpClient,
			baseURL+ApiProviderServiceListAPIProvidersProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("ListAPIProviders")),
			connect.WithClientOptions(opts...),
		),
		createAPIProvider: connect.NewClient[v1.CreateApiProviderRequest, v1.ApiProvider](
			httpClient,
			baseURL+ApiProviderServiceCreateAPIProviderProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("CreateAPIProvider")),
			connect.WithClientOptions(opts...),
		),
		updateAPIProvider: connect.NewClient[v1.UpdateApiProviderRequest, v1.ApiProvider](
			httpClient,
			baseURL+ApiProviderServiceUpdateAPIProviderProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("UpdateAPIProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteAPIProvider: connect.NewClient[v1.DeleteApiProviderRequest, emptypb.Empty](
			httpClient,
			baseURL+ApiProviderServiceDeleteAPIProviderProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("DeleteAPIProvider")),
			connect.WithClientOptions(opts...),
		),
		listAPIProviderModels: connect.NewClient[v1.ListApiProviderModelsRequest, v1.ListApiProviderModelsResponse](
			httpClient,
			baseURL+ApiProviderServiceListAPIProviderModelsProcedure,
			connect.WithSchema(apiProviderServiceMethods.ByName("ListAPIProviderModels")),
			connect.WithClientOptions(opts...),
		),
	}
}

// apiProviderServiceClient implements ApiProviderServiceClient.
type apiProviderServiceClient struct {
	getAPIProvider        *connect.Client[v1.GetApiProviderRequest, v1.ApiProvider]
	listAPIProviders      *connect.Client[v1.ListApiProvidersRequest, v1.ListApiProvidersResponse]
	createAPIProvider     *connect.Client[v1.CreateApiProviderRequest, v1.ApiProvider]
	updateAPIProvider     *connect.Client[v1.UpdateApiProviderRequest, v1.ApiProvider]
	deleteAPIProvider     *connect.Client[v1.DeleteApiProviderRequest, emptypb.Empty]
	listAPIProviderModels *connect.Client[v1.ListApiProviderModelsRequest, v1.ListApiProviderModelsResponse]
}

// GetAPIProvider calls laelia.v1.ApiProviderService.GetAPIProvider.
func (c *apiProviderServiceClient) GetAPIProvider(ctx context.Context, req *connect.Request[v1.GetApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return c.getAPIProvider.CallUnary(ctx, req)
}

// ListAPIProviders calls laelia.v1.ApiProviderService.ListAPIProviders.
func (c *apiProviderServiceClient) ListAPIProviders(ctx context.Context, req *connect.Request[v1.ListApiProvidersRequest]) (*connect.Response[v1.ListApiProvidersResponse], error) {
	return c.listAPIProviders.CallUnary(ctx, req)
}

// CreateAPIProvider calls laelia.v1.ApiProviderService.CreateAPIProvider.
func (c *apiProviderServiceClient) CreateAPIProvider(ctx context.Context, req *connect.Request[v1.CreateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return c.createAPIProvider.CallUnary(ctx, req)
}

// UpdateAPIProvider calls laelia.v1.ApiProviderService.UpdateAPIProvider.
func (c *apiProviderServiceClient) UpdateAPIProvider(ctx context.Context, req *connect.Request[v1.UpdateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return c.updateAPIProvider.CallUnary(ctx, req)
}

// DeleteAPIProvider calls laelia.v1.ApiProviderService.DeleteAPIProvider.
func (c *apiProviderServiceClient) DeleteAPIProvider(ctx context.Context, req *connect.Request[v1.DeleteApiProviderRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAPIProvider.CallUnary(ctx, req)
}

// ListAPIProviderModels calls laelia.v1.ApiProviderService.ListAPIProviderModels.
func (c *apiProviderServiceClient) ListAPIProviderModels(ctx context.Context, req *connect.Request[v1.ListApiProviderModelsRequest]) (*connect.Response[v1.ListApiProviderModelsResponse], error) {
	return c.listAPIProviderModels.CallUnary(ctx, req)
}

// ApiProviderServiceHandler is an implementation of the laelia.v1.ApiProviderService service.
type ApiProviderServiceHandler interface {
	GetAPIProvider(context.Context, *connect.Request[v1.GetApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	ListAPIProviders(context.Context, *connect.Request[v1.ListApiProvidersRequest]) (*connect.Response[v1.ListApiProvidersResponse], error)
	CreateAPIProvider(context.Context, *connect.Request[v1.CreateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	UpdateAPIProvider(context.Context, *connect.Request[v1.UpdateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error)
	DeleteAPIProvider(context.Context, *connect.Request[v1.DeleteApiProviderRequest]) (*connect.Response[emptypb.Empty], error)
	// List the models a provider type exposes. The manager proxies the provider's
	// model-listing HTTP API (DeepSeek GET /models with the caller's api_key;
	// OpenRouter GET /models, public). Admin (laelia.apiProviders.update) only.
	ListAPIProviderModels(context.Context, *connect.Request[v1.ListApiProviderModelsRequest]) (*connect.Response[v1.ListApiProviderModelsResponse], error)
}

// NewApiProviderServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApiProviderServiceHandler(svc ApiProviderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	apiProviderServiceMethods := v1.File_v1_api_provider_service_proto.Services().ByName("ApiProviderService").Methods()
	apiProviderServiceGetAPIProviderHandler := connect.NewUnaryHandler(
		ApiProviderServiceGetAPIProviderProcedure,
		svc.GetAPIProvider,
		connect.WithSchema(apiProviderServiceMethods.ByName("GetAPIProvider")),
		connect.WithHandlerOptions(opts...),
	)
	apiProviderServiceListAPIProvidersHandler := connect.NewUnaryHandler(
		ApiProviderServiceListAPIProvidersProcedure,
		svc.ListAPIProviders,
		connect.WithSchema(apiProviderServiceMethods.ByName("ListAPIProviders")),
		connect.WithHandlerOptions(opts...),
	)
	apiProviderServiceCreateAPIProviderHandler := connect.NewUnaryHandler(
		ApiProviderServiceCreateAPIProviderProcedure,
		svc.CreateAPIProvider,
		connect.WithSchema(apiProviderServiceMethods.ByName("CreateAPIProvider")),
		connect.WithHandlerOptions(opts...),
	)
	apiProviderServiceUpdateAPIProviderHandler := connect.NewUnaryHandler(
		ApiProviderServiceUpdateAPIProviderProcedure,
		svc.UpdateAPIProvider,
		connect.WithSchema(apiProviderServiceMethods.ByName("UpdateAPIProvider")),
		connect.WithHandlerOptions(opts...),
	)
	apiProviderServiceDeleteAPIProviderHandler := connect.NewUnaryHandler(
		ApiProviderServiceDeleteAPIProviderProcedure,
		svc.DeleteAPIProvider,
		connect.WithSchema(apiProviderServiceMethods.ByName("DeleteAPIProvider")),
		connect.WithHandlerOptions(opts...),
	)
	apiProviderServiceListAPIProviderModelsHandler := connect.NewUnaryHandler(
		ApiProviderServiceListAPIProviderModelsProcedure,
		svc.ListAPIProviderModels,
		connect.WithSchema(apiProviderServiceMethods.ByName("ListAPIProviderModels")),
		connect.WithHandlerOptions(opts...),
	)
	return "/laelia.v1.ApiProviderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApiProviderServiceGetAPIProviderProcedure:
			apiProviderServiceGetAPIProviderHandler.ServeHTTP(w, r)
		case ApiProviderServiceListAPIProvidersProcedure:
			apiProviderServiceListAPIProvidersHandler.ServeHTTP(w, r)
		case ApiProviderServiceCreateAPIProviderProcedure:
			apiProviderServiceCreateAPIProviderHandler.ServeHTTP(w, r)
		case ApiProviderServiceUpdateAPIProviderProcedure:
			apiProviderServiceUpdateAPIProviderHandler.ServeHTTP(w, r)
		case ApiProviderServiceDeleteAPIProviderProcedure:
			apiProviderServiceDeleteAPIProviderHandler.ServeHTTP(w, r)
		case ApiProviderServiceListAPIProviderModelsProcedure:
			apiProviderServiceListAPIProviderModelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApiProviderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApiProviderServiceHandler struct{}

func (UnimplementedApiProviderServiceHandler) GetAPIProvider(context.Context, *connect.Request[v1.GetApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.GetAPIProvider is not implemented"))
}

func (UnimplementedApiProviderServiceHandler) ListAPIProviders(context.Context, *connect.Request[v1.ListApiProvidersRequest]) (*connect.Response[v1.ListApiProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.ListAPIProviders is not implemented"))
}

func (UnimplementedApiProviderServiceHandler) CreateAPIProvider(context.Context, *connect.Request[v1.CreateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.CreateAPIProvider is not implemented"))
}

func (UnimplementedApiProviderServiceHandler) UpdateAPIProvider(context.Context, *connect.Request[v1.UpdateApiProviderRequest]) (*connect.Response[v1.ApiProvider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.UpdateAPIProvider is not implemented"))
}

func (UnimplementedApiProviderServiceHandler) DeleteAPIProvider(context.Context, *connect.Request[v1.DeleteApiProviderRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.DeleteAPIProvider is not implemented"))
}

func (UnimplementedApiProviderServiceHandler) ListAPIProviderModels(context.Context, *connect.Request[v1.ListApiProviderModelsRequest]) (*connect.Response[v1.ListApiProviderModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.ApiProviderService.ListAPIProviderModels is not implemented"))
}
