// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/group_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMemberRole int32

const (
	GroupMemberRole_GROUP_MEMBER_ROLE_UNSPECIFIED GroupMemberRole = 0
	// Owners manage the group (update/delete) without workspace-level group
	// permissions.
	GroupMemberRole_OWNER  GroupMemberRole = 1
	GroupMemberRole_MEMBER GroupMemberRole = 2
)

// Enum value maps for GroupMemberRole.
var (
	GroupMemberRole_name = map[int32]string{
		0: "GROUP_MEMBER_ROLE_UNSPECIFIED",
		1: "OWNER",
		2: "MEMBER",
	}
	GroupMemberRole_value = map[string]int32{
		"GROUP_MEMBER_ROLE_UNSPECIFIED": 0,
		"OWNER":                         1,
		"MEMBER":                        2,
	}
)

func (x GroupMemberRole) Enum() *GroupMemberRole {
	p := new(GroupMemberRole)
	*p = x
	return p
}

func (x GroupMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_group_service_proto_enumTypes[0].Descriptor()
}

func (GroupMemberRole) Type() protoreflect.EnumType {
	return &file_v1_group_service_proto_enumTypes[0]
}

func (x GroupMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMemberRole.Descriptor instead.
func (GroupMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{0}
}

// Group is a named collection of users that can be bound in IAM policies
// (workspace, agent, and conversation bindings accept groups/{email} members).
// The IAM engine expands a group's members at authorization time.
type Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the group, in the form `groups/{id}`. The id is the
	// stable primary key; groups with an email also accept `groups/{email}` in
	// IAM bindings and Get requests (resolved by the store).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The group email, e.g. "eng@example.com". Optional: groups without an email
	// are referenced by their id only.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Human-readable title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Longer description of the group.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The group's members. Each member is a user resource name ("users/{uid}")
	// with a role: OWNER (may manage the group) or MEMBER.
	Members []*GroupMember `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	// Output only. When non-empty, the group is synced from an external source
	// (e.g. SCIM) and is read-only over this API.
	Source string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// Output only. True when the caller may manage this group: the caller is a
	// group OWNER or holds laelia.groups.update. Populated for the caller only.
	CanManage     bool `protobuf:"varint,7,opt,name=can_manage,json=canManage,proto3" json:"can_manage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_v1_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Group) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Group) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Group) GetCanManage() bool {
	if x != nil {
		return x.CanManage
	}
	return false
}

type GroupMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's user resource name, in the form `users/{uid}`.
	Member string `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// The member's role in the group.
	Role          GroupMemberRole `protobuf:"varint,2,opt,name=role,proto3,enum=laelia.v1.GroupMemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_v1_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *GroupMember) GetRole() GroupMemberRole {
	if x != nil {
		return x.Role
	}
	return GroupMemberRole_GROUP_MEMBER_ROLE_UNSPECIFIED
}

type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group resource name, in the form `groups/{email}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_v1_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BatchGetGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group resource names, in the form `groups/{email}`.
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGroupsRequest) Reset() {
	*x = BatchGetGroupsRequest{}
	mi := &file_v1_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGroupsRequest) ProtoMessage() {}

func (x *BatchGetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGroupsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetGroupsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type BatchGetGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGroupsResponse) Reset() {
	*x = BatchGetGroupsResponse{}
	mi := &file_v1_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGroupsResponse) ProtoMessage() {}

func (x *BatchGetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGroupsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListGroupsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter is used to filter groups returned in the list. Supported fields:
	// - title: equality on the group title.
	// - email: equality on the group email.
	// Example: title == "Engineering"
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_v1_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListGroupsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGroupsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_v1_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group email, e.g. "eng@example.com". Optional; groups without an email
	// are referenced by their generated id.
	GroupEmail string `protobuf:"bytes,1,opt,name=group_email,json=groupEmail,proto3" json:"group_email,omitempty"`
	// Optional stable id (lowercase alnum + dash). When empty, a UUID is
	// generated. The id is immutable after creation.
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The group to create. The name field is ignored (the id/email are taken
	// from group_id/group_email); title and members are required.
	Group         *Group `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_v1_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGroupRequest) GetGroupEmail() string {
	if x != nil {
		return x.GroupEmail
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupRequest) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group to update. The `name` field identifies the group.
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The list of fields to update: "title", "description", "members".
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_v1_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupRequest) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateGroupRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group resource name, in the form `groups/{email}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_v1_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GroupReference is one policy (workspace, agent, or conversation) that binds
// the group as a member.
type GroupReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the policy, e.g. "workspaces/-", "agents/{id}", or
	// "conversations/{id}".
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The policy resource type: WORKSPACE, AGENT, or CONVERSATION.
	ResourceType  string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupReference) Reset() {
	*x = GroupReference{}
	mi := &file_v1_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReference) ProtoMessage() {}

func (x *GroupReference) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReference.ProtoReflect.Descriptor instead.
func (*GroupReference) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *GroupReference) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GroupReference) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GroupReferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*GroupReference      `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupReferences) Reset() {
	*x = GroupReferences{}
	mi := &file_v1_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReferences) ProtoMessage() {}

func (x *GroupReferences) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReferences.ProtoReflect.Descriptor instead.
func (*GroupReferences) Descriptor() ([]byte, []int) {
	return file_v1_group_service_proto_rawDescGZIP(), []int{11}
}

func (x *GroupReferences) GetReferences() []*GroupReference {
	if x != nil {
		return x.References
	}
	return nil
}

var File_v1_group_service_proto protoreflect.FileDescriptor

const file_v1_group_service_proto_rawDesc = "" +
	"\n" +
	"\x16v1/group_service.proto\x12\tlaelia.v1\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x13v1/annotation.proto\"\x8c\x02\n" +
	"\x05Group\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\b\xe0A\x02R\x04name\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tB\x03\xe0A\x05R\x05email\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\amembers\x18\x05 \x03(\v2\x16.laelia.v1.GroupMemberR\amembers\x12\x1b\n" +
	"\x06source\x18\x06 \x01(\tB\x03\xe0A\x03R\x06source\x12\"\n" +
	"\n" +
	"can_manage\x18\a \x01(\bB\x03\xe0A\x03R\tcanManage:!\xeaA\x1e\n" +
	"\flaelia/Group\x12\x0egroups/{group}\"j\n" +
	"\vGroupMember\x12+\n" +
	"\x06member\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vlaelia/UserR\x06member\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.laelia.v1.GroupMemberRoleR\x04role\";\n" +
	"\x0fGetGroupRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/GroupR\x04name\"C\n" +
	"\x15BatchGetGroupsRequest\x12*\n" +
	"\x05names\x18\x01 \x03(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/GroupR\x05names\"B\n" +
	"\x16BatchGetGroupsResponse\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.laelia.v1.GroupR\x06groups\"g\n" +
	"\x11ListGroupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"f\n" +
	"\x12ListGroupsResponse\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.laelia.v1.GroupR\x06groups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"}\n" +
	"\x12CreateGroupRequest\x12\x1f\n" +
	"\vgroup_email\x18\x01 \x01(\tR\n" +
	"groupEmail\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12+\n" +
	"\x05group\x18\x02 \x01(\v2\x10.laelia.v1.GroupB\x03\xe0A\x02R\x05group\"~\n" +
	"\x12UpdateGroupRequest\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x10.laelia.v1.GroupB\x03\xe0A\x02R\x05group\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\">\n" +
	"\x12DeleteGroupRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/GroupR\x04name\"Q\n" +
	"\x0eGroupReference\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"L\n" +
	"\x0fGroupReferences\x129\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x19.laelia.v1.GroupReferenceR\n" +
	"references*K\n" +
	"\x0fGroupMemberRole\x12!\n" +
	"\x1dGROUP_MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05OWNER\x10\x01\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x022\x87\x06\n" +
	"\fGroupService\x12Z\n" +
	"\bGetGroup\x12\x1a.laelia.v1.GetGroupRequest\x1a\x10.laelia.v1.Group\" \xdaA\x04name\x8a\xea0\x11laelia.groups.get\x90\xea0\x01\x12p\n" +
	"\x0eBatchGetGroups\x12 .laelia.v1.BatchGetGroupsRequest\x1a!.laelia.v1.BatchGetGroupsResponse\"\x19\x8a\xea0\x11laelia.groups.get\x90\xea0\x01\x12e\n" +
	"\n" +
	"ListGroups\x12\x1c.laelia.v1.ListGroupsRequest\x1a\x1d.laelia.v1.ListGroupsResponse\"\x1a\x8a\xea0\x12laelia.groups.list\x90\xea0\x01\x12t\n" +
	"\vCreateGroup\x12\x1d.laelia.v1.CreateGroupRequest\x1a\x10.laelia.v1.Group\"4\xdaA\x11group_email,group\x8a\xea0\x14laelia.groups.create\x90\xea0\x01\x98\xea0\x01\x12t\n" +
	"\vUpdateGroup\x12\x1d.laelia.v1.UpdateGroupRequest\x1a\x10.laelia.v1.Group\"4\xdaA\x11group,update_mask\x8a\xea0\x14laelia.groups.update\x90\xea0\x01\x98\xea0\x01\x12m\n" +
	"\vDeleteGroup\x12\x1d.laelia.v1.DeleteGroupRequest\x1a\x16.google.protobuf.Empty\"'\xdaA\x04name\x8a\xea0\x14laelia.groups.delete\x90\xea0\x01\x98\xea0\x01\x12g\n" +
	"\x12GetGroupReferences\x12\x1a.laelia.v1.GetGroupRequest\x1a\x1a.laelia.v1.GroupReferences\"\x19\x8a\xea0\x11laelia.groups.get\x90\xea0\x01B7Z5github.com/tbdavid2019/888a2a/backend/generated-go/v1b\x06proto3"

var (
	file_v1_group_service_proto_rawDescOnce sync.Once
	file_v1_group_service_proto_rawDescData []byte
)

func file_v1_group_service_proto_rawDescGZIP() []byte {
	file_v1_group_service_proto_rawDescOnce.Do(func() {
		file_v1_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_group_service_proto_rawDesc), len(file_v1_group_service_proto_rawDesc)))
	})
	return file_v1_group_service_proto_rawDescData
}

var file_v1_group_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_group_service_proto_goTypes = []any{
	(GroupMemberRole)(0),           // 0: laelia.v1.GroupMemberRole
	(*Group)(nil),                  // 1: laelia.v1.Group
	(*GroupMember)(nil),            // 2: laelia.v1.GroupMember
	(*GetGroupRequest)(nil),        // 3: laelia.v1.GetGroupRequest
	(*BatchGetGroupsRequest)(nil),  // 4: laelia.v1.BatchGetGroupsRequest
	(*BatchGetGroupsResponse)(nil), // 5: laelia.v1.BatchGetGroupsResponse
	(*ListGroupsRequest)(nil),      // 6: laelia.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),     // 7: laelia.v1.ListGroupsResponse
	(*CreateGroupRequest)(nil),     // 8: laelia.v1.CreateGroupRequest
	(*UpdateGroupRequest)(nil),     // 9: laelia.v1.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),     // 10: laelia.v1.DeleteGroupRequest
	(*GroupReference)(nil),         // 11: laelia.v1.GroupReference
	(*GroupReferences)(nil),        // 12: laelia.v1.GroupReferences
	(*fieldmaskpb.FieldMask)(nil),  // 13: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 14: google.protobuf.Empty
}
var file_v1_group_service_proto_depIdxs = []int32{
	2,  // 0: laelia.v1.Group.members:type_name -> laelia.v1.GroupMember
	0,  // 1: laelia.v1.GroupMember.role:type_name -> laelia.v1.GroupMemberRole
	1,  // 2: laelia.v1.BatchGetGroupsResponse.groups:type_name -> laelia.v1.Group
	1,  // 3: laelia.v1.ListGroupsResponse.groups:type_name -> laelia.v1.Group
	1,  // 4: laelia.v1.CreateGroupRequest.group:type_name -> laelia.v1.Group
	1,  // 5: laelia.v1.UpdateGroupRequest.group:type_name -> laelia.v1.Group
	13, // 6: laelia.v1.UpdateGroupRequest.update_mask:type_name -> google.protobuf.FieldMask
	11, // 7: laelia.v1.GroupReferences.references:type_name -> laelia.v1.GroupReference
	3,  // 8: laelia.v1.GroupService.GetGroup:input_type -> laelia.v1.GetGroupRequest
	4,  // 9: laelia.v1.GroupService.BatchGetGroups:input_type -> laelia.v1.BatchGetGroupsRequest
	6,  // 10: laelia.v1.GroupService.ListGroups:input_type -> laelia.v1.ListGroupsRequest
	8,  // 11: laelia.v1.GroupService.CreateGroup:input_type -> laelia.v1.CreateGroupRequest
	9,  // 12: laelia.v1.GroupService.UpdateGroup:input_type -> laelia.v1.UpdateGroupRequest
	10, // 13: laelia.v1.GroupService.DeleteGroup:input_type -> laelia.v1.DeleteGroupRequest
	3,  // 14: laelia.v1.GroupService.GetGroupReferences:input_type -> laelia.v1.GetGroupRequest
	1,  // 15: laelia.v1.GroupService.GetGroup:output_type -> laelia.v1.Group
	5,  // 16: laelia.v1.GroupService.BatchGetGroups:output_type -> laelia.v1.BatchGetGroupsResponse
	7,  // 17: laelia.v1.GroupService.ListGroups:output_type -> laelia.v1.ListGroupsResponse
	1,  // 18: laelia.v1.GroupService.CreateGroup:output_type -> laelia.v1.Group
	1,  // 19: laelia.v1.GroupService.UpdateGroup:output_type -> laelia.v1.Group
	14, // 20: laelia.v1.GroupService.DeleteGroup:output_type -> google.protobuf.Empty
	12, // 21: laelia.v1.GroupService.GetGroupReferences:output_type -> laelia.v1.GroupReferences
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_group_service_proto_init() }
func file_v1_group_service_proto_init() {
	if File_v1_group_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_group_service_proto_rawDesc), len(file_v1_group_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_group_service_proto_goTypes,
		DependencyIndexes: file_v1_group_service_proto_depIdxs,
		EnumInfos:         file_v1_group_service_proto_enumTypes,
		MessageInfos:      file_v1_group_service_proto_msgTypes,
	}.Build()
	File_v1_group_service_proto = out.File
	file_v1_group_service_proto_goTypes = nil
	file_v1_group_service_proto_depIdxs = nil
}
