// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/iam_service.proto

package v1

import (
	store "github.com/tbdavid2019/888a2a/backend/generated-go/store"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	expr "google.golang.org/genproto/googleapis/type/expr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action is the type of change applied to a binding.
type BindingDelta_Action int32

const (
	// Unspecified action.
	BindingDelta_ACTION_UNSPECIFIED BindingDelta_Action = 0
	// The member was added to the role.
	BindingDelta_ADD BindingDelta_Action = 1
	// The member was removed from the role.
	BindingDelta_REMOVE BindingDelta_Action = 2
)

// Enum value maps for BindingDelta_Action.
var (
	BindingDelta_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ADD",
		2: "REMOVE",
	}
	BindingDelta_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ADD":                1,
		"REMOVE":             2,
	}
)

func (x BindingDelta_Action) Enum() *BindingDelta_Action {
	p := new(BindingDelta_Action)
	*p = x
	return p
}

func (x BindingDelta_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingDelta_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_iam_service_proto_enumTypes[0].Descriptor()
}

func (BindingDelta_Action) Type() protoreflect.EnumType {
	return &file_v1_iam_service_proto_enumTypes[0]
}

func (x BindingDelta_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingDelta_Action.Descriptor instead.
func (BindingDelta_Action) EnumDescriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{1, 0}
}

// IamPolicyView is an IAM policy together with its etag. The etag is returned
// by Get and must be supplied on Set for optimistic concurrency: a Set whose
// etag does not match the stored policy's etag is rejected with
// connect.CodeAborted so the caller can re-fetch and retry.
type IamPolicyView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *store.IamPolicy       `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IamPolicyView) Reset() {
	*x = IamPolicyView{}
	mi := &file_v1_iam_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IamPolicyView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IamPolicyView) ProtoMessage() {}

func (x *IamPolicyView) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IamPolicyView.ProtoReflect.Descriptor instead.
func (*IamPolicyView) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{0}
}

func (x *IamPolicyView) GetPolicy() *store.IamPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *IamPolicyView) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// BindingDelta describes a single member-role-condition change between two
// IAM policies. It is computed on Set and recorded in the audit log so an
// operator can see who granted or removed what.
type BindingDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action that was performed on the binding.
	Action BindingDelta_Action `protobuf:"varint,1,opt,name=action,proto3,enum=laelia.v1.BindingDelta_Action" json:"action,omitempty"`
	// The affected member, e.g. "users/101", "groups/eng@example.com",
	// "agents/{rid}", or "allUsers".
	Member string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	// The affected role, in the form "roles/{role}".
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// The condition associated with the changed binding, if any.
	Condition     *expr.Expr `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingDelta) Reset() {
	*x = BindingDelta{}
	mi := &file_v1_iam_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingDelta) ProtoMessage() {}

func (x *BindingDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingDelta.ProtoReflect.Descriptor instead.
func (*BindingDelta) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{1}
}

func (x *BindingDelta) GetAction() BindingDelta_Action {
	if x != nil {
		return x.Action
	}
	return BindingDelta_ACTION_UNSPECIFIED
}

func (x *BindingDelta) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *BindingDelta) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BindingDelta) GetCondition() *expr.Expr {
	if x != nil {
		return x.Condition
	}
	return nil
}

// PolicyDelta describes the changes between two IAM policies.
type PolicyDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The binding deltas between the previous and the new policy.
	BindingDeltas []*BindingDelta `protobuf:"bytes,1,rep,name=binding_deltas,json=bindingDeltas,proto3" json:"binding_deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDelta) Reset() {
	*x = PolicyDelta{}
	mi := &file_v1_iam_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDelta) ProtoMessage() {}

func (x *PolicyDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDelta.ProtoReflect.Descriptor instead.
func (*PolicyDelta) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyDelta) GetBindingDeltas() []*BindingDelta {
	if x != nil {
		return x.BindingDeltas
	}
	return nil
}

// IamPolicyChange is the audit payload recorded for a successful SetIamPolicy
// call: the target resource and the binding deltas applied.
type IamPolicyChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource the policy was set on, e.g. "workspaces/-" for the workspace
	// policy or "agents/{agent}" for an agent policy.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The binding changes applied by the Set.
	BindingDeltas []*BindingDelta `protobuf:"bytes,2,rep,name=binding_deltas,json=bindingDeltas,proto3" json:"binding_deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IamPolicyChange) Reset() {
	*x = IamPolicyChange{}
	mi := &file_v1_iam_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IamPolicyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IamPolicyChange) ProtoMessage() {}

func (x *IamPolicyChange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IamPolicyChange.ProtoReflect.Descriptor instead.
func (*IamPolicyChange) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{3}
}

func (x *IamPolicyChange) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *IamPolicyChange) GetBindingDeltas() []*BindingDelta {
	if x != nil {
		return x.BindingDeltas
	}
	return nil
}

type GetWorkspaceIamPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceIamPolicyRequest) Reset() {
	*x = GetWorkspaceIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceIamPolicyRequest) ProtoMessage() {}

func (x *GetWorkspaceIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{4}
}

type SetWorkspaceIamPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *store.IamPolicy       `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkspaceIamPolicyRequest) Reset() {
	*x = SetWorkspaceIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkspaceIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkspaceIamPolicyRequest) ProtoMessage() {}

func (x *SetWorkspaceIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkspaceIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetWorkspaceIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetWorkspaceIamPolicyRequest) GetPolicy() *store.IamPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SetWorkspaceIamPolicyRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type GetAgentIamPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent resource name, in the form `agents/{agent}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentIamPolicyRequest) Reset() {
	*x = GetAgentIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIamPolicyRequest) ProtoMessage() {}

func (x *GetAgentIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetAgentIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentIamPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetAgentIamPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent resource name, in the form `agents/{agent}`.
	Name          string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Policy        *store.IamPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Etag          string           `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgentIamPolicyRequest) Reset() {
	*x = SetAgentIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgentIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentIamPolicyRequest) ProtoMessage() {}

func (x *SetAgentIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetAgentIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetAgentIamPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetAgentIamPolicyRequest) GetPolicy() *store.IamPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SetAgentIamPolicyRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type GetMachineIamPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The machine resource name, in the form `machines/{machine}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineIamPolicyRequest) Reset() {
	*x = GetMachineIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineIamPolicyRequest) ProtoMessage() {}

func (x *GetMachineIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetMachineIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMachineIamPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetMachineIamPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The machine resource name, in the form `machines/{machine}`.
	Name          string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Policy        *store.IamPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Etag          string           `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMachineIamPolicyRequest) Reset() {
	*x = SetMachineIamPolicyRequest{}
	mi := &file_v1_iam_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMachineIamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMachineIamPolicyRequest) ProtoMessage() {}

func (x *SetMachineIamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_iam_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMachineIamPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetMachineIamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_iam_service_proto_rawDescGZIP(), []int{9}
}

func (x *SetMachineIamPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMachineIamPolicyRequest) GetPolicy() *store.IamPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SetMachineIamPolicyRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_v1_iam_service_proto protoreflect.FileDescriptor

const file_v1_iam_service_proto_rawDesc = "" +
	"\n" +
	"\x14v1/iam_service.proto\x12\tlaelia.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x16google/type/expr.proto\x1a\x12store/policy.proto\x1a\x13v1/annotation.proto\"T\n" +
	"\rIamPolicyView\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.laelia.store.IamPolicyR\x06policy\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"\xda\x01\n" +
	"\fBindingDelta\x126\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1e.laelia.v1.BindingDelta.ActionR\x06action\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12/\n" +
	"\tcondition\x18\x04 \x01(\v2\x11.google.type.ExprR\tcondition\"5\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\"M\n" +
	"\vPolicyDelta\x12>\n" +
	"\x0ebinding_deltas\x18\x01 \x03(\v2\x17.laelia.v1.BindingDeltaR\rbindingDeltas\"m\n" +
	"\x0fIamPolicyChange\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12>\n" +
	"\x0ebinding_deltas\x18\x02 \x03(\v2\x17.laelia.v1.BindingDeltaR\rbindingDeltas\"\x1e\n" +
	"\x1cGetWorkspaceIamPolicyRequest\"h\n" +
	"\x1cSetWorkspaceIamPolicyRequest\x124\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.laelia.store.IamPolicyB\x03\xe0A\x02R\x06policy\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"D\n" +
	"\x18GetAgentIamPolicyRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/AgentR\x04name\"\x8e\x01\n" +
	"\x18SetAgentIamPolicyRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/AgentR\x04name\x124\n" +
	"\x06policy\x18\x02 \x01(\v2\x17.laelia.store.IamPolicyB\x03\xe0A\x02R\x06policy\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"H\n" +
	"\x1aGetMachineIamPolicyRequest\x12*\n" +
	"\x04name\x18\x01 \x01(\tB\x16\xe0A\x02\xfaA\x10\n" +
	"\x0elaelia/MachineR\x04name\"\x92\x01\n" +
	"\x1aSetMachineIamPolicyRequest\x12*\n" +
	"\x04name\x18\x01 \x01(\tB\x16\xe0A\x02\xfaA\x10\n" +
	"\x0elaelia/MachineR\x04name\x124\n" +
	"\x06policy\x18\x02 \x01(\v2\x17.laelia.store.IamPolicyB\x03\xe0A\x02R\x06policy\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag2\xac\x05\n" +
	"\n" +
	"IamService\x12x\n" +
	"\x15GetWorkspaceIamPolicy\x12'.laelia.v1.GetWorkspaceIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\"\x1c\x8a\xea0\x14laelia.iam.getPolicy\x90\xea0\x01\x12|\n" +
	"\x15SetWorkspaceIamPolicy\x12'.laelia.v1.SetWorkspaceIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\" \x8a\xea0\x14laelia.iam.setPolicy\x90\xea0\x01\x98\xea0\x01\x12p\n" +
	"\x11GetAgentIamPolicy\x12#.laelia.v1.GetAgentIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\"\x1c\x8a\xea0\x14laelia.iam.getPolicy\x90\xea0\x01\x12t\n" +
	"\x11SetAgentIamPolicy\x12#.laelia.v1.SetAgentIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\" \x8a\xea0\x14laelia.iam.setPolicy\x90\xea0\x01\x98\xea0\x01\x12\\\n" +
	"\x13GetMachineIamPolicy\x12%.laelia.v1.GetMachineIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\"\x04\x90\xea0\x01\x12`\n" +
	"\x13SetMachineIamPolicy\x12%.laelia.v1.SetMachineIamPolicyRequest\x1a\x18.laelia.v1.IamPolicyView\"\b\x90\xea0\x01\x98\xea0\x01B7Z5github.com/tbdavid2019/888a2a/backend/generated-go/v1b\x06proto3"

var (
	file_v1_iam_service_proto_rawDescOnce sync.Once
	file_v1_iam_service_proto_rawDescData []byte
)

func file_v1_iam_service_proto_rawDescGZIP() []byte {
	file_v1_iam_service_proto_rawDescOnce.Do(func() {
		file_v1_iam_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_iam_service_proto_rawDesc), len(file_v1_iam_service_proto_rawDesc)))
	})
	return file_v1_iam_service_proto_rawDescData
}

var file_v1_iam_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_iam_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_iam_service_proto_goTypes = []any{
	(BindingDelta_Action)(0),             // 0: laelia.v1.BindingDelta.Action
	(*IamPolicyView)(nil),                // 1: laelia.v1.IamPolicyView
	(*BindingDelta)(nil),                 // 2: laelia.v1.BindingDelta
	(*PolicyDelta)(nil),                  // 3: laelia.v1.PolicyDelta
	(*IamPolicyChange)(nil),              // 4: laelia.v1.IamPolicyChange
	(*GetWorkspaceIamPolicyRequest)(nil), // 5: laelia.v1.GetWorkspaceIamPolicyRequest
	(*SetWorkspaceIamPolicyRequest)(nil), // 6: laelia.v1.SetWorkspaceIamPolicyRequest
	(*GetAgentIamPolicyRequest)(nil),     // 7: laelia.v1.GetAgentIamPolicyRequest
	(*SetAgentIamPolicyRequest)(nil),     // 8: laelia.v1.SetAgentIamPolicyRequest
	(*GetMachineIamPolicyRequest)(nil),   // 9: laelia.v1.GetMachineIamPolicyRequest
	(*SetMachineIamPolicyRequest)(nil),   // 10: laelia.v1.SetMachineIamPolicyRequest
	(*store.IamPolicy)(nil),              // 11: laelia.store.IamPolicy
	(*expr.Expr)(nil),                    // 12: google.type.Expr
}
var file_v1_iam_service_proto_depIdxs = []int32{
	11, // 0: laelia.v1.IamPolicyView.policy:type_name -> laelia.store.IamPolicy
	0,  // 1: laelia.v1.BindingDelta.action:type_name -> laelia.v1.BindingDelta.Action
	12, // 2: laelia.v1.BindingDelta.condition:type_name -> google.type.Expr
	2,  // 3: laelia.v1.PolicyDelta.binding_deltas:type_name -> laelia.v1.BindingDelta
	2,  // 4: laelia.v1.IamPolicyChange.binding_deltas:type_name -> laelia.v1.BindingDelta
	11, // 5: laelia.v1.SetWorkspaceIamPolicyRequest.policy:type_name -> laelia.store.IamPolicy
	11, // 6: laelia.v1.SetAgentIamPolicyRequest.policy:type_name -> laelia.store.IamPolicy
	11, // 7: laelia.v1.SetMachineIamPolicyRequest.policy:type_name -> laelia.store.IamPolicy
	5,  // 8: laelia.v1.IamService.GetWorkspaceIamPolicy:input_type -> laelia.v1.GetWorkspaceIamPolicyRequest
	6,  // 9: laelia.v1.IamService.SetWorkspaceIamPolicy:input_type -> laelia.v1.SetWorkspaceIamPolicyRequest
	7,  // 10: laelia.v1.IamService.GetAgentIamPolicy:input_type -> laelia.v1.GetAgentIamPolicyRequest
	8,  // 11: laelia.v1.IamService.SetAgentIamPolicy:input_type -> laelia.v1.SetAgentIamPolicyRequest
	9,  // 12: laelia.v1.IamService.GetMachineIamPolicy:input_type -> laelia.v1.GetMachineIamPolicyRequest
	10, // 13: laelia.v1.IamService.SetMachineIamPolicy:input_type -> laelia.v1.SetMachineIamPolicyRequest
	1,  // 14: laelia.v1.IamService.GetWorkspaceIamPolicy:output_type -> laelia.v1.IamPolicyView
	1,  // 15: laelia.v1.IamService.SetWorkspaceIamPolicy:output_type -> laelia.v1.IamPolicyView
	1,  // 16: laelia.v1.IamService.GetAgentIamPolicy:output_type -> laelia.v1.IamPolicyView
	1,  // 17: laelia.v1.IamService.SetAgentIamPolicy:output_type -> laelia.v1.IamPolicyView
	1,  // 18: laelia.v1.IamService.GetMachineIamPolicy:output_type -> laelia.v1.IamPolicyView
	1,  // 19: laelia.v1.IamService.SetMachineIamPolicy:output_type -> laelia.v1.IamPolicyView
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_iam_service_proto_init() }
func file_v1_iam_service_proto_init() {
	if File_v1_iam_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_iam_service_proto_rawDesc), len(file_v1_iam_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_iam_service_proto_goTypes,
		DependencyIndexes: file_v1_iam_service_proto_depIdxs,
		EnumInfos:         file_v1_iam_service_proto_enumTypes,
		MessageInfos:      file_v1_iam_service_proto_msgTypes,
	}.Build()
	File_v1_iam_service_proto = out.File
	file_v1_iam_service_proto_goTypes = nil
	file_v1_iam_service_proto_depIdxs = nil
}
