// @generated by protoc-gen-es v2.12.0
// @generated from file v1/agent.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import type { State } from "./common_pb";

/**
 * Describes the file v1/agent.proto.
 */
export declare const file_v1_agent: GenFile;

/**
 * @generated from message laelia.v1.CreateAgentRequest
 */
export declare type CreateAgentRequest = Message<"laelia.v1.CreateAgentRequest"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;
};

/**
 * Describes the message laelia.v1.CreateAgentRequest.
 * Use `create(CreateAgentRequestSchema)` to create a new message.
 */
export declare const CreateAgentRequestSchema: GenMessage<CreateAgentRequest>;

/**
 * @generated from message laelia.v1.CreateAgentResponse
 */
export declare type CreateAgentResponse = Message<"laelia.v1.CreateAgentResponse"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;

  /**
   * 7-day validity, reusable until rotated/revoked
   *
   * @generated from field: string bootstrap_token = 2;
   */
  bootstrapToken: string;
};

/**
 * Describes the message laelia.v1.CreateAgentResponse.
 * Use `create(CreateAgentResponseSchema)` to create a new message.
 */
export declare const CreateAgentResponseSchema: GenMessage<CreateAgentResponse>;

/**
 * @generated from message laelia.v1.UpdateAgentRequest
 */
export declare type UpdateAgentRequest = Message<"laelia.v1.UpdateAgentRequest"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message laelia.v1.UpdateAgentRequest.
 * Use `create(UpdateAgentRequestSchema)` to create a new message.
 */
export declare const UpdateAgentRequestSchema: GenMessage<UpdateAgentRequest>;

/**
 * @generated from message laelia.v1.TransferAgentOwnershipRequest
 */
export declare type TransferAgentOwnershipRequest = Message<"laelia.v1.TransferAgentOwnershipRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * New owner's user resource name (users/{id}).
   *
   * @generated from field: string new_owner = 2;
   */
  newOwner: string;

  /**
   * audit purpose
   *
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.TransferAgentOwnershipRequest.
 * Use `create(TransferAgentOwnershipRequestSchema)` to create a new message.
 */
export declare const TransferAgentOwnershipRequestSchema: GenMessage<TransferAgentOwnershipRequest>;

/**
 * @generated from message laelia.v1.TransferAgentOwnershipResponse
 */
export declare type TransferAgentOwnershipResponse = Message<"laelia.v1.TransferAgentOwnershipResponse"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;
};

/**
 * Describes the message laelia.v1.TransferAgentOwnershipResponse.
 * Use `create(TransferAgentOwnershipResponseSchema)` to create a new message.
 */
export declare const TransferAgentOwnershipResponseSchema: GenMessage<TransferAgentOwnershipResponse>;

/**
 * @generated from message laelia.v1.RotateAgentTokenRequest
 */
export declare type RotateAgentTokenRequest = Message<"laelia.v1.RotateAgentTokenRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * audit purpose
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.RotateAgentTokenRequest.
 * Use `create(RotateAgentTokenRequestSchema)` to create a new message.
 */
export declare const RotateAgentTokenRequestSchema: GenMessage<RotateAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RotateAgentTokenResponse
 */
export declare type RotateAgentTokenResponse = Message<"laelia.v1.RotateAgentTokenResponse"> & {
  /**
   * new bootstrap token
   *
   * @generated from field: string bootstrap_token = 1;
   */
  bootstrapToken: string;
};

/**
 * Describes the message laelia.v1.RotateAgentTokenResponse.
 * Use `create(RotateAgentTokenResponseSchema)` to create a new message.
 */
export declare const RotateAgentTokenResponseSchema: GenMessage<RotateAgentTokenResponse>;

/**
 * @generated from message laelia.v1.RevokeAgentTokenRequest
 */
export declare type RevokeAgentTokenRequest = Message<"laelia.v1.RevokeAgentTokenRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.RevokeAgentTokenRequest.
 * Use `create(RevokeAgentTokenRequestSchema)` to create a new message.
 */
export declare const RevokeAgentTokenRequestSchema: GenMessage<RevokeAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RevokeAgentTokenResponse
 */
export declare type RevokeAgentTokenResponse = Message<"laelia.v1.RevokeAgentTokenResponse"> & {
};

/**
 * Describes the message laelia.v1.RevokeAgentTokenResponse.
 * Use `create(RevokeAgentTokenResponseSchema)` to create a new message.
 */
export declare const RevokeAgentTokenResponseSchema: GenMessage<RevokeAgentTokenResponse>;

/**
 * @generated from message laelia.v1.ForceDisconnectAgentRequest
 */
export declare type ForceDisconnectAgentRequest = Message<"laelia.v1.ForceDisconnectAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.ForceDisconnectAgentRequest.
 * Use `create(ForceDisconnectAgentRequestSchema)` to create a new message.
 */
export declare const ForceDisconnectAgentRequestSchema: GenMessage<ForceDisconnectAgentRequest>;

/**
 * @generated from message laelia.v1.ListAgentSessionsRequest
 */
export declare type ListAgentSessionsRequest = Message<"laelia.v1.ListAgentSessionsRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * default: only active sessions
   *
   * @generated from field: bool include_terminated = 4;
   */
  includeTerminated: boolean;
};

/**
 * Describes the message laelia.v1.ListAgentSessionsRequest.
 * Use `create(ListAgentSessionsRequestSchema)` to create a new message.
 */
export declare const ListAgentSessionsRequestSchema: GenMessage<ListAgentSessionsRequest>;

/**
 * @generated from message laelia.v1.ListAgentSessionsResponse
 */
export declare type ListAgentSessionsResponse = Message<"laelia.v1.ListAgentSessionsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.AgentSession sessions = 1;
   */
  sessions: AgentSession[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListAgentSessionsResponse.
 * Use `create(ListAgentSessionsResponseSchema)` to create a new message.
 */
export declare const ListAgentSessionsResponseSchema: GenMessage<ListAgentSessionsResponse>;

/**
 * @generated from message laelia.v1.AgentSession
 */
export declare type AgentSession = Message<"laelia.v1.AgentSession"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string agent_name = 2;
   */
  agentName: string;

  /**
   * @generated from field: string source_ip = 3;
   */
  sourceIp: string;

  /**
   * @generated from field: string agent_version = 4;
   */
  agentVersion: string;

  /**
   * @generated from field: string fingerprint = 5;
   */
  fingerprint: string;

  /**
   * @generated from field: google.protobuf.Timestamp connected_at = 6;
   */
  connectedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp last_heartbeat_at = 7;
   */
  lastHeartbeatAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp disconnected_at = 8;
   */
  disconnectedAt?: Timestamp | undefined;

  /**
   * @generated from field: string disconnect_reason = 9;
   */
  disconnectReason: string;

  /**
   * @generated from field: laelia.v1.AgentStatus.ConnectionState state = 10;
   */
  state: AgentStatus_ConnectionState;
};

/**
 * Describes the message laelia.v1.AgentSession.
 * Use `create(AgentSessionSchema)` to create a new message.
 */
export declare const AgentSessionSchema: GenMessage<AgentSession>;

/**
 * @generated from message laelia.v1.ConnectAgentRequest
 */
export declare type ConnectAgentRequest = Message<"laelia.v1.ConnectAgentRequest"> & {
  /**
   * first connection or after refresh failure
   *
   * @generated from field: string bootstrap_token = 1;
   */
  bootstrapToken: string;

  /**
   * @generated from field: laelia.v1.AgentInfo info = 2;
   */
  info?: AgentInfo | undefined;

  /**
   * client-generated connection fingerprint (hostname:os:arch)
   *
   * @generated from field: string fingerprint = 3;
   */
  fingerprint: string;
};

/**
 * Describes the message laelia.v1.ConnectAgentRequest.
 * Use `create(ConnectAgentRequestSchema)` to create a new message.
 */
export declare const ConnectAgentRequestSchema: GenMessage<ConnectAgentRequest>;

/**
 * @generated from message laelia.v1.ConnectAgentResponse
 */
export declare type ConnectAgentResponse = Message<"laelia.v1.ConnectAgentResponse"> & {
  /**
   * 15-minute validity
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * 24-hour validity, single-use rotation
   *
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * session identifier
   *
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * server-signed nonce for next heartbeat
   *
   * @generated from field: string next_nonce = 4;
   */
  nextNonce: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 5;
   */
  accessTokenExpiresAt?: Timestamp | undefined;

  /**
   * @generated from field: laelia.v1.AgentStatus initial_status = 6;
   */
  initialStatus?: AgentStatus | undefined;

  /**
   * server-provided structured ACP config
   *
   * @generated from field: laelia.v1.AgentACPConfig acp_config = 7;
   */
  acpConfig?: AgentACPConfig | undefined;
};

/**
 * Describes the message laelia.v1.ConnectAgentResponse.
 * Use `create(ConnectAgentResponseSchema)` to create a new message.
 */
export declare const ConnectAgentResponseSchema: GenMessage<ConnectAgentResponse>;

/**
 * @generated from message laelia.v1.AgentHeartbeatRequest
 */
export declare type AgentHeartbeatRequest = Message<"laelia.v1.AgentHeartbeatRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * nonce from previous response (replay protection)
   *
   * @generated from field: string previous_nonce = 2;
   */
  previousNonce: string;

  /**
   * optional agent metrics
   *
   * @generated from field: laelia.v1.AgentMetrics metrics = 3;
   */
  metrics?: AgentMetrics | undefined;
};

/**
 * Describes the message laelia.v1.AgentHeartbeatRequest.
 * Use `create(AgentHeartbeatRequestSchema)` to create a new message.
 */
export declare const AgentHeartbeatRequestSchema: GenMessage<AgentHeartbeatRequest>;

/**
 * @generated from message laelia.v1.AgentHeartbeatResponse
 */
export declare type AgentHeartbeatResponse = Message<"laelia.v1.AgentHeartbeatResponse"> & {
  /**
   * nonce for next request
   *
   * @generated from field: string next_nonce = 1;
   */
  nextNonce: string;

  /**
   * expected next heartbeat time
   *
   * @generated from field: google.protobuf.Timestamp next_heartbeat_at = 2;
   */
  nextHeartbeatAt?: Timestamp | undefined;

  /**
   * new access token (only if expiring soon)
   *
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 4;
   */
  accessTokenExpiresAt?: Timestamp | undefined;

  /**
   * Fallback channel: when bidi command stream is unavailable
   *
   * @generated from field: bool command_stream_required = 5;
   */
  commandStreamRequired: boolean;

  /**
   * @generated from field: laelia.v1.PendingCommandHint pending_command_hint = 6;
   */
  pendingCommandHint?: PendingCommandHint | undefined;
};

/**
 * Describes the message laelia.v1.AgentHeartbeatResponse.
 * Use `create(AgentHeartbeatResponseSchema)` to create a new message.
 */
export declare const AgentHeartbeatResponseSchema: GenMessage<AgentHeartbeatResponse>;

/**
 * @generated from message laelia.v1.PendingCommandHint
 */
export declare type PendingCommandHint = Message<"laelia.v1.PendingCommandHint"> & {
  /**
   * @generated from field: string command_id = 1;
   */
  commandId: string;

  /**
   * @generated from field: string command = 2;
   */
  command: string;

  /**
   * @generated from field: map<string, string> env = 3;
   */
  env: { [key: string]: string };

  /**
   * @generated from field: string working_dir = 4;
   */
  workingDir: string;

  /**
   * @generated from field: int32 timeout_seconds = 5;
   */
  timeoutSeconds: number;
};

/**
 * Describes the message laelia.v1.PendingCommandHint.
 * Use `create(PendingCommandHintSchema)` to create a new message.
 */
export declare const PendingCommandHintSchema: GenMessage<PendingCommandHint>;

/**
 * @generated from message laelia.v1.AgentDisconnectRequest
 */
export declare type AgentDisconnectRequest = Message<"laelia.v1.AgentDisconnectRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * "shutdown", "upgrade" etc.
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.AgentDisconnectRequest.
 * Use `create(AgentDisconnectRequestSchema)` to create a new message.
 */
export declare const AgentDisconnectRequestSchema: GenMessage<AgentDisconnectRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentTokenRequest
 */
export declare type RefreshAgentTokenRequest = Message<"laelia.v1.RefreshAgentTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * verify connection fingerprint
   *
   * @generated from field: string fingerprint = 2;
   */
  fingerprint: string;
};

/**
 * Describes the message laelia.v1.RefreshAgentTokenRequest.
 * Use `create(RefreshAgentTokenRequestSchema)` to create a new message.
 */
export declare const RefreshAgentTokenRequestSchema: GenMessage<RefreshAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentTokenResponse
 */
export declare type RefreshAgentTokenResponse = Message<"laelia.v1.RefreshAgentTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * new refresh token (rotation)
   *
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 3;
   */
  accessTokenExpiresAt?: Timestamp | undefined;
};

/**
 * Describes the message laelia.v1.RefreshAgentTokenResponse.
 * Use `create(RefreshAgentTokenResponseSchema)` to create a new message.
 */
export declare const RefreshAgentTokenResponseSchema: GenMessage<RefreshAgentTokenResponse>;

/**
 * @generated from message laelia.v1.ListAgentsRequest
 */
export declare type ListAgentsRequest = Message<"laelia.v1.ListAgentsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: bool show_deleted = 3;
   */
  showDeleted: boolean;

  /**
   * parent, when set to a machine resource name (machines/{machine}), filters
   * the list to agents bound to that machine. Empty lists all agents.
   *
   * @generated from field: string parent = 4;
   */
  parent: string;
};

/**
 * Describes the message laelia.v1.ListAgentsRequest.
 * Use `create(ListAgentsRequestSchema)` to create a new message.
 */
export declare const ListAgentsRequestSchema: GenMessage<ListAgentsRequest>;

/**
 * @generated from message laelia.v1.ListAgentsResponse
 */
export declare type ListAgentsResponse = Message<"laelia.v1.ListAgentsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.AgentSummary agents = 1;
   */
  agents: AgentSummary[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListAgentsResponse.
 * Use `create(ListAgentsResponseSchema)` to create a new message.
 */
export declare const ListAgentsResponseSchema: GenMessage<ListAgentsResponse>;

/**
 * @generated from message laelia.v1.GetAgentRequest
 */
export declare type GetAgentRequest = Message<"laelia.v1.GetAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.GetAgentRequest.
 * Use `create(GetAgentRequestSchema)` to create a new message.
 */
export declare const GetAgentRequestSchema: GenMessage<GetAgentRequest>;

/**
 * @generated from message laelia.v1.DeleteAgentRequest
 */
export declare type DeleteAgentRequest = Message<"laelia.v1.DeleteAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteAgentRequest.
 * Use `create(DeleteAgentRequestSchema)` to create a new message.
 */
export declare const DeleteAgentRequestSchema: GenMessage<DeleteAgentRequest>;

/**
 * @generated from message laelia.v1.StopAgentRequest
 */
export declare type StopAgentRequest = Message<"laelia.v1.StopAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.StopAgentRequest.
 * Use `create(StopAgentRequestSchema)` to create a new message.
 */
export declare const StopAgentRequestSchema: GenMessage<StopAgentRequest>;

/**
 * @generated from message laelia.v1.StartAgentRequest
 */
export declare type StartAgentRequest = Message<"laelia.v1.StartAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.StartAgentRequest.
 * Use `create(StartAgentRequestSchema)` to create a new message.
 */
export declare const StartAgentRequestSchema: GenMessage<StartAgentRequest>;

/**
 * @generated from message laelia.v1.UpdateAgentACPConfigRequest
 */
export declare type UpdateAgentACPConfigRequest = Message<"laelia.v1.UpdateAgentACPConfigRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: laelia.v1.AgentACPConfig acp_config = 2;
   */
  acpConfig?: AgentACPConfig | undefined;
};

/**
 * Describes the message laelia.v1.UpdateAgentACPConfigRequest.
 * Use `create(UpdateAgentACPConfigRequestSchema)` to create a new message.
 */
export declare const UpdateAgentACPConfigRequestSchema: GenMessage<UpdateAgentACPConfigRequest>;

/**
 * @generated from message laelia.v1.UpdateAgentMcpConfigRequest
 */
export declare type UpdateAgentMcpConfigRequest = Message<"laelia.v1.UpdateAgentMcpConfigRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * mcp_servers is the full replacement set of enabled MCP server resource
   * names (mcpServers/{id}).
   *
   * @generated from field: repeated string mcp_servers = 2;
   */
  mcpServers: string[];
};

/**
 * Describes the message laelia.v1.UpdateAgentMcpConfigRequest.
 * Use `create(UpdateAgentMcpConfigRequestSchema)` to create a new message.
 */
export declare const UpdateAgentMcpConfigRequestSchema: GenMessage<UpdateAgentMcpConfigRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentProvidersRequest
 */
export declare type RefreshAgentProvidersRequest = Message<"laelia.v1.RefreshAgentProvidersRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.RefreshAgentProvidersRequest.
 * Use `create(RefreshAgentProvidersRequestSchema)` to create a new message.
 */
export declare const RefreshAgentProvidersRequestSchema: GenMessage<RefreshAgentProvidersRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentProvidersResponse
 */
export declare type RefreshAgentProvidersResponse = Message<"laelia.v1.RefreshAgentProvidersResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.AgentProviderInfo providers = 1;
   */
  providers: AgentProviderInfo[];
};

/**
 * Describes the message laelia.v1.RefreshAgentProvidersResponse.
 * Use `create(RefreshAgentProvidersResponseSchema)` to create a new message.
 */
export declare const RefreshAgentProvidersResponseSchema: GenMessage<RefreshAgentProvidersResponse>;

/**
 * WorkspaceEntry is one file/directory node of a lazily loaded workspace tree.
 *
 * @generated from message laelia.v1.WorkspaceEntry
 */
export declare type WorkspaceEntry = Message<"laelia.v1.WorkspaceEntry"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * relative to the workspace root
   *
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: bool is_directory = 3;
   */
  isDirectory: boolean;

  /**
   * file bytes; 0 for directories
   *
   * @generated from field: int64 size = 4;
   */
  size: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp modified_at = 5;
   */
  modifiedAt?: Timestamp | undefined;

  /**
   * dotfile
   *
   * @generated from field: bool is_hidden = 6;
   */
  isHidden: boolean;
};

/**
 * Describes the message laelia.v1.WorkspaceEntry.
 * Use `create(WorkspaceEntrySchema)` to create a new message.
 */
export declare const WorkspaceEntrySchema: GenMessage<WorkspaceEntry>;

/**
 * WorkspaceReadResponse carries a previewed file (or an error) from the machine
 * app back to the manager. A non-empty error means the file cannot be
 * previewed; the unary RPC still succeeds so the frontend can show the reason.
 * Shared by the per-agent workspace stream (command.proto) and the unary
 * ReadAgentWorkspaceFile RPC.
 *
 * @generated from message laelia.v1.WorkspaceReadResponse
 */
export declare type WorkspaceReadResponse = Message<"laelia.v1.WorkspaceReadResponse"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * text: utf-8; image: base64; otherwise empty
   *
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * true for images and other binary files
   *
   * @generated from field: bool binary = 3;
   */
  binary: boolean;

  /**
   * @generated from field: int64 size = 4;
   */
  size: bigint;

  /**
   * set for images
   *
   * @generated from field: string mime_type = 5;
   */
  mimeType: string;

  /**
   * "utf-8" / "base64" / ""
   *
   * @generated from field: string encoding = 6;
   */
  encoding: string;

  /**
   * preview-disabled reason (sensitive file, too large, missing)
   *
   * @generated from field: string error = 7;
   */
  error: string;
};

/**
 * Describes the message laelia.v1.WorkspaceReadResponse.
 * Use `create(WorkspaceReadResponseSchema)` to create a new message.
 */
export declare const WorkspaceReadResponseSchema: GenMessage<WorkspaceReadResponse>;

/**
 * @generated from message laelia.v1.ListAgentWorkspaceRequest
 */
export declare type ListAgentWorkspaceRequest = Message<"laelia.v1.ListAgentWorkspaceRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * relative to the workspace root; empty = root
   *
   * @generated from field: string dir_path = 2;
   */
  dirPath: string;

  /**
   * @generated from field: bool include_hidden = 3;
   */
  includeHidden: boolean;
};

/**
 * Describes the message laelia.v1.ListAgentWorkspaceRequest.
 * Use `create(ListAgentWorkspaceRequestSchema)` to create a new message.
 */
export declare const ListAgentWorkspaceRequestSchema: GenMessage<ListAgentWorkspaceRequest>;

/**
 * @generated from message laelia.v1.ListAgentWorkspaceResponse
 */
export declare type ListAgentWorkspaceResponse = Message<"laelia.v1.ListAgentWorkspaceResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.WorkspaceEntry entries = 1;
   */
  entries: WorkspaceEntry[];
};

/**
 * Describes the message laelia.v1.ListAgentWorkspaceResponse.
 * Use `create(ListAgentWorkspaceResponseSchema)` to create a new message.
 */
export declare const ListAgentWorkspaceResponseSchema: GenMessage<ListAgentWorkspaceResponse>;

/**
 * @generated from message laelia.v1.ReadAgentWorkspaceFileRequest
 */
export declare type ReadAgentWorkspaceFileRequest = Message<"laelia.v1.ReadAgentWorkspaceFileRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * relative to the workspace root
   *
   * @generated from field: string path = 2;
   */
  path: string;
};

/**
 * Describes the message laelia.v1.ReadAgentWorkspaceFileRequest.
 * Use `create(ReadAgentWorkspaceFileRequestSchema)` to create a new message.
 */
export declare const ReadAgentWorkspaceFileRequestSchema: GenMessage<ReadAgentWorkspaceFileRequest>;

/**
 * @generated from message laelia.v1.ReadAgentWorkspaceFileResponse
 */
export declare type ReadAgentWorkspaceFileResponse = Message<"laelia.v1.ReadAgentWorkspaceFileResponse"> & {
  /**
   * @generated from field: laelia.v1.WorkspaceReadResponse file = 1;
   */
  file?: WorkspaceReadResponse | undefined;
};

/**
 * Describes the message laelia.v1.ReadAgentWorkspaceFileResponse.
 * Use `create(ReadAgentWorkspaceFileResponseSchema)` to create a new message.
 */
export declare const ReadAgentWorkspaceFileResponseSchema: GenMessage<ReadAgentWorkspaceFileResponse>;

/**
 * @generated from message laelia.v1.ListPiModelsRequest
 */
export declare type ListPiModelsRequest = Message<"laelia.v1.ListPiModelsRequest"> & {
  /**
   * LLM API provider id ("deepseek" | "openrouter" | "custom"). See AgentACPConfig.api_provider.
   *
   * @generated from field: string api_provider = 1;
   */
  apiProvider: string;

  /**
   * Plaintext LLM API key. Required for deepseek and custom; ignored (public endpoint) for openrouter.
   *
   * @generated from field: string api_key = 2;
   */
  apiKey: string;

  /**
   * Custom API base URL. Required when api_provider == "custom".
   *
   * @generated from field: string api_base_url = 3;
   */
  apiBaseUrl: string;
};

/**
 * Describes the message laelia.v1.ListPiModelsRequest.
 * Use `create(ListPiModelsRequestSchema)` to create a new message.
 */
export declare const ListPiModelsRequestSchema: GenMessage<ListPiModelsRequest>;

/**
 * @generated from message laelia.v1.ListPiModelsResponse
 */
export declare type ListPiModelsResponse = Message<"laelia.v1.ListPiModelsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.PiModel models = 1;
   */
  models: PiModel[];
};

/**
 * Describes the message laelia.v1.ListPiModelsResponse.
 * Use `create(ListPiModelsResponseSchema)` to create a new message.
 */
export declare const ListPiModelsResponseSchema: GenMessage<ListPiModelsResponse>;

/**
 * PiModel is one model id returned by the LLM API provider's model-listing API.
 *
 * @generated from message laelia.v1.PiModel
 */
export declare type PiModel = Message<"laelia.v1.PiModel"> & {
  /**
   * model id, the value passed to pi --model
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * optional display name (deepseek echoes id; openrouter has a human-readable name)
   *
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.PiModel.
 * Use `create(PiModelSchema)` to create a new message.
 */
export declare const PiModelSchema: GenMessage<PiModel>;

/**
 * @generated from message laelia.v1.UploadAgentAvatarRequest
 */
export declare type UploadAgentAvatarRequest = Message<"laelia.v1.UploadAgentAvatarRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * @generated from field: string mime_type = 3;
   */
  mimeType: string;
};

/**
 * Describes the message laelia.v1.UploadAgentAvatarRequest.
 * Use `create(UploadAgentAvatarRequestSchema)` to create a new message.
 */
export declare const UploadAgentAvatarRequestSchema: GenMessage<UploadAgentAvatarRequest>;

/**
 * @generated from message laelia.v1.DownloadAgentAvatarRequest
 */
export declare type DownloadAgentAvatarRequest = Message<"laelia.v1.DownloadAgentAvatarRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DownloadAgentAvatarRequest.
 * Use `create(DownloadAgentAvatarRequestSchema)` to create a new message.
 */
export declare const DownloadAgentAvatarRequestSchema: GenMessage<DownloadAgentAvatarRequest>;

/**
 * @generated from message laelia.v1.DownloadAgentAvatarResponse
 */
export declare type DownloadAgentAvatarResponse = Message<"laelia.v1.DownloadAgentAvatarResponse"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * @generated from field: string mime_type = 2;
   */
  mimeType: string;

  /**
   * @generated from field: string etag = 3;
   */
  etag: string;
};

/**
 * Describes the message laelia.v1.DownloadAgentAvatarResponse.
 * Use `create(DownloadAgentAvatarResponseSchema)` to create a new message.
 */
export declare const DownloadAgentAvatarResponseSchema: GenMessage<DownloadAgentAvatarResponse>;

/**
 * @generated from message laelia.v1.DeleteAgentAvatarRequest
 */
export declare type DeleteAgentAvatarRequest = Message<"laelia.v1.DeleteAgentAvatarRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteAgentAvatarRequest.
 * Use `create(DeleteAgentAvatarRequestSchema)` to create a new message.
 */
export declare const DeleteAgentAvatarRequestSchema: GenMessage<DeleteAgentAvatarRequest>;

/**
 * @generated from message laelia.v1.HelloRequest
 */
export declare type HelloRequest = Message<"laelia.v1.HelloRequest"> & {
};

/**
 * Describes the message laelia.v1.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message laelia.v1.HelloResponse
 */
export declare type HelloResponse = Message<"laelia.v1.HelloResponse"> & {
  /**
   * @generated from field: int64 current_time = 1;
   */
  currentTime: bigint;

  /**
   * @generated from field: string server_version = 2;
   */
  serverVersion: string;
};

/**
 * Describes the message laelia.v1.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export declare const HelloResponseSchema: GenMessage<HelloResponse>;

/**
 * @generated from message laelia.v1.Agent
 */
export declare type Agent = Message<"laelia.v1.Agent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * handle is the agent's human-readable, unique mention id (e.g.
   * "rei-agent-1"), generated at creation and immutable thereafter. It is the
   * {agent} segment of name ("agents/{handle}"), the value an agent types after
   * "@" to mention or DM this agent, and the name of its workspace directory
   * (~/.laelia/<machine>/<handle>/). Always populated; mirror of
   * agent.resource_id.
   *
   * @generated from field: string handle = 22;
   */
  handle: string;

  /**
   * @generated from field: laelia.v1.State state = 2;
   */
  state: State;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * description is a short, public intro for this agent shown to other users
   * and agents (who this agent is, what it is responsible for, its role). It is
   * intentionally NOT injected into the agent's own prompt — persona_prompt is
   * the private self prompt that defines the agent to itself and is hidden from
   * non-owners/non-admins.
   *
   * @generated from field: string description = 24;
   */
  description: string;

  /**
   * @generated from field: laelia.v1.AgentInfo info = 5;
   */
  info?: AgentInfo | undefined;

  /**
   * @generated from field: laelia.v1.AgentStatus status = 6;
   */
  status?: AgentStatus | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: map<string, string> labels = 8;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: google.protobuf.Timestamp last_token_rotated_at = 9;
   */
  lastTokenRotatedAt?: Timestamp | undefined;

  /**
   * @generated from field: int32 token_version = 10;
   */
  tokenVersion: number;

  /**
   * Creator's user resource name (users/{id}); empty for legacy agents with no
   * recorded creator. Display-only: it never authorizes anything (the agent's
   * owner does). Immutable after creation.
   *
   * @generated from field: string created_by = 11;
   */
  createdBy: string;

  /**
   * can_edit reports whether the current caller may modify this agent: true for
   * the agent's owner and for workspace admins, false otherwise. Populated per
   * caller by GetAgent/ListAgents; not set on agent-daemon paths.
   *
   * @generated from field: bool can_edit = 12;
   */
  canEdit: boolean;

  /**
   * avatar is the resource name of the agent's uploaded avatar image, or empty
   * when the agent has not uploaded one (frontend renders a deterministic pixel
   * identicon seeded by the agent id). Format: agents/{agent}/avatar.
   *
   * @generated from field: string avatar = 13;
   */
  avatar: string;

  /**
   * machine is the resource name of the machine this agent is bound to
   * (machines/{machine}). Required on CreateAgent (the parent machine the agent
   * runs on) and immutable thereafter; an agent runs on exactly one machine,
   * and the machine app picks it up via the MachineChannel control stream.
   *
   * @generated from field: string machine = 14;
   */
  machine: string;

  /**
   * allow_add_to_channel controls whether other users may add this agent to a
   * channel. Default false: only the agent's owner or a workspace admin may add
   * it. When true, the normal channel-side rule (conversations.manage = channel
   * owner/admin) applies.
   *
   * @generated from field: bool allow_add_to_channel = 15;
   */
  allowAddToChannel: boolean;

  /**
   * Owner's user resource name (users/{id}); empty for legacy agents with no
   * recorded owner. The owner is the human responsible for the agent: only the
   * owner or a workspace admin may modify it, the owner may transfer ownership
   * to another user (TransferAgentOwnership), and non-owners' high-risk
   * requests to the agent require the owner's approval (see the agent prompt's
   * Ownership & Safety section). Defaults to the creator on CreateAgent and is
   * backfilled from created_by for existing agents.
   *
   * @generated from field: string owner = 16;
   */
  owner: string;

  /**
   * Owner's display name — the name the agent writes `dm:@<owner_name>` to when
   * requesting approval for a high-risk operation. Empty for legacy agents.
   *
   * @generated from field: string owner_name = 17;
   */
  ownerName: string;

  /**
   * follow_owner_permissions grants this agent read access to every channel (and
   * DM) its owner can read, without requiring the agent to be added as a member.
   * The agent can read and proactively join such channels; posting still
   * requires explicit membership. Default true: the agent acts within its
   * owner's channel visibility.
   *
   * @generated from field: bool follow_owner_permissions = 18;
   */
  followOwnerPermissions: boolean;

  /**
   * mcp_servers is the set of MCP server resource names (mcpServers/{id})
   * enabled on this agent. The manager resolves them into a tool catalog when
   * the agent starts; the machine never receives transport configuration.
   *
   * @generated from field: repeated string mcp_servers = 19;
   */
  mcpServers: string[];

  /**
   * can_manage_channel_members grants this agent the ability to add/remove
   * members in a channel where its owner is a channel Admin or Owner. This is
   * separate from follow_owner_permissions (which controls read visibility):
   * the agent acts on its owner's behalf for member management only — it never
   * inherits the owner's other manage powers (rename, delete, transfer, roles).
   * Default true.
   *
   * @generated from field: bool can_manage_channel_members = 20;
   */
  canManageChannelMembers: boolean;

  /**
   * enabled reports whether the agent is running. When false the agent has
   * been stopped (StopAgent): its machine runner is torn down and it does not
   * process session messages or run an LLM agent until StartAgent. Default
   * true.
   *
   * @generated from field: bool enabled = 23;
   */
  enabled: boolean;

  /**
   * machine_title is the display name (title) of the machine this agent is
   * bound to, resolved server-side by GetAgent so clients can render a
   * human-readable machine name without a second GetMachine round-trip (the
   * machine may be invisible to the caller, in which case GetMachine would
   * return NotFound). Empty when the machine is missing.
   *
   * @generated from field: string machine_title = 21;
   */
  machineTitle: string;
};

/**
 * Describes the message laelia.v1.Agent.
 * Use `create(AgentSchema)` to create a new message.
 */
export declare const AgentSchema: GenMessage<Agent>;

/**
 * AgentSummary is the lightweight list-view projection of an Agent returned by
 * ListAgents. It carries only the fields list/header views need: identity,
 * lifecycle state, connection status, and the provider/executable signal that
 * agentLifecycle() reads to classify an agent as ready/pending/offline. The
 * full Agent (available_providers, the rest of acp_config, capability, host
 * info, token fields, created_by, can_edit) is returned only by GetAgent, so
 * the two RPCs don't overlap. can_edit is intentionally omitted: resolving it
 * per row would N+1 the IAM policy lookup for non-admin callers. can_delete is
 * the cheap subset the list view gates its delete affordance on: the agent's
 * owner or a workspace-scope holder of laelia.agents.edit (per-agent policy
 * bindings are not consulted, so a custom role bound on the agent may still
 * delete server-side while the list hides the button).
 *
 * @generated from message laelia.v1.AgentSummary
 */
export declare type AgentSummary = Message<"laelia.v1.AgentSummary"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * handle is the agent's readable id ("rei-agent-1"), the {agent} segment of
   * name. See Agent.handle. Always populated.
   *
   * @generated from field: string handle = 14;
   */
  handle: string;

  /**
   * @generated from field: laelia.v1.State state = 2;
   */
  state: State;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * description is the public agent intro surfaced in list views, member
   * pickers, and rosters so other users/agents know what this agent is for.
   * See Agent.description.
   *
   * @generated from field: string description = 16;
   */
  description: string;

  /**
   * @generated from field: laelia.v1.AgentStatus status = 4;
   */
  status?: AgentStatus | undefined;

  /**
   * provider/executable mirror acp_config.provider/executable on the full
   * Agent, surfaced top-level so list consumers don't pull in AgentInfo.
   *
   * @generated from field: string provider = 5;
   */
  provider: string;

  /**
   * @generated from field: string executable = 6;
   */
  executable: string;

  /**
   * machine is the resource name of the machine this agent is bound to
   * (machines/{machine}).
   *
   * @generated from field: string machine = 7;
   */
  machine: string;

  /**
   * created_by is the creator's user resource name (users/{id}); empty for
   * legacy agents with no recorded creator. Display-only — grouping and
   * authorization use owner. Surfaced on the summary so list consumers can
   * show the creator without an N+1 of GetAgent.
   *
   * @generated from field: string created_by = 8;
   */
  createdBy: string;

  /**
   * allow_add_to_channel mirrors Agent.allow_add_to_channel so list consumers
   * (e.g. the channel member picker) can hide agents the current caller may
   * not add.
   *
   * @generated from field: bool allow_add_to_channel = 9;
   */
  allowAddToChannel: boolean;

  /**
   * owner is the owner's user resource name (users/{id}); empty for legacy
   * agents with no recorded owner. Surfaced on the summary so list consumers
   * (e.g. the Members page's per-user "Owned Agents" view and the channel
   * member picker) can group agents by owner without an N+1 of GetAgent.
   *
   * @generated from field: string owner = 10;
   */
  owner: string;

  /**
   * follow_owner_permissions mirrors Agent.follow_owner_permissions so list
   * consumers can show whether the agent follows its owner's channel access.
   *
   * @generated from field: bool follow_owner_permissions = 11;
   */
  followOwnerPermissions: boolean;

  /**
   * can_manage_channel_members mirrors Agent.can_manage_channel_members so list
   * consumers can show whether the agent may manage members on its owner's
   * behalf.
   *
   * @generated from field: bool can_manage_channel_members = 12;
   */
  canManageChannelMembers: boolean;

  /**
   * enabled reports whether the agent is running; mirrors Agent.enabled (see
   * there). False means the agent is stopped and processes no messages.
   *
   * @generated from field: bool enabled = 15;
   */
  enabled: boolean;
};

/**
 * Describes the message laelia.v1.AgentSummary.
 * Use `create(AgentSummarySchema)` to create a new message.
 */
export declare const AgentSummarySchema: GenMessage<AgentSummary>;

/**
 * @generated from message laelia.v1.AgentInfo
 */
export declare type AgentInfo = Message<"laelia.v1.AgentInfo"> & {
  /**
   * @generated from field: string agent_type = 1;
   */
  agentType: string;

  /**
   * @generated from field: string hostname = 2;
   */
  hostname: string;

  /**
   * @generated from field: string os = 3;
   */
  os: string;

  /**
   * @generated from field: string arch = 4;
   */
  arch: string;

  /**
   * @generated from field: string ip = 5;
   */
  ip: string;

  /**
   * @generated from field: string version = 6;
   */
  version: string;

  /**
   * @generated from field: map<string, string> labels = 7;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: laelia.v1.AgentCapability capability = 8;
   */
  capability?: AgentCapability | undefined;

  /**
   * LLM agent providers auto-discovered by the agent daemon (agent-owned, not overwritten by the server)
   *
   * @generated from field: repeated laelia.v1.AgentProviderInfo available_providers = 9;
   */
  availableProviders: AgentProviderInfo[];

  /**
   * @generated from field: laelia.v1.AgentACPConfig acp_config = 10;
   */
  acpConfig?: AgentACPConfig | undefined;
};

/**
 * Describes the message laelia.v1.AgentInfo.
 * Use `create(AgentInfoSchema)` to create a new message.
 */
export declare const AgentInfoSchema: GenMessage<AgentInfo>;

/**
 * AgentProviderInfo describes one LLM agent provider detected on the agent
 * daemon's host. Reported via ConnectAgent and refreshed on demand. The server
 * treats this as agent-owned: it preserves it across ConnectAgent/Update flows
 * the same way it preserves acp_config.
 *
 * @generated from message laelia.v1.AgentProviderInfo
 */
export declare type AgentProviderInfo = Message<"laelia.v1.AgentProviderInfo"> & {
  /**
   * e.g. "opencode", "claude-code"
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: string executable_path = 4;
   */
  executablePath: string;

  /**
   * empty when the provider does not advertise a model config option
   *
   * @generated from field: repeated laelia.v1.AgentModelOption models = 5;
   */
  models: AgentModelOption[];

  /**
   * whether probing observed a category=="model" config option
   *
   * @generated from field: bool supports_model_config_option = 6;
   */
  supportsModelConfigOption: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp detected_at = 7;
   */
  detectedAt?: Timestamp | undefined;

  /**
   * READY, BROKEN, QUARANTINED, UPDATE_AVAILABLE, DETECTED
   *
   * @generated from field: string runtime_status = 8;
   */
  runtimeStatus: string;

  /**
   * DETECTED, PROTOCOL_READY, FUNCTIONALLY_VERIFIED, FULL_LOOP_VERIFIED
   *
   * @generated from field: string compatibility_level = 9;
   */
  compatibilityLevel: string;

  /**
   * @generated from field: string failure_message = 10;
   */
  failureMessage: string;

  /**
   * @generated from field: string package_version = 11;
   */
  packageVersion: string;

  /**
   * @generated from field: string manifest_digest = 12;
   */
  manifestDigest: string;
};

/**
 * Describes the message laelia.v1.AgentProviderInfo.
 * Use `create(AgentProviderInfoSchema)` to create a new message.
 */
export declare const AgentProviderInfoSchema: GenMessage<AgentProviderInfo>;

/**
 * AgentModelOption is one model selectable via the ACP session config option
 * round trip. Value is the valueId the client sends to SetSessionConfigOption.
 *
 * @generated from message laelia.v1.AgentModelOption
 */
export declare type AgentModelOption = Message<"laelia.v1.AgentModelOption"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message laelia.v1.AgentModelOption.
 * Use `create(AgentModelOptionSchema)` to create a new message.
 */
export declare const AgentModelOptionSchema: GenMessage<AgentModelOption>;

/**
 * User-configurable ACP settings. Everything else (working dir, capabilities,
 * permissions) is derived from a built-in template, not set by the admin.
 *
 * @generated from message laelia.v1.AgentACPConfig
 */
export declare type AgentACPConfig = Message<"laelia.v1.AgentACPConfig"> & {
  /**
   * command to run, e.g. "npx". Only used when provider is "custom" or empty.
   *
   * @generated from field: string executable = 1;
   */
  executable: string;

  /**
   * args passed to executable, e.g. ["-y", "@agentclientprotocol/claude-agent-acp@latest"]
   *
   * @generated from field: repeated string args = 2;
   */
  args: string[];

  /**
   * env var names the child process may inherit
   *
   * @generated from field: repeated string allow_env = 3;
   */
  allowEnv: string[];

  /**
   * selected LLM agent provider id, e.g. "opencode", "claude-code", "custom", "builtin-pi"
   *
   * @generated from field: string provider = 4;
   */
  provider: string;

  /**
   * selected model valueId, matching an option advertised by the provider in NewSession ConfigOptions
   *
   * @generated from field: string model = 5;
   */
  model: string;

  /**
   * user-defined key-value env vars overlaid (and overriding) the inherited allow_env set
   *
   * @generated from field: map<string, string> custom_env = 6;
   */
  customEnv: { [key: string]: string };

  /**
   * admin-authored self-awareness prompt: personality, chat style, focus area. Empty = not loaded.
   *
   * @generated from field: string persona_prompt = 7;
   */
  personaPrompt: string;

  /**
   * api_provider is the LLM API provider for the built-in pi runtime ("deepseek" or "openrouter"
   * in phase 1). Only meaningful when provider == "builtin-pi"; ignored by ACP runtimes.
   *
   * @generated from field: string api_provider = 8;
   */
  apiProvider: string;

  /**
   * api_key is the plaintext LLM API key for the api_provider. Only meaningful when
   * provider == "builtin-pi"; ignored by ACP runtimes. Stored in the agent info JSONB with the
   * same plaintext-at-rest posture as custom_env. When global_provider is set, api_key is
   * ignored: the key is resolved server-side from the global provider's entry and never stored
   * in (nor returned with) the agent.
   *
   * @generated from field: string api_key = 9;
   */
  apiKey: string;

  /**
   * global_provider is the resource name of the global API provider this builtin-pi agent uses
   * ("apiProviders/{id}"). Only meaningful when provider == "builtin-pi". When set, the stored
   * config carries the provider/entry references instead of an inline api_provider/api_key; the
   * server resolves the concrete api_provider/api_key/model at the daemon boundary.
   *
   * @generated from field: string global_provider = 10;
   */
  globalProvider: string;

  /**
   * global_provider_entry is the resource name of the (key, model) entry within the global
   * provider, in the form "apiProviders/{id}/entries/{entry}". Only meaningful when
   * provider == "builtin-pi" and global_provider is set.
   *
   * @generated from field: string global_provider_entry = 11;
   */
  globalProviderEntry: string;

  /**
   * protocol declares the ACP protocol generation the provider speaks:
   * empty (inferred from the provider type), "acp-v1" (session protocol) or
   * "acp-v2" (thread protocol). Only meaningful for a "custom" provider: a
   * built-in provider's protocol is determined by its implementation.
   *
   * @generated from field: string protocol = 12;
   */
  protocol: string;

  /**
   * api_base_url is the custom LLM API base URL for the built-in pi runtime.
   * Only meaningful when provider == "builtin-pi" and api_provider == "custom";
   * ignored by ACP runtimes and by known (deepseek/openrouter) providers.
   *
   * @generated from field: string api_base_url = 13;
   */
  apiBaseUrl: string;
};

/**
 * Describes the message laelia.v1.AgentACPConfig.
 * Use `create(AgentACPConfigSchema)` to create a new message.
 */
export declare const AgentACPConfigSchema: GenMessage<AgentACPConfig>;

/**
 * @generated from message laelia.v1.AgentCapability
 */
export declare type AgentCapability = Message<"laelia.v1.AgentCapability"> & {
  /**
   * @generated from field: bool supports_acp = 1;
   */
  supportsAcp: boolean;

  /**
   * @generated from field: int32 max_timeout_seconds = 3;
   */
  maxTimeoutSeconds: number;

  /**
   * @generated from field: bool supports_diff = 4;
   */
  supportsDiff: boolean;

  /**
   * @generated from field: bool supports_raw_events = 5;
   */
  supportsRawEvents: boolean;

  /**
   * @generated from field: bool supports_tool_traces = 6;
   */
  supportsToolTraces: boolean;

  /**
   * @generated from field: int32 max_event_count = 7;
   */
  maxEventCount: number;

  /**
   * @generated from field: int64 max_output_bytes = 8;
   */
  maxOutputBytes: bigint;

  /**
   * @generated from field: bool supports_autonomous_decision = 9;
   */
  supportsAutonomousDecision: boolean;

  /**
   * supports_pi is true for agents backed by the built-in non-ACP pi runtime. The dispatcher's
   * BeginSession gate accepts either supports_acp or supports_pi so a pi agent can run drain
   * sessions without an ACP executor.
   *
   * @generated from field: bool supports_pi = 10;
   */
  supportsPi: boolean;
};

/**
 * Describes the message laelia.v1.AgentCapability.
 * Use `create(AgentCapabilitySchema)` to create a new message.
 */
export declare const AgentCapabilitySchema: GenMessage<AgentCapability>;

/**
 * @generated from message laelia.v1.AgentStatus
 */
export declare type AgentStatus = Message<"laelia.v1.AgentStatus"> & {
  /**
   * @generated from field: laelia.v1.AgentStatus.ConnectionState state = 1;
   */
  state: AgentStatus_ConnectionState;

  /**
   * @generated from field: google.protobuf.Timestamp last_heartbeat_time = 2;
   */
  lastHeartbeatTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp connected_time = 3;
   */
  connectedTime?: Timestamp | undefined;

  /**
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;

  /**
   * current active session ID
   *
   * @generated from field: string active_session_id = 5;
   */
  activeSessionId: string;
};

/**
 * Describes the message laelia.v1.AgentStatus.
 * Use `create(AgentStatusSchema)` to create a new message.
 */
export declare const AgentStatusSchema: GenMessage<AgentStatus>;

/**
 * @generated from enum laelia.v1.AgentStatus.ConnectionState
 */
export enum AgentStatus_ConnectionState {
  /**
   * @generated from enum value: CONNECTION_STATE_UNSPECIFIED = 0;
   */
  CONNECTION_STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ONLINE = 1;
   */
  ONLINE = 1,

  /**
   * @generated from enum value: OFFLINE = 2;
   */
  OFFLINE = 2,

  /**
   * @generated from enum value: ERROR = 3;
   */
  ERROR = 3,

  /**
   * evicted by a new connection
   *
   * @generated from enum value: KICKED = 4;
   */
  KICKED = 4,

  /**
   * disabled via StopAgent; not processing sessions
   *
   * @generated from enum value: STOPPED = 5;
   */
  STOPPED = 5,
}

/**
 * Describes the enum laelia.v1.AgentStatus.ConnectionState.
 */
export declare const AgentStatus_ConnectionStateSchema: GenEnum<AgentStatus_ConnectionState>;

/**
 * @generated from message laelia.v1.AgentMetrics
 */
export declare type AgentMetrics = Message<"laelia.v1.AgentMetrics"> & {
  /**
   * @generated from field: double cpu_percent = 1;
   */
  cpuPercent: number;

  /**
   * @generated from field: uint64 memory_used_bytes = 2;
   */
  memoryUsedBytes: bigint;

  /**
   * @generated from field: uint64 memory_total_bytes = 3;
   */
  memoryTotalBytes: bigint;

  /**
   * @generated from field: uint64 disk_used_bytes = 4;
   */
  diskUsedBytes: bigint;

  /**
   * @generated from field: uint64 disk_total_bytes = 5;
   */
  diskTotalBytes: bigint;

  /**
   * @generated from field: uint32 uptime_seconds = 6;
   */
  uptimeSeconds: number;

  /**
   * @generated from field: uint32 goroutine_count = 7;
   */
  goroutineCount: number;
};

/**
 * Describes the message laelia.v1.AgentMetrics.
 * Use `create(AgentMetricsSchema)` to create a new message.
 */
export declare const AgentMetricsSchema: GenMessage<AgentMetrics>;

/**
 * ========== Management APIs (IAM auth, admin only) ==========
 *
 * @generated from service laelia.v1.AgentService
 */
export declare const AgentService: GenService<{
  /**
   * CreateAgent is handler-gated (no permission annotation): the machine's
   * creator, a workspace admin, or a principal bound to
   * roles/machineAgentCreator on the machine's IAM policy may create agents on
   * it. The machine-scoped check is enforced by the handler via
   * laelia.machines.createAgent against the machine's IAM policy.
   *
   * @generated from rpc laelia.v1.AgentService.CreateAgent
   */
  createAgent: {
    methodKind: "unary";
    input: typeof CreateAgentRequestSchema;
    output: typeof CreateAgentResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.AgentService.ListAgents
   */
  listAgents: {
    methodKind: "unary";
    input: typeof ListAgentsRequestSchema;
    output: typeof ListAgentsResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.AgentService.GetAgent
   */
  getAgent: {
    methodKind: "unary";
    input: typeof GetAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * UpdateAgent patches a single mutable agent field. Only allow_add_to_channel
   * is supported initially (any other update_mask path is rejected). Authorized
   * in the handler for the agent's owner or a workspace admin; the IAM
   * interceptor's agents.edit is admin-only, so this RPC carries no permission
   * annotation and is handler-gated.
   *
   * @generated from rpc laelia.v1.AgentService.UpdateAgent
   */
  updateAgent: {
    methodKind: "unary";
    input: typeof UpdateAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * TransferAgentOwnership reassigns the agent's owner to another user. The new
   * owner takes effect immediately and unilaterally (no acceptance required);
   * the previous owner loses owner authority at once. Authorized in the handler
   * for the agent's current owner or a workspace admin; like UpdateAgent this
   * RPC carries no permission annotation (agents.edit is admin-only) and is
   * handler-gated via canEditAgent.
   *
   * @generated from rpc laelia.v1.AgentService.TransferAgentOwnership
   */
  transferAgentOwnership: {
    methodKind: "unary";
    input: typeof TransferAgentOwnershipRequestSchema;
    output: typeof TransferAgentOwnershipResponseSchema;
  },
  /**
   * DeleteAgent soft-deletes an agent. Authorized in the handler for the
   * agent's owner or a holder of laelia.agents.edit on the agent; no
   * permission annotation so the owner short-circuit can run.
   *
   * @generated from rpc laelia.v1.AgentService.DeleteAgent
   */
  deleteAgent: {
    methodKind: "unary";
    input: typeof DeleteAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * StopAgent stops an agent: its machine runner is torn down and it no
   * longer processes session messages or runs an LLM agent until StartAgent.
   * The agent row is preserved (not deleted) and remains visible. Authorized
   * in the handler for the agent's owner or a holder of laelia.agents.edit.
   *
   * @generated from rpc laelia.v1.AgentService.StopAgent
   */
  stopAgent: {
    methodKind: "unary";
    input: typeof StopAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * StartAgent resumes a stopped agent: its machine runner is re-spawned and
   * it resumes processing session messages. No-op (still succeeds) if the
   * agent is already enabled. Authorized in the handler for the agent's owner
   * or a holder of laelia.agents.edit.
   *
   * @generated from rpc laelia.v1.AgentService.StartAgent
   */
  startAgent: {
    methodKind: "unary";
    input: typeof StartAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Token rotation: generate a new bootstrap token, old token invalid after
   * grace period. Authorized in the handler for the agent's owner or a holder
   * of laelia.agents.edit on the agent; no permission annotation so the owner
   * short-circuit can run.
   *
   * @generated from rpc laelia.v1.AgentService.RotateAgentToken
   */
  rotateAgentToken: {
    methodKind: "unary";
    input: typeof RotateAgentTokenRequestSchema;
    output: typeof RotateAgentTokenResponseSchema;
  },
  /**
   * Token revocation: revoke all tokens for the agent. Authorized in the
   * handler for the agent's owner or a holder of laelia.agents.edit on the
   * agent; no permission annotation so the owner short-circuit can run.
   *
   * @generated from rpc laelia.v1.AgentService.RevokeAgentToken
   */
  revokeAgentToken: {
    methodKind: "unary";
    input: typeof RevokeAgentTokenRequestSchema;
    output: typeof RevokeAgentTokenResponseSchema;
  },
  /**
   * Force-disconnects an agent connection. Authorized in the handler for the
   * agent's owner or a holder of laelia.agents.edit on the agent; no
   * permission annotation so the owner short-circuit can run.
   *
   * @generated from rpc laelia.v1.AgentService.ForceDisconnectAgent
   */
  forceDisconnectAgent: {
    methodKind: "unary";
    input: typeof ForceDisconnectAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * List agent sessions
   *
   * @generated from rpc laelia.v1.AgentService.ListAgentSessions
   */
  listAgentSessions: {
    methodKind: "unary";
    input: typeof ListAgentSessionsRequestSchema;
    output: typeof ListAgentSessionsResponseSchema;
  },
  /**
   * Update the agent's ACP config. Handler-gated (no permission annotation):
   * the agent's owner or a workspace admin may update it. Setting a legacy
   * inline api_provider/api_key additionally requires laelia.agents.edit (only
   * workspace admin today); owners without it must use a global provider.
   *
   * @generated from rpc laelia.v1.AgentService.UpdateAgentACPConfig
   */
  updateAgentACPConfig: {
    methodKind: "unary";
    input: typeof UpdateAgentACPConfigRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * UpdateAgentMcpConfig replaces the MCP servers enabled on an agent. Only
   * servers the caller may use (members of the server's user/group list, or
   * workspace admin) are accepted. Handler-gated like UpdateAgentACPConfig:
   * the agent's owner or a workspace admin may update it.
   *
   * @generated from rpc laelia.v1.AgentService.UpdateAgentMcpConfig
   */
  updateAgentMcpConfig: {
    methodKind: "unary";
    input: typeof UpdateAgentMcpConfigRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Ask the agent daemon to re-probe its host for installed LLM agent
   * providers and their models. Returns the freshly discovered provider list
   * (also persisted into agent.info.available_providers). Authorized in the
   * handler for the agent's owner or a holder of laelia.agents.edit on the
   * agent; no permission annotation so the owner short-circuit can run.
   *
   * @generated from rpc laelia.v1.AgentService.RefreshAgentProviders
   */
  refreshAgentProviders: {
    methodKind: "unary";
    input: typeof RefreshAgentProvidersRequestSchema;
    output: typeof RefreshAgentProvidersResponseSchema;
  },
  /**
   * ListAgentWorkspace lists one directory level of an agent's workspace on its
   * machine (~/.laelia/<machineID>/<agentID>/), lazily loading the tree level by
   * level. Workspace content is sensitive: authorized in the handler for the
   * agent's owner or a workspace admin (canEditAgent); like UpdateAgent this
   * RPC carries no permission annotation (agents.edit is admin-only) and is
   * handler-gated.
   *
   * @generated from rpc laelia.v1.AgentService.ListAgentWorkspace
   */
  listAgentWorkspace: {
    methodKind: "unary";
    input: typeof ListAgentWorkspaceRequestSchema;
    output: typeof ListAgentWorkspaceResponseSchema;
  },
  /**
   * ReadAgentWorkspaceFile reads a single workspace file for text/image preview.
   * Same handler-gated authorization as ListAgentWorkspace (owner or workspace
   * admin). Sensitive files (secret/credential/token patterns) are rejected by
   * the machine app and surface as a per-file error, not a transport error.
   *
   * @generated from rpc laelia.v1.AgentService.ReadAgentWorkspaceFile
   */
  readAgentWorkspaceFile: {
    methodKind: "unary";
    input: typeof ReadAgentWorkspaceFileRequestSchema;
    output: typeof ReadAgentWorkspaceFileResponseSchema;
  },
  /**
   * List the models a built-in pi agent's LLM API provider exposes. The manager
   * proxies the provider's model-listing HTTP API (DeepSeek `GET /models` with
   * the caller's api_key; OpenRouter `GET /models`, public) so the model list is
   * fetched dynamically rather than hardcoded. Not agent-scoped: the add-agent
   * form calls it before the agent exists. Admin (agents.edit) only.
   *
   * @generated from rpc laelia.v1.AgentService.ListPiModels
   */
  listPiModels: {
    methodKind: "unary";
    input: typeof ListPiModelsRequestSchema;
    output: typeof ListPiModelsResponseSchema;
  },
  /**
   * Agent initial connection using bootstrap token
   *
   * @generated from rpc laelia.v1.AgentService.ConnectAgent
   */
  connectAgent: {
    methodKind: "unary";
    input: typeof ConnectAgentRequestSchema;
    output: typeof ConnectAgentResponseSchema;
  },
  /**
   * Agent heartbeat
   *
   * @generated from rpc laelia.v1.AgentService.AgentHeartbeat
   */
  agentHeartbeat: {
    methodKind: "unary";
    input: typeof AgentHeartbeatRequestSchema;
    output: typeof AgentHeartbeatResponseSchema;
  },
  /**
   * Agent graceful disconnect
   *
   * @generated from rpc laelia.v1.AgentService.AgentDisconnect
   */
  agentDisconnect: {
    methodKind: "unary";
    input: typeof AgentDisconnectRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Agent refreshes access token
   *
   * @generated from rpc laelia.v1.AgentService.RefreshAgentToken
   */
  refreshAgentToken: {
    methodKind: "unary";
    input: typeof RefreshAgentTokenRequestSchema;
    output: typeof RefreshAgentTokenResponseSchema;
  },
  /**
   * UploadAgentAvatar replaces an agent's avatar image. Requires
   * laelia.agents.edit on the agent; the caller must be the agent's creator or a
   * workspace admin. Bytes travel over Connect-JSON.
   *
   * @generated from rpc laelia.v1.AgentService.UploadAgentAvatar
   */
  uploadAgentAvatar: {
    methodKind: "unary";
    input: typeof UploadAgentAvatarRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * DownloadAgentAvatar fetches an agent's avatar image bytes. Any authenticated
   * user may download any agent's avatar (workspace-internal profile image).
   *
   * @generated from rpc laelia.v1.AgentService.DownloadAgentAvatar
   */
  downloadAgentAvatar: {
    methodKind: "unary";
    input: typeof DownloadAgentAvatarRequestSchema;
    output: typeof DownloadAgentAvatarResponseSchema;
  },
  /**
   * DeleteAgentAvatar clears an agent's avatar, reverting to the pixel default.
   * Requires laelia.agents.edit on the agent.
   *
   * @generated from rpc laelia.v1.AgentService.DeleteAgentAvatar
   */
  deleteAgentAvatar: {
    methodKind: "unary";
    input: typeof DeleteAgentAvatarRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * Health check (no auth required)
   *
   * @generated from rpc laelia.v1.AgentService.Hello
   */
  hello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
}>;

