// @generated by protoc-gen-es v2.12.0
// @generated from file v1/annotation.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, extDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/annotation.proto.
 */
export const file_v1_annotation = /*@__PURE__*/
  fileDesc("ChN2MS9hbm5vdGF0aW9uLnByb3RvEglsYWVsaWEudjEqPgoKQXV0aE1ldGhvZBIbChdBVVRIX01FVEhPRF9VTlNQRUNJRklFRBAAEgcKA0lBTRABEgoKBkNVU1RPTRACOloKGGFsbG93X3dpdGhvdXRfY3JlZGVudGlhbBIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGKCNBiABKAhSFmFsbG93V2l0aG91dENyZWRlbnRpYWw6QAoKcGVybWlzc2lvbhIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGKGNBiABKAlSCnBlcm1pc3Npb246WAoLYXV0aF9tZXRob2QSHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxiijQYgASgOMhUubGFlbGlhLnYxLkF1dGhNZXRob2RSCmF1dGhNZXRob2Q6NgoFYXVkaXQSHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxijjQYgASgIUgVhdWRpdEI3WjVnaXRodWIuY29tL3RiZGF2aWQyMDE5Lzg4OGEyYS9iYWNrZW5kL2dlbmVyYXRlZC1nby92MWIGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * Describes the enum laelia.v1.AuthMethod.
 */
export const AuthMethodSchema = /*@__PURE__*/
  enumDesc(file_v1_annotation, 0);

/**
 * @generated from enum laelia.v1.AuthMethod
 */
export const AuthMethod = /*@__PURE__*/
  tsEnum(AuthMethodSchema);

/**
 * @generated from extension: bool allow_without_credential = 100000;
 */
export const allow_without_credential = /*@__PURE__*/
  extDesc(file_v1_annotation, 0);

/**
 * @generated from extension: string permission = 100001;
 */
export const permission = /*@__PURE__*/
  extDesc(file_v1_annotation, 1);

/**
 * @generated from extension: laelia.v1.AuthMethod auth_method = 100002;
 */
export const auth_method = /*@__PURE__*/
  extDesc(file_v1_annotation, 2);

/**
 * @generated from extension: bool audit = 100003;
 */
export const audit = /*@__PURE__*/
  extDesc(file_v1_annotation, 3);

