// @generated by protoc-gen-es v2.12.0
// @generated from file store/group.proto (package laelia.store, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file store/group.proto.
 */
export declare const file_store_group: GenFile;

/**
 * @generated from message laelia.store.GroupMember
 */
export declare type GroupMember = Message<"laelia.store.GroupMember"> & {
  /**
   * Member is the principal who belong to this group.
   *
   * Format: users/{userUID}.
   *
   * @generated from field: string member = 1;
   */
  member: string;

  /**
   * @generated from field: laelia.store.GroupMember.Role role = 2;
   */
  role: GroupMember_Role;
};

/**
 * Describes the message laelia.store.GroupMember.
 * Use `create(GroupMemberSchema)` to create a new message.
 */
export declare const GroupMemberSchema: GenMessage<GroupMember>;

/**
 * @generated from enum laelia.store.GroupMember.Role
 */
export enum GroupMember_Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  ROLE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: OWNER = 1;
   */
  OWNER = 1,

  /**
   * @generated from enum value: MEMBER = 2;
   */
  MEMBER = 2,
}

/**
 * Describes the enum laelia.store.GroupMember.Role.
 */
export declare const GroupMember_RoleSchema: GenEnum<GroupMember_Role>;

/**
 * @generated from message laelia.store.GroupPayload
 */
export declare type GroupPayload = Message<"laelia.store.GroupPayload"> & {
  /**
   * @generated from field: repeated laelia.store.GroupMember members = 1;
   */
  members: GroupMember[];

  /**
   * source means where the group comes from. For now we support Entra ID SCIM sync, so the source could be Entra ID.
   *
   * @generated from field: string source = 2;
   */
  source: string;
};

/**
 * Describes the message laelia.store.GroupPayload.
 * Use `create(GroupPayloadSchema)` to create a new message.
 */
export declare const GroupPayloadSchema: GenMessage<GroupPayload>;

