// @generated by protoc-gen-es v2.12.0
// @generated from file store/user.proto (package laelia.store, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file store/user.proto.
 */
export declare const file_store_user: GenFile;

/**
 * @generated from message laelia.store.UserProfile
 */
export declare type UserProfile = Message<"laelia.store.UserProfile"> & {
  /**
   * @generated from field: google.protobuf.Timestamp last_login_time = 1;
   */
  lastLoginTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp last_change_password_time = 2;
   */
  lastChangePasswordTime?: Timestamp | undefined;

  /**
   * source means where the user comes from. For now we support Entra ID SCIM sync, so the source could be Entra ID.
   *
   * @generated from field: string source = 3;
   */
  source: string;
};

/**
 * Describes the message laelia.store.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export declare const UserProfileSchema: GenMessage<UserProfile>;

/**
 * ChatPreferences mirrors laelia.v1.ChatPreferences. Stored as jsonb on the
 * principal row; a NULL/absent value means "use the default" (enter_to_send
 * true), so a nil pointer in the store layer signals "unset".
 *
 * @generated from message laelia.store.ChatPreferences
 */
export declare type ChatPreferences = Message<"laelia.store.ChatPreferences"> & {
  /**
   * @generated from field: bool enter_to_send = 1;
   */
  enterToSend: boolean;

  /**
   * @generated from field: laelia.store.PreferredLanguage preferred_language = 2;
   */
  preferredLanguage: PreferredLanguage;
};

/**
 * Describes the message laelia.store.ChatPreferences.
 * Use `create(ChatPreferencesSchema)` to create a new message.
 */
export declare const ChatPreferencesSchema: GenMessage<ChatPreferences>;

/**
 * PrincipalType is the type of a principal.
 *
 * @generated from enum laelia.store.PrincipalType
 */
export enum PrincipalType {
  /**
   * @generated from enum value: PRINCIPAL_TYPE_UNSPECIFIED = 0;
   */
  PRINCIPAL_TYPE_UNSPECIFIED = 0,

  /**
   * END_USER represents the human being.
   *
   * @generated from enum value: END_USER = 1;
   */
  END_USER = 1,

  /**
   * SERVICE_ACCOUNT represents the external service calling OpenAPI.
   *
   * @generated from enum value: SERVICE_ACCOUNT = 2;
   */
  SERVICE_ACCOUNT = 2,

  /**
   * SYSTEM_BOT represents the internal system bot performing operations.
   *
   * @generated from enum value: SYSTEM_BOT = 3;
   */
  SYSTEM_BOT = 3,
}

/**
 * Describes the enum laelia.store.PrincipalType.
 */
export declare const PrincipalTypeSchema: GenEnum<PrincipalType>;

/**
 * PreferredLanguage mirrors laelia.v1.PreferredLanguage.
 *
 * @generated from enum laelia.store.PreferredLanguage
 */
export enum PreferredLanguage {
  /**
   * @generated from enum value: PREFERRED_LANGUAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PREFERRED_LANGUAGE_ZH_CN = 1;
   */
  ZH_CN = 1,

  /**
   * @generated from enum value: PREFERRED_LANGUAGE_EN_US = 2;
   */
  EN_US = 2,

  /**
   * @generated from enum value: PREFERRED_LANGUAGE_JA_JP = 3;
   */
  JA_JP = 3,
}

/**
 * Describes the enum laelia.store.PreferredLanguage.
 */
export declare const PreferredLanguageSchema: GenEnum<PreferredLanguage>;

