// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: a2a888/agent_runtime.proto

package a2a888

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeKind int32

const (
	RuntimeKind_RUNTIME_KIND_UNSPECIFIED RuntimeKind = 0
	RuntimeKind_SYSTEM_EXECUTABLE        RuntimeKind = 1
	RuntimeKind_NPM_PACKAGE              RuntimeKind = 2
	RuntimeKind_EMBEDDED                 RuntimeKind = 3
	RuntimeKind_CUSTOM_RUNTIME           RuntimeKind = 4
)

// Enum value maps for RuntimeKind.
var (
	RuntimeKind_name = map[int32]string{
		0: "RUNTIME_KIND_UNSPECIFIED",
		1: "SYSTEM_EXECUTABLE",
		2: "NPM_PACKAGE",
		3: "EMBEDDED",
		4: "CUSTOM_RUNTIME",
	}
	RuntimeKind_value = map[string]int32{
		"RUNTIME_KIND_UNSPECIFIED": 0,
		"SYSTEM_EXECUTABLE":        1,
		"NPM_PACKAGE":              2,
		"EMBEDDED":                 3,
		"CUSTOM_RUNTIME":           4,
	}
)

func (x RuntimeKind) Enum() *RuntimeKind {
	p := new(RuntimeKind)
	*p = x
	return p
}

func (x RuntimeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_agent_runtime_proto_enumTypes[0].Descriptor()
}

func (RuntimeKind) Type() protoreflect.EnumType {
	return &file_a2a888_agent_runtime_proto_enumTypes[0]
}

func (x RuntimeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeKind.Descriptor instead.
func (RuntimeKind) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{0}
}

type AgentProtocol int32

const (
	AgentProtocol_AGENT_PROTOCOL_UNSPECIFIED AgentProtocol = 0
	AgentProtocol_ACP_V1                     AgentProtocol = 1
	AgentProtocol_ACP_V2                     AgentProtocol = 2
	AgentProtocol_A2A                        AgentProtocol = 3
	AgentProtocol_CUSTOM_PROTOCOL            AgentProtocol = 4
)

// Enum value maps for AgentProtocol.
var (
	AgentProtocol_name = map[int32]string{
		0: "AGENT_PROTOCOL_UNSPECIFIED",
		1: "ACP_V1",
		2: "ACP_V2",
		3: "A2A",
		4: "CUSTOM_PROTOCOL",
	}
	AgentProtocol_value = map[string]int32{
		"AGENT_PROTOCOL_UNSPECIFIED": 0,
		"ACP_V1":                     1,
		"ACP_V2":                     2,
		"A2A":                        3,
		"CUSTOM_PROTOCOL":            4,
	}
)

func (x AgentProtocol) Enum() *AgentProtocol {
	p := new(AgentProtocol)
	*p = x
	return p
}

func (x AgentProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_agent_runtime_proto_enumTypes[1].Descriptor()
}

func (AgentProtocol) Type() protoreflect.EnumType {
	return &file_a2a888_agent_runtime_proto_enumTypes[1]
}

func (x AgentProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentProtocol.Descriptor instead.
func (AgentProtocol) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{1}
}

type SessionMode int32

const (
	SessionMode_SESSION_MODE_UNSPECIFIED SessionMode = 0
	SessionMode_EPHEMERAL                SessionMode = 1
	SessionMode_PERSISTENT               SessionMode = 2
)

// Enum value maps for SessionMode.
var (
	SessionMode_name = map[int32]string{
		0: "SESSION_MODE_UNSPECIFIED",
		1: "EPHEMERAL",
		2: "PERSISTENT",
	}
	SessionMode_value = map[string]int32{
		"SESSION_MODE_UNSPECIFIED": 0,
		"EPHEMERAL":                1,
		"PERSISTENT":               2,
	}
)

func (x SessionMode) Enum() *SessionMode {
	p := new(SessionMode)
	*p = x
	return p
}

func (x SessionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_agent_runtime_proto_enumTypes[2].Descriptor()
}

func (SessionMode) Type() protoreflect.EnumType {
	return &file_a2a888_agent_runtime_proto_enumTypes[2]
}

func (x SessionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMode.Descriptor instead.
func (SessionMode) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{2}
}

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED RuntimeState = 0
	RuntimeState_UNAVAILABLE               RuntimeState = 1
	RuntimeState_INSTALLING                RuntimeState = 2
	RuntimeState_VERIFYING                 RuntimeState = 3
	RuntimeState_READY                     RuntimeState = 4
	RuntimeState_BROKEN                    RuntimeState = 5
	RuntimeState_QUARANTINED               RuntimeState = 6
	RuntimeState_UPDATE_AVAILABLE          RuntimeState = 7
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "UNAVAILABLE",
		2: "INSTALLING",
		3: "VERIFYING",
		4: "READY",
		5: "BROKEN",
		6: "QUARANTINED",
		7: "UPDATE_AVAILABLE",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED": 0,
		"UNAVAILABLE":               1,
		"INSTALLING":                2,
		"VERIFYING":                 3,
		"READY":                     4,
		"BROKEN":                    5,
		"QUARANTINED":               6,
		"UPDATE_AVAILABLE":          7,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_agent_runtime_proto_enumTypes[3].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_a2a888_agent_runtime_proto_enumTypes[3]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{3}
}

type CompatibilityLevel int32

const (
	CompatibilityLevel_COMPATIBILITY_LEVEL_UNSPECIFIED CompatibilityLevel = 0
	CompatibilityLevel_DETECTED                        CompatibilityLevel = 1
	CompatibilityLevel_PROTOCOL_READY                  CompatibilityLevel = 2
	CompatibilityLevel_FUNCTIONALLY_VERIFIED           CompatibilityLevel = 3
	CompatibilityLevel_FULL_LOOP_VERIFIED              CompatibilityLevel = 4
)

// Enum value maps for CompatibilityLevel.
var (
	CompatibilityLevel_name = map[int32]string{
		0: "COMPATIBILITY_LEVEL_UNSPECIFIED",
		1: "DETECTED",
		2: "PROTOCOL_READY",
		3: "FUNCTIONALLY_VERIFIED",
		4: "FULL_LOOP_VERIFIED",
	}
	CompatibilityLevel_value = map[string]int32{
		"COMPATIBILITY_LEVEL_UNSPECIFIED": 0,
		"DETECTED":                        1,
		"PROTOCOL_READY":                  2,
		"FUNCTIONALLY_VERIFIED":           3,
		"FULL_LOOP_VERIFIED":              4,
	}
)

func (x CompatibilityLevel) Enum() *CompatibilityLevel {
	p := new(CompatibilityLevel)
	*p = x
	return p
}

func (x CompatibilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompatibilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_agent_runtime_proto_enumTypes[4].Descriptor()
}

func (CompatibilityLevel) Type() protoreflect.EnumType {
	return &file_a2a888_agent_runtime_proto_enumTypes[4]
}

func (x CompatibilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompatibilityLevel.Descriptor instead.
func (CompatibilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{4}
}

// ProviderManifest describes how a provider runtime is identified, installed,
// started, and authorized on a supported platform.
type ProviderManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable provider identifier. Provider IDs are intentionally strings so that
	// providers can be added without changing this contract.
	ProviderId      string            `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DisplayName     string            `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RuntimeKind     RuntimeKind       `protobuf:"varint,3,opt,name=runtime_kind,json=runtimeKind,proto3,enum=a2a888.v1.RuntimeKind" json:"runtime_kind,omitempty"`
	AgentProtocol   AgentProtocol     `protobuf:"varint,4,opt,name=agent_protocol,json=agentProtocol,proto3,enum=a2a888.v1.AgentProtocol" json:"agent_protocol,omitempty"`
	PlatformTargets []*PlatformTarget `protobuf:"bytes,5,rep,name=platform_targets,json=platformTargets,proto3" json:"platform_targets,omitempty"`
	// Exactly one runtime configuration must be supplied.
	//
	// Types that are valid to be assigned to RuntimeConfig:
	//
	//	*ProviderManifest_SystemExecutable
	//	*ProviderManifest_NpmPackage
	//	*ProviderManifest_Embedded
	//	*ProviderManifest_Custom
	RuntimeConfig           isProviderManifest_RuntimeConfig `protobuf_oneof:"runtime_config"`
	Capabilities            *ProviderCapabilities            `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	PermissionProfile       *PermissionProfile               `protobuf:"bytes,9,opt,name=permission_profile,json=permissionProfile,proto3" json:"permission_profile,omitempty"`
	SessionBehavior         *SessionBehavior                 `protobuf:"bytes,10,opt,name=session_behavior,json=sessionBehavior,proto3" json:"session_behavior,omitempty"`
	ManifestVersion         string                           `protobuf:"bytes,11,opt,name=manifest_version,json=manifestVersion,proto3" json:"manifest_version,omitempty"`
	ManifestIntegritySha256 string                           `protobuf:"bytes,12,opt,name=manifest_integrity_sha256,json=manifestIntegritySha256,proto3" json:"manifest_integrity_sha256,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProviderManifest) Reset() {
	*x = ProviderManifest{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderManifest) ProtoMessage() {}

func (x *ProviderManifest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderManifest.ProtoReflect.Descriptor instead.
func (*ProviderManifest) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderManifest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderManifest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderManifest) GetRuntimeKind() RuntimeKind {
	if x != nil {
		return x.RuntimeKind
	}
	return RuntimeKind_RUNTIME_KIND_UNSPECIFIED
}

func (x *ProviderManifest) GetAgentProtocol() AgentProtocol {
	if x != nil {
		return x.AgentProtocol
	}
	return AgentProtocol_AGENT_PROTOCOL_UNSPECIFIED
}

func (x *ProviderManifest) GetPlatformTargets() []*PlatformTarget {
	if x != nil {
		return x.PlatformTargets
	}
	return nil
}

func (x *ProviderManifest) GetRuntimeConfig() isProviderManifest_RuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

func (x *ProviderManifest) GetSystemExecutable() *SystemExecutableConfig {
	if x != nil {
		if x, ok := x.RuntimeConfig.(*ProviderManifest_SystemExecutable); ok {
			return x.SystemExecutable
		}
	}
	return nil
}

func (x *ProviderManifest) GetNpmPackage() *NpmPackageConfig {
	if x != nil {
		if x, ok := x.RuntimeConfig.(*ProviderManifest_NpmPackage); ok {
			return x.NpmPackage
		}
	}
	return nil
}

func (x *ProviderManifest) GetEmbedded() *EmbeddedRuntimeConfig {
	if x != nil {
		if x, ok := x.RuntimeConfig.(*ProviderManifest_Embedded); ok {
			return x.Embedded
		}
	}
	return nil
}

func (x *ProviderManifest) GetCustom() *CustomRuntimeConfig {
	if x != nil {
		if x, ok := x.RuntimeConfig.(*ProviderManifest_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *ProviderManifest) GetCapabilities() *ProviderCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderManifest) GetPermissionProfile() *PermissionProfile {
	if x != nil {
		return x.PermissionProfile
	}
	return nil
}

func (x *ProviderManifest) GetSessionBehavior() *SessionBehavior {
	if x != nil {
		return x.SessionBehavior
	}
	return nil
}

func (x *ProviderManifest) GetManifestVersion() string {
	if x != nil {
		return x.ManifestVersion
	}
	return ""
}

func (x *ProviderManifest) GetManifestIntegritySha256() string {
	if x != nil {
		return x.ManifestIntegritySha256
	}
	return ""
}

type isProviderManifest_RuntimeConfig interface {
	isProviderManifest_RuntimeConfig()
}

type ProviderManifest_SystemExecutable struct {
	SystemExecutable *SystemExecutableConfig `protobuf:"bytes,6,opt,name=system_executable,json=systemExecutable,proto3,oneof"`
}

type ProviderManifest_NpmPackage struct {
	NpmPackage *NpmPackageConfig `protobuf:"bytes,7,opt,name=npm_package,json=npmPackage,proto3,oneof"`
}

type ProviderManifest_Embedded struct {
	Embedded *EmbeddedRuntimeConfig `protobuf:"bytes,13,opt,name=embedded,proto3,oneof"`
}

type ProviderManifest_Custom struct {
	Custom *CustomRuntimeConfig `protobuf:"bytes,14,opt,name=custom,proto3,oneof"`
}

func (*ProviderManifest_SystemExecutable) isProviderManifest_RuntimeConfig() {}

func (*ProviderManifest_NpmPackage) isProviderManifest_RuntimeConfig() {}

func (*ProviderManifest_Embedded) isProviderManifest_RuntimeConfig() {}

func (*ProviderManifest_Custom) isProviderManifest_RuntimeConfig() {}

// PlatformTarget uses normalized runtime platform names, such as linux,
// darwin, windows, amd64, arm64, and glibc.
type PlatformTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperatingSystem string                 `protobuf:"bytes,1,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Architecture    string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Libc            string                 `protobuf:"bytes,3,opt,name=libc,proto3" json:"libc,omitempty"`
	Variant         string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlatformTarget) Reset() {
	*x = PlatformTarget{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformTarget) ProtoMessage() {}

func (x *PlatformTarget) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformTarget.ProtoReflect.Descriptor instead.
func (*PlatformTarget) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformTarget) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *PlatformTarget) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *PlatformTarget) GetLibc() string {
	if x != nil {
		return x.Libc
	}
	return ""
}

func (x *PlatformTarget) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

// SystemExecutableConfig identifies an executable already installed or
// provided by the host operating system.
type SystemExecutableConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Executable      string                 `protobuf:"bytes,1,opt,name=executable,proto3" json:"executable,omitempty"`
	Arguments       []string               `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	VersionArgument string                 `protobuf:"bytes,3,opt,name=version_argument,json=versionArgument,proto3" json:"version_argument,omitempty"`
	VersionPattern  string                 `protobuf:"bytes,4,opt,name=version_pattern,json=versionPattern,proto3" json:"version_pattern,omitempty"`
	PackageManager  string                 `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	PackageName     string                 `protobuf:"bytes,6,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageVersion  string                 `protobuf:"bytes,7,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	IntegritySha256 string                 `protobuf:"bytes,8,opt,name=integrity_sha256,json=integritySha256,proto3" json:"integrity_sha256,omitempty"`
	// Names of host environment variables that may be inherited; values are
	// supplied by the runtime host and are never stored in the manifest.
	InheritedEnvironment []string `protobuf:"bytes,9,rep,name=inherited_environment,json=inheritedEnvironment,proto3" json:"inherited_environment,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SystemExecutableConfig) Reset() {
	*x = SystemExecutableConfig{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemExecutableConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemExecutableConfig) ProtoMessage() {}

func (x *SystemExecutableConfig) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemExecutableConfig.ProtoReflect.Descriptor instead.
func (*SystemExecutableConfig) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *SystemExecutableConfig) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *SystemExecutableConfig) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *SystemExecutableConfig) GetVersionArgument() string {
	if x != nil {
		return x.VersionArgument
	}
	return ""
}

func (x *SystemExecutableConfig) GetVersionPattern() string {
	if x != nil {
		return x.VersionPattern
	}
	return ""
}

func (x *SystemExecutableConfig) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *SystemExecutableConfig) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *SystemExecutableConfig) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *SystemExecutableConfig) GetIntegritySha256() string {
	if x != nil {
		return x.IntegritySha256
	}
	return ""
}

func (x *SystemExecutableConfig) GetInheritedEnvironment() []string {
	if x != nil {
		return x.InheritedEnvironment
	}
	return nil
}

// NpmPackageConfig pins every value needed to resolve an npm runtime.
type NpmPackageConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageName    string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageVersion string                 `protobuf:"bytes,2,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	Binary         string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	// Subresource Integrity (SRI) value for the exact package artifact.
	Integrity     string   `protobuf:"bytes,4,opt,name=integrity,proto3" json:"integrity,omitempty"`
	Registry      string   `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	Arguments     []string `protobuf:"bytes,6,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpmPackageConfig) Reset() {
	*x = NpmPackageConfig{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpmPackageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpmPackageConfig) ProtoMessage() {}

func (x *NpmPackageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpmPackageConfig.ProtoReflect.Descriptor instead.
func (*NpmPackageConfig) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *NpmPackageConfig) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *NpmPackageConfig) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *NpmPackageConfig) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *NpmPackageConfig) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

func (x *NpmPackageConfig) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *NpmPackageConfig) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// EmbeddedRuntimeConfig identifies a runtime shipped with the host service.
type EmbeddedRuntimeConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Artifact        string                 `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Binary          string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	IntegritySha256 string                 `protobuf:"bytes,4,opt,name=integrity_sha256,json=integritySha256,proto3" json:"integrity_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmbeddedRuntimeConfig) Reset() {
	*x = EmbeddedRuntimeConfig{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedRuntimeConfig) ProtoMessage() {}

func (x *EmbeddedRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedRuntimeConfig.ProtoReflect.Descriptor instead.
func (*EmbeddedRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddedRuntimeConfig) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *EmbeddedRuntimeConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EmbeddedRuntimeConfig) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *EmbeddedRuntimeConfig) GetIntegritySha256() string {
	if x != nil {
		return x.IntegritySha256
	}
	return ""
}

// CustomRuntimeConfig describes a provider-specific launch command.
type CustomRuntimeConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Command   string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Arguments []string               `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// Names of host environment variables that may be inherited; values are
	// supplied by the runtime host and are never stored in the manifest.
	InheritedEnvironment []string `protobuf:"bytes,3,rep,name=inherited_environment,json=inheritedEnvironment,proto3" json:"inherited_environment,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	IntegritySha256      string   `protobuf:"bytes,5,opt,name=integrity_sha256,json=integritySha256,proto3" json:"integrity_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CustomRuntimeConfig) Reset() {
	*x = CustomRuntimeConfig{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRuntimeConfig) ProtoMessage() {}

func (x *CustomRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRuntimeConfig.ProtoReflect.Descriptor instead.
func (*CustomRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *CustomRuntimeConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CustomRuntimeConfig) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CustomRuntimeConfig) GetInheritedEnvironment() []string {
	if x != nil {
		return x.InheritedEnvironment
	}
	return nil
}

func (x *CustomRuntimeConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomRuntimeConfig) GetIntegritySha256() string {
	if x != nil {
		return x.IntegritySha256
	}
	return ""
}

// ProviderCapabilities is a typed capability declaration for runtime
// discovery and session orchestration.
type ProviderCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelDiscovery bool                   `protobuf:"varint,1,opt,name=model_discovery,json=modelDiscovery,proto3" json:"model_discovery,omitempty"`
	SessionResume  bool                   `protobuf:"varint,2,opt,name=session_resume,json=sessionResume,proto3" json:"session_resume,omitempty"`
	Streaming      bool                   `protobuf:"varint,3,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Steering       bool                   `protobuf:"varint,4,opt,name=steering,proto3" json:"steering,omitempty"`
	Mcp            bool                   `protobuf:"varint,5,opt,name=mcp,proto3" json:"mcp,omitempty"`
	ToolTraces     bool                   `protobuf:"varint,6,opt,name=tool_traces,json=toolTraces,proto3" json:"tool_traces,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderCapabilities) GetModelDiscovery() bool {
	if x != nil {
		return x.ModelDiscovery
	}
	return false
}

func (x *ProviderCapabilities) GetSessionResume() bool {
	if x != nil {
		return x.SessionResume
	}
	return false
}

func (x *ProviderCapabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ProviderCapabilities) GetSteering() bool {
	if x != nil {
		return x.Steering
	}
	return false
}

func (x *ProviderCapabilities) GetMcp() bool {
	if x != nil {
		return x.Mcp
	}
	return false
}

func (x *ProviderCapabilities) GetToolTraces() bool {
	if x != nil {
		return x.ToolTraces
	}
	return false
}

// PermissionProfile records the least-privilege permissions requested by a
// runtime. Empty allowlists mean that the corresponding access is denied.
type PermissionProfile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProcessExecution     bool                   `protobuf:"varint,1,opt,name=process_execution,json=processExecution,proto3" json:"process_execution,omitempty"`
	InheritEnvironment   bool                   `protobuf:"varint,2,opt,name=inherit_environment,json=inheritEnvironment,proto3" json:"inherit_environment,omitempty"`
	FilesystemReadPaths  []string               `protobuf:"bytes,3,rep,name=filesystem_read_paths,json=filesystemReadPaths,proto3" json:"filesystem_read_paths,omitempty"`
	FilesystemWritePaths []string               `protobuf:"bytes,4,rep,name=filesystem_write_paths,json=filesystemWritePaths,proto3" json:"filesystem_write_paths,omitempty"`
	NetworkHosts         []string               `protobuf:"bytes,5,rep,name=network_hosts,json=networkHosts,proto3" json:"network_hosts,omitempty"`
	NetworkAccess        bool                   `protobuf:"varint,6,opt,name=network_access,json=networkAccess,proto3" json:"network_access,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PermissionProfile) Reset() {
	*x = PermissionProfile{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionProfile) ProtoMessage() {}

func (x *PermissionProfile) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionProfile.ProtoReflect.Descriptor instead.
func (*PermissionProfile) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *PermissionProfile) GetProcessExecution() bool {
	if x != nil {
		return x.ProcessExecution
	}
	return false
}

func (x *PermissionProfile) GetInheritEnvironment() bool {
	if x != nil {
		return x.InheritEnvironment
	}
	return false
}

func (x *PermissionProfile) GetFilesystemReadPaths() []string {
	if x != nil {
		return x.FilesystemReadPaths
	}
	return nil
}

func (x *PermissionProfile) GetFilesystemWritePaths() []string {
	if x != nil {
		return x.FilesystemWritePaths
	}
	return nil
}

func (x *PermissionProfile) GetNetworkHosts() []string {
	if x != nil {
		return x.NetworkHosts
	}
	return nil
}

func (x *PermissionProfile) GetNetworkAccess() bool {
	if x != nil {
		return x.NetworkAccess
	}
	return false
}

// SessionBehavior defines lifecycle and resume expectations for provider
// sessions.
type SessionBehavior struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Mode                       SessionMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=a2a888.v1.SessionMode" json:"mode,omitempty"`
	SupportsResume             bool                   `protobuf:"varint,2,opt,name=supports_resume,json=supportsResume,proto3" json:"supports_resume,omitempty"`
	SupportsConcurrentSessions bool                   `protobuf:"varint,3,opt,name=supports_concurrent_sessions,json=supportsConcurrentSessions,proto3" json:"supports_concurrent_sessions,omitempty"`
	IdleTimeoutSeconds         uint32                 `protobuf:"varint,4,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	RequiresCleanShutdown      bool                   `protobuf:"varint,5,opt,name=requires_clean_shutdown,json=requiresCleanShutdown,proto3" json:"requires_clean_shutdown,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SessionBehavior) Reset() {
	*x = SessionBehavior{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionBehavior) ProtoMessage() {}

func (x *SessionBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionBehavior.ProtoReflect.Descriptor instead.
func (*SessionBehavior) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *SessionBehavior) GetMode() SessionMode {
	if x != nil {
		return x.Mode
	}
	return SessionMode_SESSION_MODE_UNSPECIFIED
}

func (x *SessionBehavior) GetSupportsResume() bool {
	if x != nil {
		return x.SupportsResume
	}
	return false
}

func (x *SessionBehavior) GetSupportsConcurrentSessions() bool {
	if x != nil {
		return x.SupportsConcurrentSessions
	}
	return false
}

func (x *SessionBehavior) GetIdleTimeoutSeconds() uint32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *SessionBehavior) GetRequiresCleanShutdown() bool {
	if x != nil {
		return x.RequiresCleanShutdown
	}
	return false
}

// PreparedRuntime is the immutable result of resolving and verifying a
// ProviderManifest for one platform.
type PreparedRuntime struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderId     string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	CacheIdentity  *CacheIdentity         `protobuf:"bytes,2,opt,name=cache_identity,json=cacheIdentity,proto3" json:"cache_identity,omitempty"`
	ResolvedBinary *ResolvedBinary        `protobuf:"bytes,3,opt,name=resolved_binary,json=resolvedBinary,proto3" json:"resolved_binary,omitempty"`
	Status         *RuntimeStatus         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Compatibility  *CompatibilityReport   `protobuf:"bytes,5,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	PreparedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=prepared_at,json=preparedAt,proto3" json:"prepared_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreparedRuntime) Reset() {
	*x = PreparedRuntime{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedRuntime) ProtoMessage() {}

func (x *PreparedRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedRuntime.ProtoReflect.Descriptor instead.
func (*PreparedRuntime) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *PreparedRuntime) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *PreparedRuntime) GetCacheIdentity() *CacheIdentity {
	if x != nil {
		return x.CacheIdentity
	}
	return nil
}

func (x *PreparedRuntime) GetResolvedBinary() *ResolvedBinary {
	if x != nil {
		return x.ResolvedBinary
	}
	return nil
}

func (x *PreparedRuntime) GetStatus() *RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PreparedRuntime) GetCompatibility() *CompatibilityReport {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *PreparedRuntime) GetPreparedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PreparedAt
	}
	return nil
}

// CacheIdentity is content-addressed and must not change for the lifetime of a
// prepared runtime. A changed manifest or artifact creates a new identity.
type CacheIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityDigest string                 `protobuf:"bytes,1,opt,name=identity_digest,json=identityDigest,proto3" json:"identity_digest,omitempty"`
	ProviderId     string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,4,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	Platform       *PlatformTarget        `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	LockDigest     string                 `protobuf:"bytes,6,opt,name=lock_digest,json=lockDigest,proto3" json:"lock_digest,omitempty"`
	PackageName    string                 `protobuf:"bytes,7,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageVersion string                 `protobuf:"bytes,8,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	// SRI integrity value for package-backed runtimes.
	Integrity     string `protobuf:"bytes,9,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheIdentity) Reset() {
	*x = CacheIdentity{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheIdentity) ProtoMessage() {}

func (x *CacheIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheIdentity.ProtoReflect.Descriptor instead.
func (*CacheIdentity) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *CacheIdentity) GetIdentityDigest() string {
	if x != nil {
		return x.IdentityDigest
	}
	return ""
}

func (x *CacheIdentity) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CacheIdentity) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *CacheIdentity) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *CacheIdentity) GetPlatform() *PlatformTarget {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *CacheIdentity) GetLockDigest() string {
	if x != nil {
		return x.LockDigest
	}
	return ""
}

func (x *CacheIdentity) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *CacheIdentity) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *CacheIdentity) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

// ResolvedBinary identifies the exact executable selected for a prepared
// runtime, including its content digest.
type ResolvedBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Binary        string                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Arguments     []string               `protobuf:"bytes,7,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedBinary) Reset() {
	*x = ResolvedBinary{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedBinary) ProtoMessage() {}

func (x *ResolvedBinary) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedBinary.ProtoReflect.Descriptor instead.
func (*ResolvedBinary) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *ResolvedBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResolvedBinary) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *ResolvedBinary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedBinary) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ResolvedBinary) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResolvedBinary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResolvedBinary) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type RuntimeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           RuntimeState           `protobuf:"varint,1,opt,name=state,proto3,enum=a2a888.v1.RuntimeState" json:"state,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ObservedVersion string                 `protobuf:"bytes,3,opt,name=observed_version,json=observedVersion,proto3" json:"observed_version,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	FailureCode     string                 `protobuf:"bytes,5,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeStatus) Reset() {
	*x = RuntimeStatus{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatus) ProtoMessage() {}

func (x *RuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatus.ProtoReflect.Descriptor instead.
func (*RuntimeStatus) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *RuntimeStatus) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *RuntimeStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeStatus) GetObservedVersion() string {
	if x != nil {
		return x.ObservedVersion
	}
	return ""
}

func (x *RuntimeStatus) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *RuntimeStatus) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

// CompatibilityReport records the strongest verified compatibility level and
// the evidence that supports it.
type CompatibilityReport struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Level         CompatibilityLevel       `protobuf:"varint,1,opt,name=level,proto3,enum=a2a888.v1.CompatibilityLevel" json:"level,omitempty"`
	Evidence      []*CompatibilityEvidence `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatibilityReport) Reset() {
	*x = CompatibilityReport{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityReport) ProtoMessage() {}

func (x *CompatibilityReport) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityReport.ProtoReflect.Descriptor instead.
func (*CompatibilityReport) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *CompatibilityReport) GetLevel() CompatibilityLevel {
	if x != nil {
		return x.Level
	}
	return CompatibilityLevel_COMPATIBILITY_LEVEL_UNSPECIFIED
}

func (x *CompatibilityReport) GetEvidence() []*CompatibilityEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// CompatibilityEvidence is an auditable result from a detection or test run.
type CompatibilityEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Platform      *PlatformTarget        `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	TestedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=tested_at,json=testedAt,proto3" json:"tested_at,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatibilityEvidence) Reset() {
	*x = CompatibilityEvidence{}
	mi := &file_a2a888_agent_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityEvidence) ProtoMessage() {}

func (x *CompatibilityEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_agent_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityEvidence.ProtoReflect.Descriptor instead.
func (*CompatibilityEvidence) Descriptor() ([]byte, []int) {
	return file_a2a888_agent_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *CompatibilityEvidence) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CompatibilityEvidence) GetPlatform() *PlatformTarget {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *CompatibilityEvidence) GetTestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TestedAt
	}
	return nil
}

func (x *CompatibilityEvidence) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_a2a888_agent_runtime_proto protoreflect.FileDescriptor

const file_a2a888_agent_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1aa2a888/agent_runtime.proto\x12\ta2a888.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x06\n" +
	"\x10ProviderManifest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x129\n" +
	"\fruntime_kind\x18\x03 \x01(\x0e2\x16.a2a888.v1.RuntimeKindR\vruntimeKind\x12?\n" +
	"\x0eagent_protocol\x18\x04 \x01(\x0e2\x18.a2a888.v1.AgentProtocolR\ragentProtocol\x12D\n" +
	"\x10platform_targets\x18\x05 \x03(\v2\x19.a2a888.v1.PlatformTargetR\x0fplatformTargets\x12P\n" +
	"\x11system_executable\x18\x06 \x01(\v2!.a2a888.v1.SystemExecutableConfigH\x00R\x10systemExecutable\x12>\n" +
	"\vnpm_package\x18\a \x01(\v2\x1b.a2a888.v1.NpmPackageConfigH\x00R\n" +
	"npmPackage\x12>\n" +
	"\bembedded\x18\r \x01(\v2 .a2a888.v1.EmbeddedRuntimeConfigH\x00R\bembedded\x128\n" +
	"\x06custom\x18\x0e \x01(\v2\x1e.a2a888.v1.CustomRuntimeConfigH\x00R\x06custom\x12C\n" +
	"\fcapabilities\x18\b \x01(\v2\x1f.a2a888.v1.ProviderCapabilitiesR\fcapabilities\x12K\n" +
	"\x12permission_profile\x18\t \x01(\v2\x1c.a2a888.v1.PermissionProfileR\x11permissionProfile\x12E\n" +
	"\x10session_behavior\x18\n" +
	" \x01(\v2\x1a.a2a888.v1.SessionBehaviorR\x0fsessionBehavior\x12)\n" +
	"\x10manifest_version\x18\v \x01(\tR\x0fmanifestVersion\x12:\n" +
	"\x19manifest_integrity_sha256\x18\f \x01(\tR\x17manifestIntegritySha256B\x10\n" +
	"\x0eruntime_config\"\x8d\x01\n" +
	"\x0ePlatformTarget\x12)\n" +
	"\x10operating_system\x18\x01 \x01(\tR\x0foperatingSystem\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x12\n" +
	"\x04libc\x18\x03 \x01(\tR\x04libc\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\"\xff\x02\n" +
	"\x16SystemExecutableConfig\x12\x1e\n" +
	"\n" +
	"executable\x18\x01 \x01(\tR\n" +
	"executable\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\tR\targuments\x12)\n" +
	"\x10version_argument\x18\x03 \x01(\tR\x0fversionArgument\x12'\n" +
	"\x0fversion_pattern\x18\x04 \x01(\tR\x0eversionPattern\x12'\n" +
	"\x0fpackage_manager\x18\x05 \x01(\tR\x0epackageManager\x12!\n" +
	"\fpackage_name\x18\x06 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\a \x01(\tR\x0epackageVersion\x12)\n" +
	"\x10integrity_sha256\x18\b \x01(\tR\x0fintegritySha256\x123\n" +
	"\x15inherited_environment\x18\t \x03(\tR\x14inheritedEnvironment\"\xce\x01\n" +
	"\x10NpmPackageConfig\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x02 \x01(\tR\x0epackageVersion\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12\x1c\n" +
	"\tintegrity\x18\x04 \x01(\tR\tintegrity\x12\x1a\n" +
	"\bregistry\x18\x05 \x01(\tR\bregistry\x12\x1c\n" +
	"\targuments\x18\x06 \x03(\tR\targuments\"\x90\x01\n" +
	"\x15EmbeddedRuntimeConfig\x12\x1a\n" +
	"\bartifact\x18\x01 \x01(\tR\bartifact\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12)\n" +
	"\x10integrity_sha256\x18\x04 \x01(\tR\x0fintegritySha256\"\xc7\x01\n" +
	"\x13CustomRuntimeConfig\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\tR\targuments\x123\n" +
	"\x15inherited_environment\x18\x03 \x03(\tR\x14inheritedEnvironment\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12)\n" +
	"\x10integrity_sha256\x18\x05 \x01(\tR\x0fintegritySha256\"\xd3\x01\n" +
	"\x14ProviderCapabilities\x12'\n" +
	"\x0fmodel_discovery\x18\x01 \x01(\bR\x0emodelDiscovery\x12%\n" +
	"\x0esession_resume\x18\x02 \x01(\bR\rsessionResume\x12\x1c\n" +
	"\tstreaming\x18\x03 \x01(\bR\tstreaming\x12\x1a\n" +
	"\bsteering\x18\x04 \x01(\bR\bsteering\x12\x10\n" +
	"\x03mcp\x18\x05 \x01(\bR\x03mcp\x12\x1f\n" +
	"\vtool_traces\x18\x06 \x01(\bR\n" +
	"toolTraces\"\xa7\x02\n" +
	"\x11PermissionProfile\x12+\n" +
	"\x11process_execution\x18\x01 \x01(\bR\x10processExecution\x12/\n" +
	"\x13inherit_environment\x18\x02 \x01(\bR\x12inheritEnvironment\x122\n" +
	"\x15filesystem_read_paths\x18\x03 \x03(\tR\x13filesystemReadPaths\x124\n" +
	"\x16filesystem_write_paths\x18\x04 \x03(\tR\x14filesystemWritePaths\x12#\n" +
	"\rnetwork_hosts\x18\x05 \x03(\tR\fnetworkHosts\x12%\n" +
	"\x0enetwork_access\x18\x06 \x01(\bR\rnetworkAccess\"\x92\x02\n" +
	"\x0fSessionBehavior\x12*\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x16.a2a888.v1.SessionModeR\x04mode\x12'\n" +
	"\x0fsupports_resume\x18\x02 \x01(\bR\x0esupportsResume\x12@\n" +
	"\x1csupports_concurrent_sessions\x18\x03 \x01(\bR\x1asupportsConcurrentSessions\x120\n" +
	"\x14idle_timeout_seconds\x18\x04 \x01(\rR\x12idleTimeoutSeconds\x126\n" +
	"\x17requires_clean_shutdown\x18\x05 \x01(\bR\x15requiresCleanShutdown\"\xec\x02\n" +
	"\x0fPreparedRuntime\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12?\n" +
	"\x0ecache_identity\x18\x02 \x01(\v2\x18.a2a888.v1.CacheIdentityR\rcacheIdentity\x12B\n" +
	"\x0fresolved_binary\x18\x03 \x01(\v2\x19.a2a888.v1.ResolvedBinaryR\x0eresolvedBinary\x120\n" +
	"\x06status\x18\x04 \x01(\v2\x18.a2a888.v1.RuntimeStatusR\x06status\x12D\n" +
	"\rcompatibility\x18\x05 \x01(\v2\x1e.a2a888.v1.CompatibilityReportR\rcompatibility\x12;\n" +
	"\vprepared_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"preparedAt\"\xed\x02\n" +
	"\rCacheIdentity\x12'\n" +
	"\x0fidentity_digest\x18\x01 \x01(\tR\x0eidentityDigest\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\x12'\n" +
	"\x0fruntime_version\x18\x04 \x01(\tR\x0eruntimeVersion\x125\n" +
	"\bplatform\x18\x05 \x01(\v2\x19.a2a888.v1.PlatformTargetR\bplatform\x12\x1f\n" +
	"\vlock_digest\x18\x06 \x01(\tR\n" +
	"lockDigest\x12!\n" +
	"\fpackage_name\x18\a \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\b \x01(\tR\x0epackageVersion\x12\x1c\n" +
	"\tintegrity\x18\t \x01(\tR\tintegrity\"\xc3\x01\n" +
	"\x0eResolvedBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\tR\x06binary\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1c\n" +
	"\targuments\x18\a \x03(\tR\targuments\"\xe3\x01\n" +
	"\rRuntimeStatus\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.a2a888.v1.RuntimeStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10observed_version\x18\x03 \x01(\tR\x0fobservedVersion\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12!\n" +
	"\ffailure_code\x18\x05 \x01(\tR\vfailureCode\"\x88\x01\n" +
	"\x13CompatibilityReport\x123\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1d.a2a888.v1.CompatibilityLevelR\x05level\x12<\n" +
	"\bevidence\x18\x02 \x03(\v2 .a2a888.v1.CompatibilityEvidenceR\bevidence\"\xbb\x01\n" +
	"\x15CompatibilityEvidence\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x125\n" +
	"\bplatform\x18\x02 \x01(\v2\x19.a2a888.v1.PlatformTargetR\bplatform\x127\n" +
	"\ttested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\btestedAt\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails*u\n" +
	"\vRuntimeKind\x12\x1c\n" +
	"\x18RUNTIME_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SYSTEM_EXECUTABLE\x10\x01\x12\x0f\n" +
	"\vNPM_PACKAGE\x10\x02\x12\f\n" +
	"\bEMBEDDED\x10\x03\x12\x12\n" +
	"\x0eCUSTOM_RUNTIME\x10\x04*e\n" +
	"\rAgentProtocol\x12\x1e\n" +
	"\x1aAGENT_PROTOCOL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACP_V1\x10\x01\x12\n" +
	"\n" +
	"\x06ACP_V2\x10\x02\x12\a\n" +
	"\x03A2A\x10\x03\x12\x13\n" +
	"\x0fCUSTOM_PROTOCOL\x10\x04*J\n" +
	"\vSessionMode\x12\x1c\n" +
	"\x18SESSION_MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tEPHEMERAL\x10\x01\x12\x0e\n" +
	"\n" +
	"PERSISTENT\x10\x02*\x9b\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x01\x12\x0e\n" +
	"\n" +
	"INSTALLING\x10\x02\x12\r\n" +
	"\tVERIFYING\x10\x03\x12\t\n" +
	"\x05READY\x10\x04\x12\n" +
	"\n" +
	"\x06BROKEN\x10\x05\x12\x0f\n" +
	"\vQUARANTINED\x10\x06\x12\x14\n" +
	"\x10UPDATE_AVAILABLE\x10\a*\x8e\x01\n" +
	"\x12CompatibilityLevel\x12#\n" +
	"\x1fCOMPATIBILITY_LEVEL_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bDETECTED\x10\x01\x12\x12\n" +
	"\x0ePROTOCOL_READY\x10\x02\x12\x19\n" +
	"\x15FUNCTIONALLY_VERIFIED\x10\x03\x12\x16\n" +
	"\x12FULL_LOOP_VERIFIED\x10\x04B;Z9github.com/tbdavid2019/888a2a/backend/generated-go/a2a888b\x06proto3"

var (
	file_a2a888_agent_runtime_proto_rawDescOnce sync.Once
	file_a2a888_agent_runtime_proto_rawDescData []byte
)

func file_a2a888_agent_runtime_proto_rawDescGZIP() []byte {
	file_a2a888_agent_runtime_proto_rawDescOnce.Do(func() {
		file_a2a888_agent_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a2a888_agent_runtime_proto_rawDesc), len(file_a2a888_agent_runtime_proto_rawDesc)))
	})
	return file_a2a888_agent_runtime_proto_rawDescData
}

var file_a2a888_agent_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_a2a888_agent_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_a2a888_agent_runtime_proto_goTypes = []any{
	(RuntimeKind)(0),               // 0: a2a888.v1.RuntimeKind
	(AgentProtocol)(0),             // 1: a2a888.v1.AgentProtocol
	(SessionMode)(0),               // 2: a2a888.v1.SessionMode
	(RuntimeState)(0),              // 3: a2a888.v1.RuntimeState
	(CompatibilityLevel)(0),        // 4: a2a888.v1.CompatibilityLevel
	(*ProviderManifest)(nil),       // 5: a2a888.v1.ProviderManifest
	(*PlatformTarget)(nil),         // 6: a2a888.v1.PlatformTarget
	(*SystemExecutableConfig)(nil), // 7: a2a888.v1.SystemExecutableConfig
	(*NpmPackageConfig)(nil),       // 8: a2a888.v1.NpmPackageConfig
	(*EmbeddedRuntimeConfig)(nil),  // 9: a2a888.v1.EmbeddedRuntimeConfig
	(*CustomRuntimeConfig)(nil),    // 10: a2a888.v1.CustomRuntimeConfig
	(*ProviderCapabilities)(nil),   // 11: a2a888.v1.ProviderCapabilities
	(*PermissionProfile)(nil),      // 12: a2a888.v1.PermissionProfile
	(*SessionBehavior)(nil),        // 13: a2a888.v1.SessionBehavior
	(*PreparedRuntime)(nil),        // 14: a2a888.v1.PreparedRuntime
	(*CacheIdentity)(nil),          // 15: a2a888.v1.CacheIdentity
	(*ResolvedBinary)(nil),         // 16: a2a888.v1.ResolvedBinary
	(*RuntimeStatus)(nil),          // 17: a2a888.v1.RuntimeStatus
	(*CompatibilityReport)(nil),    // 18: a2a888.v1.CompatibilityReport
	(*CompatibilityEvidence)(nil),  // 19: a2a888.v1.CompatibilityEvidence
	(*timestamppb.Timestamp)(nil),  // 20: google.protobuf.Timestamp
}
var file_a2a888_agent_runtime_proto_depIdxs = []int32{
	0,  // 0: a2a888.v1.ProviderManifest.runtime_kind:type_name -> a2a888.v1.RuntimeKind
	1,  // 1: a2a888.v1.ProviderManifest.agent_protocol:type_name -> a2a888.v1.AgentProtocol
	6,  // 2: a2a888.v1.ProviderManifest.platform_targets:type_name -> a2a888.v1.PlatformTarget
	7,  // 3: a2a888.v1.ProviderManifest.system_executable:type_name -> a2a888.v1.SystemExecutableConfig
	8,  // 4: a2a888.v1.ProviderManifest.npm_package:type_name -> a2a888.v1.NpmPackageConfig
	9,  // 5: a2a888.v1.ProviderManifest.embedded:type_name -> a2a888.v1.EmbeddedRuntimeConfig
	10, // 6: a2a888.v1.ProviderManifest.custom:type_name -> a2a888.v1.CustomRuntimeConfig
	11, // 7: a2a888.v1.ProviderManifest.capabilities:type_name -> a2a888.v1.ProviderCapabilities
	12, // 8: a2a888.v1.ProviderManifest.permission_profile:type_name -> a2a888.v1.PermissionProfile
	13, // 9: a2a888.v1.ProviderManifest.session_behavior:type_name -> a2a888.v1.SessionBehavior
	2,  // 10: a2a888.v1.SessionBehavior.mode:type_name -> a2a888.v1.SessionMode
	15, // 11: a2a888.v1.PreparedRuntime.cache_identity:type_name -> a2a888.v1.CacheIdentity
	16, // 12: a2a888.v1.PreparedRuntime.resolved_binary:type_name -> a2a888.v1.ResolvedBinary
	17, // 13: a2a888.v1.PreparedRuntime.status:type_name -> a2a888.v1.RuntimeStatus
	18, // 14: a2a888.v1.PreparedRuntime.compatibility:type_name -> a2a888.v1.CompatibilityReport
	20, // 15: a2a888.v1.PreparedRuntime.prepared_at:type_name -> google.protobuf.Timestamp
	6,  // 16: a2a888.v1.CacheIdentity.platform:type_name -> a2a888.v1.PlatformTarget
	3,  // 17: a2a888.v1.RuntimeStatus.state:type_name -> a2a888.v1.RuntimeState
	20, // 18: a2a888.v1.RuntimeStatus.observed_at:type_name -> google.protobuf.Timestamp
	4,  // 19: a2a888.v1.CompatibilityReport.level:type_name -> a2a888.v1.CompatibilityLevel
	19, // 20: a2a888.v1.CompatibilityReport.evidence:type_name -> a2a888.v1.CompatibilityEvidence
	6,  // 21: a2a888.v1.CompatibilityEvidence.platform:type_name -> a2a888.v1.PlatformTarget
	20, // 22: a2a888.v1.CompatibilityEvidence.tested_at:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_a2a888_agent_runtime_proto_init() }
func file_a2a888_agent_runtime_proto_init() {
	if File_a2a888_agent_runtime_proto != nil {
		return
	}
	file_a2a888_agent_runtime_proto_msgTypes[0].OneofWrappers = []any{
		(*ProviderManifest_SystemExecutable)(nil),
		(*ProviderManifest_NpmPackage)(nil),
		(*ProviderManifest_Embedded)(nil),
		(*ProviderManifest_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a2a888_agent_runtime_proto_rawDesc), len(file_a2a888_agent_runtime_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_a2a888_agent_runtime_proto_goTypes,
		DependencyIndexes: file_a2a888_agent_runtime_proto_depIdxs,
		EnumInfos:         file_a2a888_agent_runtime_proto_enumTypes,
		MessageInfos:      file_a2a888_agent_runtime_proto_msgTypes,
	}.Build()
	File_a2a888_agent_runtime_proto = out.File
	file_a2a888_agent_runtime_proto_goTypes = nil
	file_a2a888_agent_runtime_proto_depIdxs = nil
}
