// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: a2a888/connector.proto

package a2a888

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorHealth int32

const (
	ConnectorHealth_CONNECTOR_HEALTH_UNSPECIFIED ConnectorHealth = 0
	ConnectorHealth_CONNECTOR_HEALTH_HEALTHY     ConnectorHealth = 1
	ConnectorHealth_CONNECTOR_HEALTH_DEGRADED    ConnectorHealth = 2
	ConnectorHealth_CONNECTOR_HEALTH_FAILED      ConnectorHealth = 3
	ConnectorHealth_CONNECTOR_HEALTH_DISABLED    ConnectorHealth = 4
)

// Enum value maps for ConnectorHealth.
var (
	ConnectorHealth_name = map[int32]string{
		0: "CONNECTOR_HEALTH_UNSPECIFIED",
		1: "CONNECTOR_HEALTH_HEALTHY",
		2: "CONNECTOR_HEALTH_DEGRADED",
		3: "CONNECTOR_HEALTH_FAILED",
		4: "CONNECTOR_HEALTH_DISABLED",
	}
	ConnectorHealth_value = map[string]int32{
		"CONNECTOR_HEALTH_UNSPECIFIED": 0,
		"CONNECTOR_HEALTH_HEALTHY":     1,
		"CONNECTOR_HEALTH_DEGRADED":    2,
		"CONNECTOR_HEALTH_FAILED":      3,
		"CONNECTOR_HEALTH_DISABLED":    4,
	}
)

func (x ConnectorHealth) Enum() *ConnectorHealth {
	p := new(ConnectorHealth)
	*p = x
	return p
}

func (x ConnectorHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a888_connector_proto_enumTypes[0].Descriptor()
}

func (ConnectorHealth) Type() protoreflect.EnumType {
	return &file_a2a888_connector_proto_enumTypes[0]
}

func (x ConnectorHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorHealth.Descriptor instead.
func (ConnectorHealth) EnumDescriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{0}
}

type ConnectorInstallation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId       string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	InstallationId       string                 `protobuf:"bytes,3,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Kind                 string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Enabled              bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Capabilities         []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Health               ConnectorHealth        `protobuf:"varint,7,opt,name=health,proto3,enum=a2a888.v1.ConnectorHealth" json:"health,omitempty"`
	PendingDeliveries    int64                  `protobuf:"varint,8,opt,name=pending_deliveries,json=pendingDeliveries,proto3" json:"pending_deliveries,omitempty"`
	DeadLetterDeliveries int64                  `protobuf:"varint,9,opt,name=dead_letter_deliveries,json=deadLetterDeliveries,proto3" json:"dead_letter_deliveries,omitempty"`
	LastError            string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectorInstallation) Reset() {
	*x = ConnectorInstallation{}
	mi := &file_a2a888_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorInstallation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorInstallation) ProtoMessage() {}

func (x *ConnectorInstallation) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorInstallation.ProtoReflect.Descriptor instead.
func (*ConnectorInstallation) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorInstallation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorInstallation) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ConnectorInstallation) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *ConnectorInstallation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ConnectorInstallation) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConnectorInstallation) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectorInstallation) GetHealth() ConnectorHealth {
	if x != nil {
		return x.Health
	}
	return ConnectorHealth_CONNECTOR_HEALTH_UNSPECIFIED
}

func (x *ConnectorInstallation) GetPendingDeliveries() int64 {
	if x != nil {
		return x.PendingDeliveries
	}
	return 0
}

func (x *ConnectorInstallation) GetDeadLetterDeliveries() int64 {
	if x != nil {
		return x.DeadLetterDeliveries
	}
	return 0
}

func (x *ConnectorInstallation) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ConnectorInstallation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListConnectorInstallationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConnectorInstallationsRequest) Reset() {
	*x = ListConnectorInstallationsRequest{}
	mi := &file_a2a888_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorInstallationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorInstallationsRequest) ProtoMessage() {}

func (x *ListConnectorInstallationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorInstallationsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorInstallationsRequest) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{1}
}

func (x *ListConnectorInstallationsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListConnectorInstallationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Installations []*ConnectorInstallation `protobuf:"bytes,1,rep,name=installations,proto3" json:"installations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorInstallationsResponse) Reset() {
	*x = ListConnectorInstallationsResponse{}
	mi := &file_a2a888_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorInstallationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorInstallationsResponse) ProtoMessage() {}

func (x *ListConnectorInstallationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorInstallationsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorInstallationsResponse) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ListConnectorInstallationsResponse) GetInstallations() []*ConnectorInstallation {
	if x != nil {
		return x.Installations
	}
	return nil
}

type InstallConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *ConnectorInstallation `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	Credential    []byte                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallConnectorRequest) Reset() {
	*x = InstallConnectorRequest{}
	mi := &file_a2a888_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallConnectorRequest) ProtoMessage() {}

func (x *InstallConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallConnectorRequest.ProtoReflect.Descriptor instead.
func (*InstallConnectorRequest) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{3}
}

func (x *InstallConnectorRequest) GetInstallation() *ConnectorInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

func (x *InstallConnectorRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type UninstallConnectorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	InstallationId string                 `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UninstallConnectorRequest) Reset() {
	*x = UninstallConnectorRequest{}
	mi := &file_a2a888_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallConnectorRequest) ProtoMessage() {}

func (x *UninstallConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallConnectorRequest.ProtoReflect.Descriptor instead.
func (*UninstallConnectorRequest) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{4}
}

func (x *UninstallConnectorRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UninstallConnectorRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

type UninstallConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallConnectorResponse) Reset() {
	*x = UninstallConnectorResponse{}
	mi := &file_a2a888_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallConnectorResponse) ProtoMessage() {}

func (x *UninstallConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a888_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallConnectorResponse.ProtoReflect.Descriptor instead.
func (*UninstallConnectorResponse) Descriptor() ([]byte, []int) {
	return file_a2a888_connector_proto_rawDescGZIP(), []int{5}
}

var File_a2a888_connector_proto protoreflect.FileDescriptor

const file_a2a888_connector_proto_rawDesc = "" +
	"\n" +
	"\x16a2a888/connector.proto\x12\ta2a888.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x03\n" +
	"\x15ConnectorInstallation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x0finstallation_id\x18\x03 \x01(\tR\x0einstallationId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x122\n" +
	"\x06health\x18\a \x01(\x0e2\x1a.a2a888.v1.ConnectorHealthR\x06health\x12-\n" +
	"\x12pending_deliveries\x18\b \x01(\x03R\x11pendingDeliveries\x124\n" +
	"\x16dead_letter_deliveries\x18\t \x01(\x03R\x14deadLetterDeliveries\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"L\n" +
	"!ListConnectorInstallationsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"l\n" +
	"\"ListConnectorInstallationsResponse\x12F\n" +
	"\rinstallations\x18\x01 \x03(\v2 .a2a888.v1.ConnectorInstallationR\rinstallations\"\x7f\n" +
	"\x17InstallConnectorRequest\x12D\n" +
	"\finstallation\x18\x01 \x01(\v2 .a2a888.v1.ConnectorInstallationR\finstallation\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\fR\n" +
	"credential\"m\n" +
	"\x19UninstallConnectorRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\tR\x0einstallationId\"\x1c\n" +
	"\x1aUninstallConnectorResponse*\xac\x01\n" +
	"\x0fConnectorHealth\x12 \n" +
	"\x1cCONNECTOR_HEALTH_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONNECTOR_HEALTH_HEALTHY\x10\x01\x12\x1d\n" +
	"\x19CONNECTOR_HEALTH_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17CONNECTOR_HEALTH_FAILED\x10\x03\x12\x1d\n" +
	"\x19CONNECTOR_HEALTH_DISABLED\x10\x042\xca\x02\n" +
	"\x10ConnectorService\x12y\n" +
	"\x1aListConnectorInstallations\x12,.a2a888.v1.ListConnectorInstallationsRequest\x1a-.a2a888.v1.ListConnectorInstallationsResponse\x12X\n" +
	"\x10InstallConnector\x12\".a2a888.v1.InstallConnectorRequest\x1a .a2a888.v1.ConnectorInstallation\x12a\n" +
	"\x12UninstallConnector\x12$.a2a888.v1.UninstallConnectorRequest\x1a%.a2a888.v1.UninstallConnectorResponseB;Z9github.com/tbdavid2019/888a2a/backend/generated-go/a2a888b\x06proto3"

var (
	file_a2a888_connector_proto_rawDescOnce sync.Once
	file_a2a888_connector_proto_rawDescData []byte
)

func file_a2a888_connector_proto_rawDescGZIP() []byte {
	file_a2a888_connector_proto_rawDescOnce.Do(func() {
		file_a2a888_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a2a888_connector_proto_rawDesc), len(file_a2a888_connector_proto_rawDesc)))
	})
	return file_a2a888_connector_proto_rawDescData
}

var file_a2a888_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_a2a888_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_a2a888_connector_proto_goTypes = []any{
	(ConnectorHealth)(0),                       // 0: a2a888.v1.ConnectorHealth
	(*ConnectorInstallation)(nil),              // 1: a2a888.v1.ConnectorInstallation
	(*ListConnectorInstallationsRequest)(nil),  // 2: a2a888.v1.ListConnectorInstallationsRequest
	(*ListConnectorInstallationsResponse)(nil), // 3: a2a888.v1.ListConnectorInstallationsResponse
	(*InstallConnectorRequest)(nil),            // 4: a2a888.v1.InstallConnectorRequest
	(*UninstallConnectorRequest)(nil),          // 5: a2a888.v1.UninstallConnectorRequest
	(*UninstallConnectorResponse)(nil),         // 6: a2a888.v1.UninstallConnectorResponse
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
}
var file_a2a888_connector_proto_depIdxs = []int32{
	0, // 0: a2a888.v1.ConnectorInstallation.health:type_name -> a2a888.v1.ConnectorHealth
	7, // 1: a2a888.v1.ConnectorInstallation.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: a2a888.v1.ListConnectorInstallationsResponse.installations:type_name -> a2a888.v1.ConnectorInstallation
	1, // 3: a2a888.v1.InstallConnectorRequest.installation:type_name -> a2a888.v1.ConnectorInstallation
	2, // 4: a2a888.v1.ConnectorService.ListConnectorInstallations:input_type -> a2a888.v1.ListConnectorInstallationsRequest
	4, // 5: a2a888.v1.ConnectorService.InstallConnector:input_type -> a2a888.v1.InstallConnectorRequest
	5, // 6: a2a888.v1.ConnectorService.UninstallConnector:input_type -> a2a888.v1.UninstallConnectorRequest
	3, // 7: a2a888.v1.ConnectorService.ListConnectorInstallations:output_type -> a2a888.v1.ListConnectorInstallationsResponse
	1, // 8: a2a888.v1.ConnectorService.InstallConnector:output_type -> a2a888.v1.ConnectorInstallation
	6, // 9: a2a888.v1.ConnectorService.UninstallConnector:output_type -> a2a888.v1.UninstallConnectorResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_a2a888_connector_proto_init() }
func file_a2a888_connector_proto_init() {
	if File_a2a888_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a2a888_connector_proto_rawDesc), len(file_a2a888_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a2a888_connector_proto_goTypes,
		DependencyIndexes: file_a2a888_connector_proto_depIdxs,
		EnumInfos:         file_a2a888_connector_proto_enumTypes,
		MessageInfos:      file_a2a888_connector_proto_msgTypes,
	}.Build()
	File_a2a888_connector_proto = out.File
	file_a2a888_connector_proto_goTypes = nil
	file_a2a888_connector_proto_depIdxs = nil
}
