// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: store/agent.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentTokenType int32

const (
	AgentTokenType_TOKEN_TYPE_UNSPECIFIED AgentTokenType = 0
	AgentTokenType_BOOTSTRAP              AgentTokenType = 1
	AgentTokenType_ACCESS                 AgentTokenType = 2
	AgentTokenType_REFRESH                AgentTokenType = 3
)

// Enum value maps for AgentTokenType.
var (
	AgentTokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "BOOTSTRAP",
		2: "ACCESS",
		3: "REFRESH",
	}
	AgentTokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"BOOTSTRAP":              1,
		"ACCESS":                 2,
		"REFRESH":                3,
	}
)

func (x AgentTokenType) Enum() *AgentTokenType {
	p := new(AgentTokenType)
	*p = x
	return p
}

func (x AgentTokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_store_agent_proto_enumTypes[0].Descriptor()
}

func (AgentTokenType) Type() protoreflect.EnumType {
	return &file_store_agent_proto_enumTypes[0]
}

func (x AgentTokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTokenType.Descriptor instead.
func (AgentTokenType) EnumDescriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{0}
}

type AgentTokenState int32

const (
	AgentTokenState_STATE_UNSPECIFIED AgentTokenState = 0
	AgentTokenState_ACTIVE            AgentTokenState = 1
	AgentTokenState_CONSUMED          AgentTokenState = 2
	AgentTokenState_REVOKED           AgentTokenState = 3
)

// Enum value maps for AgentTokenState.
var (
	AgentTokenState_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "CONSUMED",
		3: "REVOKED",
	}
	AgentTokenState_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"ACTIVE":            1,
		"CONSUMED":          2,
		"REVOKED":           3,
	}
)

func (x AgentTokenState) Enum() *AgentTokenState {
	p := new(AgentTokenState)
	*p = x
	return p
}

func (x AgentTokenState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTokenState) Descriptor() protoreflect.EnumDescriptor {
	return file_store_agent_proto_enumTypes[1].Descriptor()
}

func (AgentTokenState) Type() protoreflect.EnumType {
	return &file_store_agent_proto_enumTypes[1]
}

func (x AgentTokenState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTokenState.Descriptor instead.
func (AgentTokenState) EnumDescriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{1}
}

type AgentStatus_ConnectionState int32

const (
	AgentStatus_CONNECTION_STATE_UNSPECIFIED AgentStatus_ConnectionState = 0
	AgentStatus_ONLINE                       AgentStatus_ConnectionState = 1
	AgentStatus_OFFLINE                      AgentStatus_ConnectionState = 2
	AgentStatus_ERROR                        AgentStatus_ConnectionState = 3
	AgentStatus_KICKED                       AgentStatus_ConnectionState = 4
)

// Enum value maps for AgentStatus_ConnectionState.
var (
	AgentStatus_ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "ONLINE",
		2: "OFFLINE",
		3: "ERROR",
		4: "KICKED",
	}
	AgentStatus_ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED": 0,
		"ONLINE":                       1,
		"OFFLINE":                      2,
		"ERROR":                        3,
		"KICKED":                       4,
	}
)

func (x AgentStatus_ConnectionState) Enum() *AgentStatus_ConnectionState {
	p := new(AgentStatus_ConnectionState)
	*p = x
	return p
}

func (x AgentStatus_ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_store_agent_proto_enumTypes[2].Descriptor()
}

func (AgentStatus_ConnectionState) Type() protoreflect.EnumType {
	return &file_store_agent_proto_enumTypes[2]
}

func (x AgentStatus_ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus_ConnectionState.Descriptor instead.
func (AgentStatus_ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{5, 0}
}

type AgentInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentType          string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                 string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch               string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Ip                 string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Version            string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capability         *AgentCapability       `protobuf:"bytes,8,opt,name=capability,proto3" json:"capability,omitempty"`
	AvailableProviders []*AgentProviderInfo   `protobuf:"bytes,9,rep,name=available_providers,json=availableProviders,proto3" json:"available_providers,omitempty"`
	AcpConfig          *AgentACPConfig        `protobuf:"bytes,10,opt,name=acp_config,json=acpConfig,proto3" json:"acp_config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_store_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentInfo) GetCapability() *AgentCapability {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *AgentInfo) GetAvailableProviders() []*AgentProviderInfo {
	if x != nil {
		return x.AvailableProviders
	}
	return nil
}

func (x *AgentInfo) GetAcpConfig() *AgentACPConfig {
	if x != nil {
		return x.AcpConfig
	}
	return nil
}

type AgentACPConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Executable          string                 `protobuf:"bytes,1,opt,name=executable,proto3" json:"executable,omitempty"`
	Args                []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	AllowEnv            []string               `protobuf:"bytes,3,rep,name=allow_env,json=allowEnv,proto3" json:"allow_env,omitempty"`
	Provider            string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Model               string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	CustomEnv           map[string]string      `protobuf:"bytes,6,rep,name=custom_env,json=customEnv,proto3" json:"custom_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PersonaPrompt       string                 `protobuf:"bytes,7,opt,name=persona_prompt,json=personaPrompt,proto3" json:"persona_prompt,omitempty"`
	ApiProvider         string                 `protobuf:"bytes,8,opt,name=api_provider,json=apiProvider,proto3" json:"api_provider,omitempty"`
	ApiKey              string                 `protobuf:"bytes,9,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	GlobalProvider      string                 `protobuf:"bytes,10,opt,name=global_provider,json=globalProvider,proto3" json:"global_provider,omitempty"`
	GlobalProviderEntry string                 `protobuf:"bytes,11,opt,name=global_provider_entry,json=globalProviderEntry,proto3" json:"global_provider_entry,omitempty"`
	Protocol            string                 `protobuf:"bytes,12,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// api_base_url is the custom LLM API base URL for the built-in pi runtime.
	// Only meaningful when provider == "builtin-pi" and api_provider == "custom";
	// ignored by ACP runtimes and by known (deepseek/openrouter) providers.
	ApiBaseUrl    string `protobuf:"bytes,13,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentACPConfig) Reset() {
	*x = AgentACPConfig{}
	mi := &file_store_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentACPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentACPConfig) ProtoMessage() {}

func (x *AgentACPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentACPConfig.ProtoReflect.Descriptor instead.
func (*AgentACPConfig) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentACPConfig) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *AgentACPConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AgentACPConfig) GetAllowEnv() []string {
	if x != nil {
		return x.AllowEnv
	}
	return nil
}

func (x *AgentACPConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentACPConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentACPConfig) GetCustomEnv() map[string]string {
	if x != nil {
		return x.CustomEnv
	}
	return nil
}

func (x *AgentACPConfig) GetPersonaPrompt() string {
	if x != nil {
		return x.PersonaPrompt
	}
	return ""
}

func (x *AgentACPConfig) GetApiProvider() string {
	if x != nil {
		return x.ApiProvider
	}
	return ""
}

func (x *AgentACPConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AgentACPConfig) GetGlobalProvider() string {
	if x != nil {
		return x.GlobalProvider
	}
	return ""
}

func (x *AgentACPConfig) GetGlobalProviderEntry() string {
	if x != nil {
		return x.GlobalProviderEntry
	}
	return ""
}

func (x *AgentACPConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AgentACPConfig) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type AgentProviderInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ProviderId                string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DisplayName               string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version                   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ExecutablePath            string                 `protobuf:"bytes,4,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	Models                    []*AgentModelOption    `protobuf:"bytes,5,rep,name=models,proto3" json:"models,omitempty"`
	SupportsModelConfigOption bool                   `protobuf:"varint,6,opt,name=supports_model_config_option,json=supportsModelConfigOption,proto3" json:"supports_model_config_option,omitempty"`
	DetectedAt                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	RuntimeStatus             string                 `protobuf:"bytes,8,opt,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty"`
	CompatibilityLevel        string                 `protobuf:"bytes,9,opt,name=compatibility_level,json=compatibilityLevel,proto3" json:"compatibility_level,omitempty"`
	FailureMessage            string                 `protobuf:"bytes,10,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	PackageVersion            string                 `protobuf:"bytes,11,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	ManifestDigest            string                 `protobuf:"bytes,12,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AgentProviderInfo) Reset() {
	*x = AgentProviderInfo{}
	mi := &file_store_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProviderInfo) ProtoMessage() {}

func (x *AgentProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProviderInfo.ProtoReflect.Descriptor instead.
func (*AgentProviderInfo) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentProviderInfo) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AgentProviderInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentProviderInfo) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *AgentProviderInfo) GetModels() []*AgentModelOption {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AgentProviderInfo) GetSupportsModelConfigOption() bool {
	if x != nil {
		return x.SupportsModelConfigOption
	}
	return false
}

func (x *AgentProviderInfo) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *AgentProviderInfo) GetRuntimeStatus() string {
	if x != nil {
		return x.RuntimeStatus
	}
	return ""
}

func (x *AgentProviderInfo) GetCompatibilityLevel() string {
	if x != nil {
		return x.CompatibilityLevel
	}
	return ""
}

func (x *AgentProviderInfo) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *AgentProviderInfo) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *AgentProviderInfo) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

type AgentModelOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModelOption) Reset() {
	*x = AgentModelOption{}
	mi := &file_store_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModelOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModelOption) ProtoMessage() {}

func (x *AgentModelOption) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModelOption.ProtoReflect.Descriptor instead.
func (*AgentModelOption) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentModelOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AgentModelOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentModelOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AgentCapability struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SupportsAcp                bool                   `protobuf:"varint,1,opt,name=supports_acp,json=supportsAcp,proto3" json:"supports_acp,omitempty"`
	MaxTimeoutSeconds          int32                  `protobuf:"varint,3,opt,name=max_timeout_seconds,json=maxTimeoutSeconds,proto3" json:"max_timeout_seconds,omitempty"`
	SupportsDiff               bool                   `protobuf:"varint,4,opt,name=supports_diff,json=supportsDiff,proto3" json:"supports_diff,omitempty"`
	SupportsRawEvents          bool                   `protobuf:"varint,5,opt,name=supports_raw_events,json=supportsRawEvents,proto3" json:"supports_raw_events,omitempty"`
	SupportsToolTraces         bool                   `protobuf:"varint,6,opt,name=supports_tool_traces,json=supportsToolTraces,proto3" json:"supports_tool_traces,omitempty"`
	MaxEventCount              int32                  `protobuf:"varint,7,opt,name=max_event_count,json=maxEventCount,proto3" json:"max_event_count,omitempty"`
	MaxOutputBytes             int64                  `protobuf:"varint,8,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	SupportsAutonomousDecision bool                   `protobuf:"varint,9,opt,name=supports_autonomous_decision,json=supportsAutonomousDecision,proto3" json:"supports_autonomous_decision,omitempty"`
	SupportsPi                 bool                   `protobuf:"varint,10,opt,name=supports_pi,json=supportsPi,proto3" json:"supports_pi,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AgentCapability) Reset() {
	*x = AgentCapability{}
	mi := &file_store_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapability) ProtoMessage() {}

func (x *AgentCapability) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapability.ProtoReflect.Descriptor instead.
func (*AgentCapability) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCapability) GetSupportsAcp() bool {
	if x != nil {
		return x.SupportsAcp
	}
	return false
}

func (x *AgentCapability) GetMaxTimeoutSeconds() int32 {
	if x != nil {
		return x.MaxTimeoutSeconds
	}
	return 0
}

func (x *AgentCapability) GetSupportsDiff() bool {
	if x != nil {
		return x.SupportsDiff
	}
	return false
}

func (x *AgentCapability) GetSupportsRawEvents() bool {
	if x != nil {
		return x.SupportsRawEvents
	}
	return false
}

func (x *AgentCapability) GetSupportsToolTraces() bool {
	if x != nil {
		return x.SupportsToolTraces
	}
	return false
}

func (x *AgentCapability) GetMaxEventCount() int32 {
	if x != nil {
		return x.MaxEventCount
	}
	return 0
}

func (x *AgentCapability) GetMaxOutputBytes() int64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *AgentCapability) GetSupportsAutonomousDecision() bool {
	if x != nil {
		return x.SupportsAutonomousDecision
	}
	return false
}

func (x *AgentCapability) GetSupportsPi() bool {
	if x != nil {
		return x.SupportsPi
	}
	return false
}

type AgentStatus struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	State           AgentStatus_ConnectionState `protobuf:"varint,1,opt,name=state,proto3,enum=laelia.store.AgentStatus_ConnectionState" json:"state,omitempty"`
	LastHeartbeatAt int64                       `protobuf:"varint,2,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	ConnectedAt     int64                       `protobuf:"varint,3,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	ErrorMessage    string                      `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ActiveSessionId string                      `protobuf:"bytes,5,opt,name=active_session_id,json=activeSessionId,proto3" json:"active_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_store_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_store_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_store_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStatus) GetState() AgentStatus_ConnectionState {
	if x != nil {
		return x.State
	}
	return AgentStatus_CONNECTION_STATE_UNSPECIFIED
}

func (x *AgentStatus) GetLastHeartbeatAt() int64 {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return 0
}

func (x *AgentStatus) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *AgentStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AgentStatus) GetActiveSessionId() string {
	if x != nil {
		return x.ActiveSessionId
	}
	return ""
}

var File_store_agent_proto protoreflect.FileDescriptor

const file_store_agent_proto_rawDesc = "" +
	"\n" +
	"\x11store/agent.proto\x12\flaelia.store\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n" +
	"\tAgentInfo\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.laelia.store.AgentInfo.LabelsEntryR\x06labels\x12=\n" +
	"\n" +
	"capability\x18\b \x01(\v2\x1d.laelia.store.AgentCapabilityR\n" +
	"capability\x12P\n" +
	"\x13available_providers\x18\t \x03(\v2\x1f.laelia.store.AgentProviderInfoR\x12availableProviders\x12;\n" +
	"\n" +
	"acp_config\x18\n" +
	" \x01(\v2\x1c.laelia.store.AgentACPConfigR\tacpConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x04\n" +
	"\x0eAgentACPConfig\x12\x1e\n" +
	"\n" +
	"executable\x18\x01 \x01(\tR\n" +
	"executable\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1b\n" +
	"\tallow_env\x18\x03 \x03(\tR\ballowEnv\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12J\n" +
	"\n" +
	"custom_env\x18\x06 \x03(\v2+.laelia.store.AgentACPConfig.CustomEnvEntryR\tcustomEnv\x12%\n" +
	"\x0epersona_prompt\x18\a \x01(\tR\rpersonaPrompt\x12!\n" +
	"\fapi_provider\x18\b \x01(\tR\vapiProvider\x12\x17\n" +
	"\aapi_key\x18\t \x01(\tR\x06apiKey\x12'\n" +
	"\x0fglobal_provider\x18\n" +
	" \x01(\tR\x0eglobalProvider\x122\n" +
	"\x15global_provider_entry\x18\v \x01(\tR\x13globalProviderEntry\x12\x1a\n" +
	"\bprotocol\x18\f \x01(\tR\bprotocol\x12 \n" +
	"\fapi_base_url\x18\r \x01(\tR\n" +
	"apiBaseUrl\x1a<\n" +
	"\x0eCustomEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x04\n" +
	"\x11AgentProviderInfo\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12'\n" +
	"\x0fexecutable_path\x18\x04 \x01(\tR\x0eexecutablePath\x126\n" +
	"\x06models\x18\x05 \x03(\v2\x1e.laelia.store.AgentModelOptionR\x06models\x12?\n" +
	"\x1csupports_model_config_option\x18\x06 \x01(\bR\x19supportsModelConfigOption\x12;\n" +
	"\vdetected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12%\n" +
	"\x0eruntime_status\x18\b \x01(\tR\rruntimeStatus\x12/\n" +
	"\x13compatibility_level\x18\t \x01(\tR\x12compatibilityLevel\x12'\n" +
	"\x0ffailure_message\x18\n" +
	" \x01(\tR\x0efailureMessage\x12'\n" +
	"\x0fpackage_version\x18\v \x01(\tR\x0epackageVersion\x12'\n" +
	"\x0fmanifest_digest\x18\f \x01(\tR\x0emanifestDigest\"^\n" +
	"\x10AgentModelOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa0\x03\n" +
	"\x0fAgentCapability\x12!\n" +
	"\fsupports_acp\x18\x01 \x01(\bR\vsupportsAcp\x12.\n" +
	"\x13max_timeout_seconds\x18\x03 \x01(\x05R\x11maxTimeoutSeconds\x12#\n" +
	"\rsupports_diff\x18\x04 \x01(\bR\fsupportsDiff\x12.\n" +
	"\x13supports_raw_events\x18\x05 \x01(\bR\x11supportsRawEvents\x120\n" +
	"\x14supports_tool_traces\x18\x06 \x01(\bR\x12supportsToolTraces\x12&\n" +
	"\x0fmax_event_count\x18\a \x01(\x05R\rmaxEventCount\x12(\n" +
	"\x10max_output_bytes\x18\b \x01(\x03R\x0emaxOutputBytes\x12@\n" +
	"\x1csupports_autonomous_decision\x18\t \x01(\bR\x1asupportsAutonomousDecision\x12\x1f\n" +
	"\vsupports_pi\x18\n" +
	" \x01(\bR\n" +
	"supportsPi\"\xd3\x02\n" +
	"\vAgentStatus\x12?\n" +
	"\x05state\x18\x01 \x01(\x0e2).laelia.store.AgentStatus.ConnectionStateR\x05state\x12*\n" +
	"\x11last_heartbeat_at\x18\x02 \x01(\x03R\x0flastHeartbeatAt\x12!\n" +
	"\fconnected_at\x18\x03 \x01(\x03R\vconnectedAt\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11active_session_id\x18\x05 \x01(\tR\x0factiveSessionId\"c\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\v\n" +
	"\aOFFLINE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\n" +
	"\n" +
	"\x06KICKED\x10\x04*T\n" +
	"\x0eAgentTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tBOOTSTRAP\x10\x01\x12\n" +
	"\n" +
	"\x06ACCESS\x10\x02\x12\v\n" +
	"\aREFRESH\x10\x03*O\n" +
	"\x0fAgentTokenState\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bCONSUMED\x10\x02\x12\v\n" +
	"\aREVOKED\x10\x03B4Z2github.com/Ranxy/laelia/backend/generated-go/storeb\x06proto3"

var (
	file_store_agent_proto_rawDescOnce sync.Once
	file_store_agent_proto_rawDescData []byte
)

func file_store_agent_proto_rawDescGZIP() []byte {
	file_store_agent_proto_rawDescOnce.Do(func() {
		file_store_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_agent_proto_rawDesc), len(file_store_agent_proto_rawDesc)))
	})
	return file_store_agent_proto_rawDescData
}

var file_store_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_store_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_store_agent_proto_goTypes = []any{
	(AgentTokenType)(0),              // 0: laelia.store.AgentTokenType
	(AgentTokenState)(0),             // 1: laelia.store.AgentTokenState
	(AgentStatus_ConnectionState)(0), // 2: laelia.store.AgentStatus.ConnectionState
	(*AgentInfo)(nil),                // 3: laelia.store.AgentInfo
	(*AgentACPConfig)(nil),           // 4: laelia.store.AgentACPConfig
	(*AgentProviderInfo)(nil),        // 5: laelia.store.AgentProviderInfo
	(*AgentModelOption)(nil),         // 6: laelia.store.AgentModelOption
	(*AgentCapability)(nil),          // 7: laelia.store.AgentCapability
	(*AgentStatus)(nil),              // 8: laelia.store.AgentStatus
	nil,                              // 9: laelia.store.AgentInfo.LabelsEntry
	nil,                              // 10: laelia.store.AgentACPConfig.CustomEnvEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_store_agent_proto_depIdxs = []int32{
	9,  // 0: laelia.store.AgentInfo.labels:type_name -> laelia.store.AgentInfo.LabelsEntry
	7,  // 1: laelia.store.AgentInfo.capability:type_name -> laelia.store.AgentCapability
	5,  // 2: laelia.store.AgentInfo.available_providers:type_name -> laelia.store.AgentProviderInfo
	4,  // 3: laelia.store.AgentInfo.acp_config:type_name -> laelia.store.AgentACPConfig
	10, // 4: laelia.store.AgentACPConfig.custom_env:type_name -> laelia.store.AgentACPConfig.CustomEnvEntry
	6,  // 5: laelia.store.AgentProviderInfo.models:type_name -> laelia.store.AgentModelOption
	11, // 6: laelia.store.AgentProviderInfo.detected_at:type_name -> google.protobuf.Timestamp
	2,  // 7: laelia.store.AgentStatus.state:type_name -> laelia.store.AgentStatus.ConnectionState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_store_agent_proto_init() }
func file_store_agent_proto_init() {
	if File_store_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_agent_proto_rawDesc), len(file_store_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_agent_proto_goTypes,
		DependencyIndexes: file_store_agent_proto_depIdxs,
		EnumInfos:         file_store_agent_proto_enumTypes,
		MessageInfos:      file_store_agent_proto_msgTypes,
	}.Build()
	File_store_agent_proto = out.File
	file_store_agent_proto_goTypes = nil
	file_store_agent_proto_depIdxs = nil
}
