// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: a2a888/connector.proto

package a2a888connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	a2a888 "github.com/tbdavid2019/888a2a/backend/generated-go/a2a888"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectorServiceName is the fully-qualified name of the ConnectorService service.
	ConnectorServiceName = "a2a888.v1.ConnectorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectorServiceListConnectorInstallationsProcedure is the fully-qualified name of the
	// ConnectorService's ListConnectorInstallations RPC.
	ConnectorServiceListConnectorInstallationsProcedure = "/a2a888.v1.ConnectorService/ListConnectorInstallations"
)

// ConnectorServiceClient is a client for the a2a888.v1.ConnectorService service.
type ConnectorServiceClient interface {
	ListConnectorInstallations(context.Context, *connect.Request[a2a888.ListConnectorInstallationsRequest]) (*connect.Response[a2a888.ListConnectorInstallationsResponse], error)
}

// NewConnectorServiceClient constructs a client for the a2a888.v1.ConnectorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectorServiceMethods := a2a888.File_a2a888_connector_proto.Services().ByName("ConnectorService").Methods()
	return &connectorServiceClient{
		listConnectorInstallations: connect.NewClient[a2a888.ListConnectorInstallationsRequest, a2a888.ListConnectorInstallationsResponse](
			httpClient,
			baseURL+ConnectorServiceListConnectorInstallationsProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("ListConnectorInstallations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectorServiceClient implements ConnectorServiceClient.
type connectorServiceClient struct {
	listConnectorInstallations *connect.Client[a2a888.ListConnectorInstallationsRequest, a2a888.ListConnectorInstallationsResponse]
}

// ListConnectorInstallations calls a2a888.v1.ConnectorService.ListConnectorInstallations.
func (c *connectorServiceClient) ListConnectorInstallations(ctx context.Context, req *connect.Request[a2a888.ListConnectorInstallationsRequest]) (*connect.Response[a2a888.ListConnectorInstallationsResponse], error) {
	return c.listConnectorInstallations.CallUnary(ctx, req)
}

// ConnectorServiceHandler is an implementation of the a2a888.v1.ConnectorService service.
type ConnectorServiceHandler interface {
	ListConnectorInstallations(context.Context, *connect.Request[a2a888.ListConnectorInstallationsRequest]) (*connect.Response[a2a888.ListConnectorInstallationsResponse], error)
}

// NewConnectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectorServiceHandler(svc ConnectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectorServiceMethods := a2a888.File_a2a888_connector_proto.Services().ByName("ConnectorService").Methods()
	connectorServiceListConnectorInstallationsHandler := connect.NewUnaryHandler(
		ConnectorServiceListConnectorInstallationsProcedure,
		svc.ListConnectorInstallations,
		connect.WithSchema(connectorServiceMethods.ByName("ListConnectorInstallations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/a2a888.v1.ConnectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectorServiceListConnectorInstallationsProcedure:
			connectorServiceListConnectorInstallationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectorServiceHandler struct{}

func (UnimplementedConnectorServiceHandler) ListConnectorInstallations(context.Context, *connect.Request[a2a888.ListConnectorInstallationsRequest]) (*connect.Response[a2a888.ListConnectorInstallationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.ConnectorService.ListConnectorInstallations is not implemented"))
}
