// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: a2a888/organization.proto

package a2a888connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	a2a888 "github.com/Ranxy/laelia/backend/generated-go/a2a888"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrganizationServiceName is the fully-qualified name of the OrganizationService service.
	OrganizationServiceName = "a2a888.v1.OrganizationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrganizationServiceListOrganizationsProcedure is the fully-qualified name of the
	// OrganizationService's ListOrganizations RPC.
	OrganizationServiceListOrganizationsProcedure = "/a2a888.v1.OrganizationService/ListOrganizations"
	// OrganizationServiceGetOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's GetOrganization RPC.
	OrganizationServiceGetOrganizationProcedure = "/a2a888.v1.OrganizationService/GetOrganization"
	// OrganizationServiceSwitchOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's SwitchOrganization RPC.
	OrganizationServiceSwitchOrganizationProcedure = "/a2a888.v1.OrganizationService/SwitchOrganization"
	// OrganizationServiceListWorkspacesProcedure is the fully-qualified name of the
	// OrganizationService's ListWorkspaces RPC.
	OrganizationServiceListWorkspacesProcedure = "/a2a888.v1.OrganizationService/ListWorkspaces"
	// OrganizationServiceListMembershipsProcedure is the fully-qualified name of the
	// OrganizationService's ListMemberships RPC.
	OrganizationServiceListMembershipsProcedure = "/a2a888.v1.OrganizationService/ListMemberships"
)

// OrganizationServiceClient is a client for the a2a888.v1.OrganizationService service.
type OrganizationServiceClient interface {
	ListOrganizations(context.Context, *connect.Request[a2a888.ListOrganizationsRequest]) (*connect.Response[a2a888.ListOrganizationsResponse], error)
	GetOrganization(context.Context, *connect.Request[a2a888.GetOrganizationRequest]) (*connect.Response[a2a888.GetOrganizationResponse], error)
	SwitchOrganization(context.Context, *connect.Request[a2a888.SwitchOrganizationRequest]) (*connect.Response[a2a888.SwitchOrganizationResponse], error)
	ListWorkspaces(context.Context, *connect.Request[a2a888.ListWorkspacesRequest]) (*connect.Response[a2a888.ListWorkspacesResponse], error)
	ListMemberships(context.Context, *connect.Request[a2a888.ListMembershipsRequest]) (*connect.Response[a2a888.ListMembershipsResponse], error)
}

// NewOrganizationServiceClient constructs a client for the a2a888.v1.OrganizationService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrganizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrganizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	organizationServiceMethods := a2a888.File_a2a888_organization_proto.Services().ByName("OrganizationService").Methods()
	return &organizationServiceClient{
		listOrganizations: connect.NewClient[a2a888.ListOrganizationsRequest, a2a888.ListOrganizationsResponse](
			httpClient,
			baseURL+OrganizationServiceListOrganizationsProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
			connect.WithClientOptions(opts...),
		),
		getOrganization: connect.NewClient[a2a888.GetOrganizationRequest, a2a888.GetOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceGetOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
			connect.WithClientOptions(opts...),
		),
		switchOrganization: connect.NewClient[a2a888.SwitchOrganizationRequest, a2a888.SwitchOrganizationResponse](
			httpClient,
			baseURL+OrganizationServiceSwitchOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("SwitchOrganization")),
			connect.WithClientOptions(opts...),
		),
		listWorkspaces: connect.NewClient[a2a888.ListWorkspacesRequest, a2a888.ListWorkspacesResponse](
			httpClient,
			baseURL+OrganizationServiceListWorkspacesProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		listMemberships: connect.NewClient[a2a888.ListMembershipsRequest, a2a888.ListMembershipsResponse](
			httpClient,
			baseURL+OrganizationServiceListMembershipsProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListMemberships")),
			connect.WithClientOptions(opts...),
		),
	}
}

// organizationServiceClient implements OrganizationServiceClient.
type organizationServiceClient struct {
	listOrganizations  *connect.Client[a2a888.ListOrganizationsRequest, a2a888.ListOrganizationsResponse]
	getOrganization    *connect.Client[a2a888.GetOrganizationRequest, a2a888.GetOrganizationResponse]
	switchOrganization *connect.Client[a2a888.SwitchOrganizationRequest, a2a888.SwitchOrganizationResponse]
	listWorkspaces     *connect.Client[a2a888.ListWorkspacesRequest, a2a888.ListWorkspacesResponse]
	listMemberships    *connect.Client[a2a888.ListMembershipsRequest, a2a888.ListMembershipsResponse]
}

// ListOrganizations calls a2a888.v1.OrganizationService.ListOrganizations.
func (c *organizationServiceClient) ListOrganizations(ctx context.Context, req *connect.Request[a2a888.ListOrganizationsRequest]) (*connect.Response[a2a888.ListOrganizationsResponse], error) {
	return c.listOrganizations.CallUnary(ctx, req)
}

// GetOrganization calls a2a888.v1.OrganizationService.GetOrganization.
func (c *organizationServiceClient) GetOrganization(ctx context.Context, req *connect.Request[a2a888.GetOrganizationRequest]) (*connect.Response[a2a888.GetOrganizationResponse], error) {
	return c.getOrganization.CallUnary(ctx, req)
}

// SwitchOrganization calls a2a888.v1.OrganizationService.SwitchOrganization.
func (c *organizationServiceClient) SwitchOrganization(ctx context.Context, req *connect.Request[a2a888.SwitchOrganizationRequest]) (*connect.Response[a2a888.SwitchOrganizationResponse], error) {
	return c.switchOrganization.CallUnary(ctx, req)
}

// ListWorkspaces calls a2a888.v1.OrganizationService.ListWorkspaces.
func (c *organizationServiceClient) ListWorkspaces(ctx context.Context, req *connect.Request[a2a888.ListWorkspacesRequest]) (*connect.Response[a2a888.ListWorkspacesResponse], error) {
	return c.listWorkspaces.CallUnary(ctx, req)
}

// ListMemberships calls a2a888.v1.OrganizationService.ListMemberships.
func (c *organizationServiceClient) ListMemberships(ctx context.Context, req *connect.Request[a2a888.ListMembershipsRequest]) (*connect.Response[a2a888.ListMembershipsResponse], error) {
	return c.listMemberships.CallUnary(ctx, req)
}

// OrganizationServiceHandler is an implementation of the a2a888.v1.OrganizationService service.
type OrganizationServiceHandler interface {
	ListOrganizations(context.Context, *connect.Request[a2a888.ListOrganizationsRequest]) (*connect.Response[a2a888.ListOrganizationsResponse], error)
	GetOrganization(context.Context, *connect.Request[a2a888.GetOrganizationRequest]) (*connect.Response[a2a888.GetOrganizationResponse], error)
	SwitchOrganization(context.Context, *connect.Request[a2a888.SwitchOrganizationRequest]) (*connect.Response[a2a888.SwitchOrganizationResponse], error)
	ListWorkspaces(context.Context, *connect.Request[a2a888.ListWorkspacesRequest]) (*connect.Response[a2a888.ListWorkspacesResponse], error)
	ListMemberships(context.Context, *connect.Request[a2a888.ListMembershipsRequest]) (*connect.Response[a2a888.ListMembershipsResponse], error)
}

// NewOrganizationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrganizationServiceHandler(svc OrganizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	organizationServiceMethods := a2a888.File_a2a888_organization_proto.Services().ByName("OrganizationService").Methods()
	organizationServiceListOrganizationsHandler := connect.NewUnaryHandler(
		OrganizationServiceListOrganizationsProcedure,
		svc.ListOrganizations,
		connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceGetOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceGetOrganizationProcedure,
		svc.GetOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceSwitchOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceSwitchOrganizationProcedure,
		svc.SwitchOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("SwitchOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceListWorkspacesHandler := connect.NewUnaryHandler(
		OrganizationServiceListWorkspacesProcedure,
		svc.ListWorkspaces,
		connect.WithSchema(organizationServiceMethods.ByName("ListWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceListMembershipsHandler := connect.NewUnaryHandler(
		OrganizationServiceListMembershipsProcedure,
		svc.ListMemberships,
		connect.WithSchema(organizationServiceMethods.ByName("ListMemberships")),
		connect.WithHandlerOptions(opts...),
	)
	return "/a2a888.v1.OrganizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrganizationServiceListOrganizationsProcedure:
			organizationServiceListOrganizationsHandler.ServeHTTP(w, r)
		case OrganizationServiceGetOrganizationProcedure:
			organizationServiceGetOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceSwitchOrganizationProcedure:
			organizationServiceSwitchOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceListWorkspacesProcedure:
			organizationServiceListWorkspacesHandler.ServeHTTP(w, r)
		case OrganizationServiceListMembershipsProcedure:
			organizationServiceListMembershipsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrganizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrganizationServiceHandler struct{}

func (UnimplementedOrganizationServiceHandler) ListOrganizations(context.Context, *connect.Request[a2a888.ListOrganizationsRequest]) (*connect.Response[a2a888.ListOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.OrganizationService.ListOrganizations is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) GetOrganization(context.Context, *connect.Request[a2a888.GetOrganizationRequest]) (*connect.Response[a2a888.GetOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.OrganizationService.GetOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) SwitchOrganization(context.Context, *connect.Request[a2a888.SwitchOrganizationRequest]) (*connect.Response[a2a888.SwitchOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.OrganizationService.SwitchOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) ListWorkspaces(context.Context, *connect.Request[a2a888.ListWorkspacesRequest]) (*connect.Response[a2a888.ListWorkspacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.OrganizationService.ListWorkspaces is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) ListMemberships(context.Context, *connect.Request[a2a888.ListMembershipsRequest]) (*connect.Response[a2a888.ListMembershipsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("a2a888.v1.OrganizationService.ListMemberships is not implemented"))
}
