// @generated by protoc-gen-es v2.12.0
// @generated from file a2a888/agent_runtime.proto (package a2a888.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file a2a888/agent_runtime.proto.
 */
export declare const file_a2a888_agent_runtime: GenFile;

/**
 * ProviderManifest describes how a provider runtime is identified, installed,
 * started, and authorized on a supported platform.
 *
 * @generated from message a2a888.v1.ProviderManifest
 */
export declare type ProviderManifest = Message<"a2a888.v1.ProviderManifest"> & {
  /**
   * Stable provider identifier. Provider IDs are intentionally strings so that
   * providers can be added without changing this contract.
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: a2a888.v1.RuntimeKind runtime_kind = 3;
   */
  runtimeKind: RuntimeKind;

  /**
   * @generated from field: a2a888.v1.AgentProtocol agent_protocol = 4;
   */
  agentProtocol: AgentProtocol;

  /**
   * @generated from field: repeated a2a888.v1.PlatformTarget platform_targets = 5;
   */
  platformTargets: PlatformTarget[];

  /**
   * Exactly one runtime configuration must be supplied.
   *
   * @generated from oneof a2a888.v1.ProviderManifest.runtime_config
   */
  runtimeConfig: {
    /**
     * @generated from field: a2a888.v1.SystemExecutableConfig system_executable = 6;
     */
    value: SystemExecutableConfig;
    case: "systemExecutable";
  } | {
    /**
     * @generated from field: a2a888.v1.NpmPackageConfig npm_package = 7;
     */
    value: NpmPackageConfig;
    case: "npmPackage";
  } | {
    /**
     * @generated from field: a2a888.v1.EmbeddedRuntimeConfig embedded = 13;
     */
    value: EmbeddedRuntimeConfig;
    case: "embedded";
  } | {
    /**
     * @generated from field: a2a888.v1.CustomRuntimeConfig custom = 14;
     */
    value: CustomRuntimeConfig;
    case: "custom";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: a2a888.v1.ProviderCapabilities capabilities = 8;
   */
  capabilities?: ProviderCapabilities | undefined;

  /**
   * @generated from field: a2a888.v1.PermissionProfile permission_profile = 9;
   */
  permissionProfile?: PermissionProfile | undefined;

  /**
   * @generated from field: a2a888.v1.SessionBehavior session_behavior = 10;
   */
  sessionBehavior?: SessionBehavior | undefined;

  /**
   * @generated from field: string manifest_version = 11;
   */
  manifestVersion: string;

  /**
   * @generated from field: string manifest_integrity_sha256 = 12;
   */
  manifestIntegritySha256: string;
};

/**
 * Describes the message a2a888.v1.ProviderManifest.
 * Use `create(ProviderManifestSchema)` to create a new message.
 */
export declare const ProviderManifestSchema: GenMessage<ProviderManifest>;

/**
 * PlatformTarget uses normalized runtime platform names, such as linux,
 * darwin, windows, amd64, arm64, and glibc.
 *
 * @generated from message a2a888.v1.PlatformTarget
 */
export declare type PlatformTarget = Message<"a2a888.v1.PlatformTarget"> & {
  /**
   * @generated from field: string operating_system = 1;
   */
  operatingSystem: string;

  /**
   * @generated from field: string architecture = 2;
   */
  architecture: string;

  /**
   * @generated from field: string libc = 3;
   */
  libc: string;

  /**
   * @generated from field: string variant = 4;
   */
  variant: string;
};

/**
 * Describes the message a2a888.v1.PlatformTarget.
 * Use `create(PlatformTargetSchema)` to create a new message.
 */
export declare const PlatformTargetSchema: GenMessage<PlatformTarget>;

/**
 * SystemExecutableConfig identifies an executable already installed or
 * provided by the host operating system.
 *
 * @generated from message a2a888.v1.SystemExecutableConfig
 */
export declare type SystemExecutableConfig = Message<"a2a888.v1.SystemExecutableConfig"> & {
  /**
   * @generated from field: string executable = 1;
   */
  executable: string;

  /**
   * @generated from field: repeated string arguments = 2;
   */
  arguments: string[];

  /**
   * @generated from field: string version_argument = 3;
   */
  versionArgument: string;

  /**
   * @generated from field: string version_pattern = 4;
   */
  versionPattern: string;

  /**
   * @generated from field: string package_manager = 5;
   */
  packageManager: string;

  /**
   * @generated from field: string package_name = 6;
   */
  packageName: string;

  /**
   * @generated from field: string package_version = 7;
   */
  packageVersion: string;

  /**
   * @generated from field: string integrity_sha256 = 8;
   */
  integritySha256: string;

  /**
   * Names of host environment variables that may be inherited; values are
   * supplied by the runtime host and are never stored in the manifest.
   *
   * @generated from field: repeated string inherited_environment = 9;
   */
  inheritedEnvironment: string[];
};

/**
 * Describes the message a2a888.v1.SystemExecutableConfig.
 * Use `create(SystemExecutableConfigSchema)` to create a new message.
 */
export declare const SystemExecutableConfigSchema: GenMessage<SystemExecutableConfig>;

/**
 * NpmPackageConfig pins every value needed to resolve an npm runtime.
 *
 * @generated from message a2a888.v1.NpmPackageConfig
 */
export declare type NpmPackageConfig = Message<"a2a888.v1.NpmPackageConfig"> & {
  /**
   * @generated from field: string package_name = 1;
   */
  packageName: string;

  /**
   * @generated from field: string package_version = 2;
   */
  packageVersion: string;

  /**
   * @generated from field: string binary = 3;
   */
  binary: string;

  /**
   * Subresource Integrity (SRI) value for the exact package artifact.
   *
   * @generated from field: string integrity = 4;
   */
  integrity: string;

  /**
   * @generated from field: string registry = 5;
   */
  registry: string;

  /**
   * @generated from field: repeated string arguments = 6;
   */
  arguments: string[];
};

/**
 * Describes the message a2a888.v1.NpmPackageConfig.
 * Use `create(NpmPackageConfigSchema)` to create a new message.
 */
export declare const NpmPackageConfigSchema: GenMessage<NpmPackageConfig>;

/**
 * EmbeddedRuntimeConfig identifies a runtime shipped with the host service.
 *
 * @generated from message a2a888.v1.EmbeddedRuntimeConfig
 */
export declare type EmbeddedRuntimeConfig = Message<"a2a888.v1.EmbeddedRuntimeConfig"> & {
  /**
   * @generated from field: string artifact = 1;
   */
  artifact: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * @generated from field: string binary = 3;
   */
  binary: string;

  /**
   * @generated from field: string integrity_sha256 = 4;
   */
  integritySha256: string;
};

/**
 * Describes the message a2a888.v1.EmbeddedRuntimeConfig.
 * Use `create(EmbeddedRuntimeConfigSchema)` to create a new message.
 */
export declare const EmbeddedRuntimeConfigSchema: GenMessage<EmbeddedRuntimeConfig>;

/**
 * CustomRuntimeConfig describes a provider-specific launch command.
 *
 * @generated from message a2a888.v1.CustomRuntimeConfig
 */
export declare type CustomRuntimeConfig = Message<"a2a888.v1.CustomRuntimeConfig"> & {
  /**
   * @generated from field: string command = 1;
   */
  command: string;

  /**
   * @generated from field: repeated string arguments = 2;
   */
  arguments: string[];

  /**
   * Names of host environment variables that may be inherited; values are
   * supplied by the runtime host and are never stored in the manifest.
   *
   * @generated from field: repeated string inherited_environment = 3;
   */
  inheritedEnvironment: string[];

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: string integrity_sha256 = 5;
   */
  integritySha256: string;
};

/**
 * Describes the message a2a888.v1.CustomRuntimeConfig.
 * Use `create(CustomRuntimeConfigSchema)` to create a new message.
 */
export declare const CustomRuntimeConfigSchema: GenMessage<CustomRuntimeConfig>;

/**
 * ProviderCapabilities is a typed capability declaration for runtime
 * discovery and session orchestration.
 *
 * @generated from message a2a888.v1.ProviderCapabilities
 */
export declare type ProviderCapabilities = Message<"a2a888.v1.ProviderCapabilities"> & {
  /**
   * @generated from field: bool model_discovery = 1;
   */
  modelDiscovery: boolean;

  /**
   * @generated from field: bool session_resume = 2;
   */
  sessionResume: boolean;

  /**
   * @generated from field: bool streaming = 3;
   */
  streaming: boolean;

  /**
   * @generated from field: bool steering = 4;
   */
  steering: boolean;

  /**
   * @generated from field: bool mcp = 5;
   */
  mcp: boolean;

  /**
   * @generated from field: bool tool_traces = 6;
   */
  toolTraces: boolean;
};

/**
 * Describes the message a2a888.v1.ProviderCapabilities.
 * Use `create(ProviderCapabilitiesSchema)` to create a new message.
 */
export declare const ProviderCapabilitiesSchema: GenMessage<ProviderCapabilities>;

/**
 * PermissionProfile records the least-privilege permissions requested by a
 * runtime. Empty allowlists mean that the corresponding access is denied.
 *
 * @generated from message a2a888.v1.PermissionProfile
 */
export declare type PermissionProfile = Message<"a2a888.v1.PermissionProfile"> & {
  /**
   * @generated from field: bool process_execution = 1;
   */
  processExecution: boolean;

  /**
   * @generated from field: bool inherit_environment = 2;
   */
  inheritEnvironment: boolean;

  /**
   * @generated from field: repeated string filesystem_read_paths = 3;
   */
  filesystemReadPaths: string[];

  /**
   * @generated from field: repeated string filesystem_write_paths = 4;
   */
  filesystemWritePaths: string[];

  /**
   * @generated from field: repeated string network_hosts = 5;
   */
  networkHosts: string[];

  /**
   * @generated from field: bool network_access = 6;
   */
  networkAccess: boolean;
};

/**
 * Describes the message a2a888.v1.PermissionProfile.
 * Use `create(PermissionProfileSchema)` to create a new message.
 */
export declare const PermissionProfileSchema: GenMessage<PermissionProfile>;

/**
 * SessionBehavior defines lifecycle and resume expectations for provider
 * sessions.
 *
 * @generated from message a2a888.v1.SessionBehavior
 */
export declare type SessionBehavior = Message<"a2a888.v1.SessionBehavior"> & {
  /**
   * @generated from field: a2a888.v1.SessionMode mode = 1;
   */
  mode: SessionMode;

  /**
   * @generated from field: bool supports_resume = 2;
   */
  supportsResume: boolean;

  /**
   * @generated from field: bool supports_concurrent_sessions = 3;
   */
  supportsConcurrentSessions: boolean;

  /**
   * @generated from field: uint32 idle_timeout_seconds = 4;
   */
  idleTimeoutSeconds: number;

  /**
   * @generated from field: bool requires_clean_shutdown = 5;
   */
  requiresCleanShutdown: boolean;
};

/**
 * Describes the message a2a888.v1.SessionBehavior.
 * Use `create(SessionBehaviorSchema)` to create a new message.
 */
export declare const SessionBehaviorSchema: GenMessage<SessionBehavior>;

/**
 * PreparedRuntime is the immutable result of resolving and verifying a
 * ProviderManifest for one platform.
 *
 * @generated from message a2a888.v1.PreparedRuntime
 */
export declare type PreparedRuntime = Message<"a2a888.v1.PreparedRuntime"> & {
  /**
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * @generated from field: a2a888.v1.CacheIdentity cache_identity = 2;
   */
  cacheIdentity?: CacheIdentity | undefined;

  /**
   * @generated from field: a2a888.v1.ResolvedBinary resolved_binary = 3;
   */
  resolvedBinary?: ResolvedBinary | undefined;

  /**
   * @generated from field: a2a888.v1.RuntimeStatus status = 4;
   */
  status?: RuntimeStatus | undefined;

  /**
   * @generated from field: a2a888.v1.CompatibilityReport compatibility = 5;
   */
  compatibility?: CompatibilityReport | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp prepared_at = 6;
   */
  preparedAt?: Timestamp | undefined;
};

/**
 * Describes the message a2a888.v1.PreparedRuntime.
 * Use `create(PreparedRuntimeSchema)` to create a new message.
 */
export declare const PreparedRuntimeSchema: GenMessage<PreparedRuntime>;

/**
 * CacheIdentity is content-addressed and must not change for the lifetime of a
 * prepared runtime. A changed manifest or artifact creates a new identity.
 *
 * @generated from message a2a888.v1.CacheIdentity
 */
export declare type CacheIdentity = Message<"a2a888.v1.CacheIdentity"> & {
  /**
   * @generated from field: string identity_digest = 1;
   */
  identityDigest: string;

  /**
   * @generated from field: string provider_id = 2;
   */
  providerId: string;

  /**
   * @generated from field: string manifest_digest = 3;
   */
  manifestDigest: string;

  /**
   * @generated from field: string runtime_version = 4;
   */
  runtimeVersion: string;

  /**
   * @generated from field: a2a888.v1.PlatformTarget platform = 5;
   */
  platform?: PlatformTarget | undefined;

  /**
   * @generated from field: string lock_digest = 6;
   */
  lockDigest: string;

  /**
   * @generated from field: string package_name = 7;
   */
  packageName: string;

  /**
   * @generated from field: string package_version = 8;
   */
  packageVersion: string;

  /**
   * SRI integrity value for package-backed runtimes.
   *
   * @generated from field: string integrity = 9;
   */
  integrity: string;
};

/**
 * Describes the message a2a888.v1.CacheIdentity.
 * Use `create(CacheIdentitySchema)` to create a new message.
 */
export declare const CacheIdentitySchema: GenMessage<CacheIdentity>;

/**
 * ResolvedBinary identifies the exact executable selected for a prepared
 * runtime, including its content digest.
 *
 * @generated from message a2a888.v1.ResolvedBinary
 */
export declare type ResolvedBinary = Message<"a2a888.v1.ResolvedBinary"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string binary = 2;
   */
  binary: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: string sha256 = 4;
   */
  sha256: string;

  /**
   * @generated from field: uint64 size_bytes = 5;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string source = 6;
   */
  source: string;

  /**
   * @generated from field: repeated string arguments = 7;
   */
  arguments: string[];
};

/**
 * Describes the message a2a888.v1.ResolvedBinary.
 * Use `create(ResolvedBinarySchema)` to create a new message.
 */
export declare const ResolvedBinarySchema: GenMessage<ResolvedBinary>;

/**
 * @generated from message a2a888.v1.RuntimeStatus
 */
export declare type RuntimeStatus = Message<"a2a888.v1.RuntimeStatus"> & {
  /**
   * @generated from field: a2a888.v1.RuntimeState state = 1;
   */
  state: RuntimeState;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string observed_version = 3;
   */
  observedVersion: string;

  /**
   * @generated from field: google.protobuf.Timestamp observed_at = 4;
   */
  observedAt?: Timestamp | undefined;

  /**
   * @generated from field: string failure_code = 5;
   */
  failureCode: string;
};

/**
 * Describes the message a2a888.v1.RuntimeStatus.
 * Use `create(RuntimeStatusSchema)` to create a new message.
 */
export declare const RuntimeStatusSchema: GenMessage<RuntimeStatus>;

/**
 * CompatibilityReport records the strongest verified compatibility level and
 * the evidence that supports it.
 *
 * @generated from message a2a888.v1.CompatibilityReport
 */
export declare type CompatibilityReport = Message<"a2a888.v1.CompatibilityReport"> & {
  /**
   * @generated from field: a2a888.v1.CompatibilityLevel level = 1;
   */
  level: CompatibilityLevel;

  /**
   * @generated from field: repeated a2a888.v1.CompatibilityEvidence evidence = 2;
   */
  evidence: CompatibilityEvidence[];
};

/**
 * Describes the message a2a888.v1.CompatibilityReport.
 * Use `create(CompatibilityReportSchema)` to create a new message.
 */
export declare const CompatibilityReportSchema: GenMessage<CompatibilityReport>;

/**
 * CompatibilityEvidence is an auditable result from a detection or test run.
 *
 * @generated from message a2a888.v1.CompatibilityEvidence
 */
export declare type CompatibilityEvidence = Message<"a2a888.v1.CompatibilityEvidence"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: a2a888.v1.PlatformTarget platform = 2;
   */
  platform?: PlatformTarget | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp tested_at = 3;
   */
  testedAt?: Timestamp | undefined;

  /**
   * @generated from field: string details = 4;
   */
  details: string;
};

/**
 * Describes the message a2a888.v1.CompatibilityEvidence.
 * Use `create(CompatibilityEvidenceSchema)` to create a new message.
 */
export declare const CompatibilityEvidenceSchema: GenMessage<CompatibilityEvidence>;

/**
 * @generated from enum a2a888.v1.RuntimeKind
 */
export enum RuntimeKind {
  /**
   * @generated from enum value: RUNTIME_KIND_UNSPECIFIED = 0;
   */
  RUNTIME_KIND_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SYSTEM_EXECUTABLE = 1;
   */
  SYSTEM_EXECUTABLE = 1,

  /**
   * @generated from enum value: NPM_PACKAGE = 2;
   */
  NPM_PACKAGE = 2,

  /**
   * @generated from enum value: EMBEDDED = 3;
   */
  EMBEDDED = 3,

  /**
   * @generated from enum value: CUSTOM_RUNTIME = 4;
   */
  CUSTOM_RUNTIME = 4,
}

/**
 * Describes the enum a2a888.v1.RuntimeKind.
 */
export declare const RuntimeKindSchema: GenEnum<RuntimeKind>;

/**
 * @generated from enum a2a888.v1.AgentProtocol
 */
export enum AgentProtocol {
  /**
   * @generated from enum value: AGENT_PROTOCOL_UNSPECIFIED = 0;
   */
  AGENT_PROTOCOL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACP_V1 = 1;
   */
  ACP_V1 = 1,

  /**
   * @generated from enum value: ACP_V2 = 2;
   */
  ACP_V2 = 2,

  /**
   * @generated from enum value: A2A = 3;
   */
  A2A = 3,

  /**
   * @generated from enum value: CUSTOM_PROTOCOL = 4;
   */
  CUSTOM_PROTOCOL = 4,
}

/**
 * Describes the enum a2a888.v1.AgentProtocol.
 */
export declare const AgentProtocolSchema: GenEnum<AgentProtocol>;

/**
 * @generated from enum a2a888.v1.SessionMode
 */
export enum SessionMode {
  /**
   * @generated from enum value: SESSION_MODE_UNSPECIFIED = 0;
   */
  SESSION_MODE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: EPHEMERAL = 1;
   */
  EPHEMERAL = 1,

  /**
   * @generated from enum value: PERSISTENT = 2;
   */
  PERSISTENT = 2,
}

/**
 * Describes the enum a2a888.v1.SessionMode.
 */
export declare const SessionModeSchema: GenEnum<SessionMode>;

/**
 * @generated from enum a2a888.v1.RuntimeState
 */
export enum RuntimeState {
  /**
   * @generated from enum value: RUNTIME_STATE_UNSPECIFIED = 0;
   */
  RUNTIME_STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNAVAILABLE = 1;
   */
  UNAVAILABLE = 1,

  /**
   * @generated from enum value: INSTALLING = 2;
   */
  INSTALLING = 2,

  /**
   * @generated from enum value: VERIFYING = 3;
   */
  VERIFYING = 3,

  /**
   * @generated from enum value: READY = 4;
   */
  READY = 4,

  /**
   * @generated from enum value: BROKEN = 5;
   */
  BROKEN = 5,

  /**
   * @generated from enum value: QUARANTINED = 6;
   */
  QUARANTINED = 6,

  /**
   * @generated from enum value: UPDATE_AVAILABLE = 7;
   */
  UPDATE_AVAILABLE = 7,
}

/**
 * Describes the enum a2a888.v1.RuntimeState.
 */
export declare const RuntimeStateSchema: GenEnum<RuntimeState>;

/**
 * @generated from enum a2a888.v1.CompatibilityLevel
 */
export enum CompatibilityLevel {
  /**
   * @generated from enum value: COMPATIBILITY_LEVEL_UNSPECIFIED = 0;
   */
  COMPATIBILITY_LEVEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: DETECTED = 1;
   */
  DETECTED = 1,

  /**
   * @generated from enum value: PROTOCOL_READY = 2;
   */
  PROTOCOL_READY = 2,

  /**
   * @generated from enum value: FUNCTIONALLY_VERIFIED = 3;
   */
  FUNCTIONALLY_VERIFIED = 3,

  /**
   * @generated from enum value: FULL_LOOP_VERIFIED = 4;
   */
  FULL_LOOP_VERIFIED = 4,
}

/**
 * Describes the enum a2a888.v1.CompatibilityLevel.
 */
export declare const CompatibilityLevelSchema: GenEnum<CompatibilityLevel>;
