// @generated by protoc-gen-es v2.12.0
// @generated from file a2a888/approval.proto (package a2a888.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file a2a888/approval.proto.
 */
export declare const file_a2a888_approval: GenFile;

/**
 * ApprovalPolicy describes one versioned, organization-scoped approval rule.
 *
 * @generated from message a2a888.v1.ApprovalPolicy
 */
export declare type ApprovalPolicy = Message<"a2a888.v1.ApprovalPolicy"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string resource_pattern = 4;
   */
  resourcePattern: string;

  /**
   * @generated from field: string agent_id = 5;
   */
  agentId: string;

  /**
   * @generated from field: string skill = 6;
   */
  skill: string;

  /**
   * @generated from field: string action_type = 7;
   */
  actionType: string;

  /**
   * @generated from field: string destination_pattern = 8;
   */
  destinationPattern: string;

  /**
   * @generated from field: string requester_class = 9;
   */
  requesterClass: string;

  /**
   * @generated from field: a2a888.v1.ApprovalRiskLevel risk_level = 10;
   */
  riskLevel: ApprovalRiskLevel;

  /**
   * @generated from field: repeated string approver_principal_ids = 11;
   */
  approverPrincipalIds: string[];

  /**
   * @generated from field: repeated string approver_group_ids = 12;
   */
  approverGroupIds: string[];

  /**
   * @generated from field: repeated string approver_roles = 13;
   */
  approverRoles: string[];

  /**
   * @generated from field: uint32 required_approvals = 14;
   */
  requiredApprovals: number;

  /**
   * @generated from field: uint32 timeout_seconds = 15;
   */
  timeoutSeconds: number;

  /**
   * @generated from field: a2a888.v1.ApprovalTimeoutAction on_timeout = 16;
   */
  onTimeout: ApprovalTimeoutAction;

  /**
   * @generated from field: repeated string escalation_principal_ids = 17;
   */
  escalationPrincipalIds: string[];

  /**
   * @generated from field: repeated string escalation_group_ids = 18;
   */
  escalationGroupIds: string[];

  /**
   * @generated from field: repeated string escalation_roles = 19;
   */
  escalationRoles: string[];

  /**
   * @generated from field: bool prohibit_requester_approval = 20;
   */
  prohibitRequesterApproval: boolean;

  /**
   * @generated from field: bool prohibit_agent_owner_sole_approval = 21;
   */
  prohibitAgentOwnerSoleApproval: boolean;

  /**
   * @generated from field: string version = 22;
   */
  version: string;

  /**
   * @generated from field: bool enabled = 23;
   */
  enabled: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 24;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 25;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message a2a888.v1.ApprovalPolicy.
 * Use `create(ApprovalPolicySchema)` to create a new message.
 */
export declare const ApprovalPolicySchema: GenMessage<ApprovalPolicy>;

/**
 * BoundAction is the immutable, normalized action that an approval authorizes.
 * normalized_parameters_json is the canonical serialization used to calculate
 * intent_hash; normalized_parameters is the structured review representation.
 *
 * @generated from message a2a888.v1.BoundAction
 */
export declare type BoundAction = Message<"a2a888.v1.BoundAction"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string resource_name = 3;
   */
  resourceName: string;

  /**
   * @generated from field: string agent_id = 4;
   */
  agentId: string;

  /**
   * @generated from field: string skill = 5;
   */
  skill: string;

  /**
   * @generated from field: string action_type = 6;
   */
  actionType: string;

  /**
   * @generated from field: string destination = 7;
   */
  destination: string;

  /**
   * @generated from field: a2a888.v1.ApprovalRiskLevel risk_level = 8;
   */
  riskLevel: ApprovalRiskLevel;

  /**
   * @generated from field: google.protobuf.Struct normalized_parameters = 9;
   */
  normalizedParameters?: JsonObject | undefined;

  /**
   * @generated from field: string normalized_parameters_json = 10;
   */
  normalizedParametersJson: string;

  /**
   * @generated from field: string intent_hash = 11;
   */
  intentHash: string;

  /**
   * @generated from field: string task_id = 12;
   */
  taskId: string;

  /**
   * @generated from field: string command_id = 13;
   */
  commandId: string;
};

/**
 * Describes the message a2a888.v1.BoundAction.
 * Use `create(BoundActionSchema)` to create a new message.
 */
export declare const BoundActionSchema: GenMessage<BoundAction>;

/**
 * ApprovalRequest binds a policy decision to one requester, Agent, action and
 * single-use execution nonce.
 *
 * @generated from message a2a888.v1.ApprovalRequest
 */
export declare type ApprovalRequest = Message<"a2a888.v1.ApprovalRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string workspace_id = 3;
   */
  workspaceId: string;

  /**
   * @generated from field: string policy_name = 4;
   */
  policyName: string;

  /**
   * @generated from field: string policy_version = 5;
   */
  policyVersion: string;

  /**
   * @generated from field: string requester_principal_id = 6;
   */
  requesterPrincipalId: string;

  /**
   * @generated from field: string executing_agent_id = 7;
   */
  executingAgentId: string;

  /**
   * @generated from field: string executing_agent_owner_id = 8;
   */
  executingAgentOwnerId: string;

  /**
   * @generated from field: a2a888.v1.BoundAction action = 9;
   */
  action?: BoundAction | undefined;

  /**
   * @generated from field: a2a888.v1.ApprovalRequestState state = 10;
   */
  state: ApprovalRequestState;

  /**
   * @generated from field: uint32 required_approvals = 11;
   */
  requiredApprovals: number;

  /**
   * @generated from field: uint32 approval_count = 12;
   */
  approvalCount: number;

  /**
   * @generated from field: string execution_nonce = 13;
   */
  executionNonce: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 14;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 15;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 16;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 17;
   */
  completedAt?: Timestamp | undefined;

  /**
   * @generated from field: string terminal_reason = 18;
   */
  terminalReason: string;
};

/**
 * Describes the message a2a888.v1.ApprovalRequest.
 * Use `create(ApprovalRequestSchema)` to create a new message.
 */
export declare const ApprovalRequestSchema: GenMessage<ApprovalRequest>;

/**
 * ApprovalDecision is an immutable decision made by one eligible principal.
 *
 * @generated from message a2a888.v1.ApprovalDecision
 */
export declare type ApprovalDecision = Message<"a2a888.v1.ApprovalDecision"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string request_name = 2;
   */
  requestName: string;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId: string;

  /**
   * @generated from field: string approver_principal_id = 4;
   */
  approverPrincipalId: string;

  /**
   * @generated from field: string approver_role = 5;
   */
  approverRole: string;

  /**
   * @generated from field: a2a888.v1.ApprovalDecisionOutcome outcome = 6;
   */
  outcome: ApprovalDecisionOutcome;

  /**
   * @generated from field: string reason = 7;
   */
  reason: string;

  /**
   * @generated from field: string intent_hash = 8;
   */
  intentHash: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message a2a888.v1.ApprovalDecision.
 * Use `create(ApprovalDecisionSchema)` to create a new message.
 */
export declare const ApprovalDecisionSchema: GenMessage<ApprovalDecision>;

/**
 * ApprovalRiskLevel classifies the side-effect risk of a bound action.
 *
 * @generated from enum a2a888.v1.ApprovalRiskLevel
 */
export enum ApprovalRiskLevel {
  /**
   * @generated from enum value: APPROVAL_RISK_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPROVAL_RISK_LEVEL_LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: APPROVAL_RISK_LEVEL_MODERATE = 2;
   */
  MODERATE = 2,

  /**
   * @generated from enum value: APPROVAL_RISK_LEVEL_HIGH = 3;
   */
  HIGH = 3,

  /**
   * @generated from enum value: APPROVAL_RISK_LEVEL_CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum a2a888.v1.ApprovalRiskLevel.
 */
export declare const ApprovalRiskLevelSchema: GenEnum<ApprovalRiskLevel>;

/**
 * ApprovalTimeoutAction defines the policy behavior when quorum is not reached.
 *
 * @generated from enum a2a888.v1.ApprovalTimeoutAction
 */
export enum ApprovalTimeoutAction {
  /**
   * @generated from enum value: APPROVAL_TIMEOUT_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPROVAL_TIMEOUT_ACTION_DENY = 1;
   */
  DENY = 1,

  /**
   * @generated from enum value: APPROVAL_TIMEOUT_ACTION_ESCALATE = 2;
   */
  ESCALATE = 2,
}

/**
 * Describes the enum a2a888.v1.ApprovalTimeoutAction.
 */
export declare const ApprovalTimeoutActionSchema: GenEnum<ApprovalTimeoutAction>;

/**
 * ApprovalRequestState is the durable lifecycle of an approval request.
 *
 * @generated from enum a2a888.v1.ApprovalRequestState
 */
export enum ApprovalRequestState {
  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_APPROVED = 2;
   */
  APPROVED = 2,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_DENIED = 3;
   */
  DENIED = 3,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_EXPIRED = 4;
   */
  EXPIRED = 4,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_CANCELLED = 5;
   */
  CANCELLED = 5,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_SUPERSEDED = 6;
   */
  SUPERSEDED = 6,

  /**
   * @generated from enum value: APPROVAL_REQUEST_STATE_EXECUTED = 7;
   */
  EXECUTED = 7,
}

/**
 * Describes the enum a2a888.v1.ApprovalRequestState.
 */
export declare const ApprovalRequestStateSchema: GenEnum<ApprovalRequestState>;

/**
 * ApprovalDecisionOutcome is the decision recorded by one eligible approver.
 *
 * @generated from enum a2a888.v1.ApprovalDecisionOutcome
 */
export enum ApprovalDecisionOutcome {
  /**
   * @generated from enum value: APPROVAL_DECISION_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPROVAL_DECISION_OUTCOME_APPROVE = 1;
   */
  APPROVE = 1,

  /**
   * @generated from enum value: APPROVAL_DECISION_OUTCOME_DENY = 2;
   */
  DENY = 2,
}

/**
 * Describes the enum a2a888.v1.ApprovalDecisionOutcome.
 */
export declare const ApprovalDecisionOutcomeSchema: GenEnum<ApprovalDecisionOutcome>;

