// @generated by protoc-gen-es v2.12.0
// @generated from file a2a888/connector.proto (package a2a888.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file a2a888/connector.proto.
 */
export declare const file_a2a888_connector: GenFile;

/**
 * @generated from message a2a888.v1.ConnectorInstallation
 */
export declare type ConnectorInstallation = Message<"a2a888.v1.ConnectorInstallation"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string installation_id = 3;
   */
  installationId: string;

  /**
   * @generated from field: string kind = 4;
   */
  kind: string;

  /**
   * @generated from field: bool enabled = 5;
   */
  enabled: boolean;

  /**
   * @generated from field: repeated string capabilities = 6;
   */
  capabilities: string[];

  /**
   * @generated from field: a2a888.v1.ConnectorHealth health = 7;
   */
  health: ConnectorHealth;

  /**
   * @generated from field: int64 pending_deliveries = 8;
   */
  pendingDeliveries: bigint;

  /**
   * @generated from field: int64 dead_letter_deliveries = 9;
   */
  deadLetterDeliveries: bigint;

  /**
   * @generated from field: string last_error = 10;
   */
  lastError: string;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 11;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message a2a888.v1.ConnectorInstallation.
 * Use `create(ConnectorInstallationSchema)` to create a new message.
 */
export declare const ConnectorInstallationSchema: GenMessage<ConnectorInstallation>;

/**
 * @generated from message a2a888.v1.ListConnectorInstallationsRequest
 */
export declare type ListConnectorInstallationsRequest = Message<"a2a888.v1.ListConnectorInstallationsRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;
};

/**
 * Describes the message a2a888.v1.ListConnectorInstallationsRequest.
 * Use `create(ListConnectorInstallationsRequestSchema)` to create a new message.
 */
export declare const ListConnectorInstallationsRequestSchema: GenMessage<ListConnectorInstallationsRequest>;

/**
 * @generated from message a2a888.v1.ListConnectorInstallationsResponse
 */
export declare type ListConnectorInstallationsResponse = Message<"a2a888.v1.ListConnectorInstallationsResponse"> & {
  /**
   * @generated from field: repeated a2a888.v1.ConnectorInstallation installations = 1;
   */
  installations: ConnectorInstallation[];
};

/**
 * Describes the message a2a888.v1.ListConnectorInstallationsResponse.
 * Use `create(ListConnectorInstallationsResponseSchema)` to create a new message.
 */
export declare const ListConnectorInstallationsResponseSchema: GenMessage<ListConnectorInstallationsResponse>;

/**
 * @generated from enum a2a888.v1.ConnectorHealth
 */
export enum ConnectorHealth {
  /**
   * @generated from enum value: CONNECTOR_HEALTH_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONNECTOR_HEALTH_HEALTHY = 1;
   */
  HEALTHY = 1,

  /**
   * @generated from enum value: CONNECTOR_HEALTH_DEGRADED = 2;
   */
  DEGRADED = 2,

  /**
   * @generated from enum value: CONNECTOR_HEALTH_FAILED = 3;
   */
  FAILED = 3,

  /**
   * @generated from enum value: CONNECTOR_HEALTH_DISABLED = 4;
   */
  DISABLED = 4,
}

/**
 * Describes the enum a2a888.v1.ConnectorHealth.
 */
export declare const ConnectorHealthSchema: GenEnum<ConnectorHealth>;

/**
 * @generated from service a2a888.v1.ConnectorService
 */
export declare const ConnectorService: GenService<{
  /**
   * @generated from rpc a2a888.v1.ConnectorService.ListConnectorInstallations
   */
  listConnectorInstallations: {
    methodKind: "unary";
    input: typeof ListConnectorInstallationsRequestSchema;
    output: typeof ListConnectorInstallationsResponseSchema;
  },
}>;
