// @generated by protoc-gen-es v2.12.0
// @generated from file a2a888/connector.proto (package a2a888.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file a2a888/connector.proto.
 */
export const file_a2a888_connector = /*@__PURE__*/
  fileDesc("ChZhMmE4ODgvY29ubmVjdG9yLnByb3RvEglhMmE4ODgudjEiuAIKFUNvbm5lY3Rvckluc3RhbGxhdGlvbhIMCgRuYW1lGAEgASgJEhcKD29yZ2FuaXphdGlvbl9pZBgCIAEoCRIXCg9pbnN0YWxsYXRpb25faWQYAyABKAkSDAoEa2luZBgEIAEoCRIPCgdlbmFibGVkGAUgASgIEhQKDGNhcGFiaWxpdGllcxgGIAMoCRIqCgZoZWFsdGgYByABKA4yGi5hMmE4ODgudjEuQ29ubmVjdG9ySGVhbHRoEhoKEnBlbmRpbmdfZGVsaXZlcmllcxgIIAEoAxIeChZkZWFkX2xldHRlcl9kZWxpdmVyaWVzGAkgASgDEhIKCmxhc3RfZXJyb3IYCiABKAkSLgoKdXBkYXRlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiPAohTGlzdENvbm5lY3Rvckluc3RhbGxhdGlvbnNSZXF1ZXN0EhcKD29yZ2FuaXphdGlvbl9pZBgBIAEoCSJdCiJMaXN0Q29ubmVjdG9ySW5zdGFsbGF0aW9uc1Jlc3BvbnNlEjcKDWluc3RhbGxhdGlvbnMYASADKAsyIC5hMmE4ODgudjEuQ29ubmVjdG9ySW5zdGFsbGF0aW9uImUKF0luc3RhbGxDb25uZWN0b3JSZXF1ZXN0EjYKDGluc3RhbGxhdGlvbhgBIAEoCzIgLmEyYTg4OC52MS5Db25uZWN0b3JJbnN0YWxsYXRpb24SEgoKY3JlZGVudGlhbBgCIAEoDCJNChlVbmluc3RhbGxDb25uZWN0b3JSZXF1ZXN0EhcKD29yZ2FuaXphdGlvbl9pZBgBIAEoCRIXCg9pbnN0YWxsYXRpb25faWQYAiABKAkiHAoaVW5pbnN0YWxsQ29ubmVjdG9yUmVzcG9uc2UqrAEKD0Nvbm5lY3RvckhlYWx0aBIgChxDT05ORUNUT1JfSEVBTFRIX1VOU1BFQ0lGSUVEEAASHAoYQ09OTkVDVE9SX0hFQUxUSF9IRUFMVEhZEAESHQoZQ09OTkVDVE9SX0hFQUxUSF9ERUdSQURFRBACEhsKF0NPTk5FQ1RPUl9IRUFMVEhfRkFJTEVEEAMSHQoZQ09OTkVDVE9SX0hFQUxUSF9ESVNBQkxFRBAEMsoCChBDb25uZWN0b3JTZXJ2aWNlEnkKGkxpc3RDb25uZWN0b3JJbnN0YWxsYXRpb25zEiwuYTJhODg4LnYxLkxpc3RDb25uZWN0b3JJbnN0YWxsYXRpb25zUmVxdWVzdBotLmEyYTg4OC52MS5MaXN0Q29ubmVjdG9ySW5zdGFsbGF0aW9uc1Jlc3BvbnNlElgKEEluc3RhbGxDb25uZWN0b3ISIi5hMmE4ODgudjEuSW5zdGFsbENvbm5lY3RvclJlcXVlc3QaIC5hMmE4ODgudjEuQ29ubmVjdG9ySW5zdGFsbGF0aW9uEmEKElVuaW5zdGFsbENvbm5lY3RvchIkLmEyYTg4OC52MS5Vbmluc3RhbGxDb25uZWN0b3JSZXF1ZXN0GiUuYTJhODg4LnYxLlVuaW5zdGFsbENvbm5lY3RvclJlc3BvbnNlQjtaOWdpdGh1Yi5jb20vdGJkYXZpZDIwMTkvODg4YTJhL2JhY2tlbmQvZ2VuZXJhdGVkLWdvL2EyYTg4OGIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message a2a888.v1.ConnectorInstallation.
 * Use `create(ConnectorInstallationSchema)` to create a new message.
 */
export const ConnectorInstallationSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 0);

/**
 * Describes the message a2a888.v1.ListConnectorInstallationsRequest.
 * Use `create(ListConnectorInstallationsRequestSchema)` to create a new message.
 */
export const ListConnectorInstallationsRequestSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 1);

/**
 * Describes the message a2a888.v1.ListConnectorInstallationsResponse.
 * Use `create(ListConnectorInstallationsResponseSchema)` to create a new message.
 */
export const ListConnectorInstallationsResponseSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 2);

/**
 * Describes the message a2a888.v1.InstallConnectorRequest.
 * Use `create(InstallConnectorRequestSchema)` to create a new message.
 */
export const InstallConnectorRequestSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 3);

/**
 * Describes the message a2a888.v1.UninstallConnectorRequest.
 * Use `create(UninstallConnectorRequestSchema)` to create a new message.
 */
export const UninstallConnectorRequestSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 4);

/**
 * Describes the message a2a888.v1.UninstallConnectorResponse.
 * Use `create(UninstallConnectorResponseSchema)` to create a new message.
 */
export const UninstallConnectorResponseSchema = /*@__PURE__*/
  messageDesc(file_a2a888_connector, 5);

/**
 * Describes the enum a2a888.v1.ConnectorHealth.
 */
export const ConnectorHealthSchema = /*@__PURE__*/
  enumDesc(file_a2a888_connector, 0);

/**
 * @generated from enum a2a888.v1.ConnectorHealth
 */
export const ConnectorHealth = /*@__PURE__*/
  tsEnum(ConnectorHealthSchema);

/**
 * @generated from service a2a888.v1.ConnectorService
 */
export const ConnectorService = /*@__PURE__*/
  serviceDesc(file_a2a888_connector, 0);
