global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 888a2a-manager
    metrics_path: /metrics
    static_configs:
      - targets: [manager:8181]
        labels:
          service: manager
